### ISSUE TITLE
when does this repository update？

### ISSUE THREAD

**Issue by CXSunshine** [STVIR/pysot#1]
Is this directory still empty? When can you update？

**Comment by lb1100** [comment]
We will upload inference code before the end of this week.
We plan to upload the training code before the end of this month (due to the conversion of the training framework)

**Comment by CXSunshine** [comment]
> We will upload inference code before the end of this week.
> We plan to upload the training code before the end of this month (due to the conversion of the training framework)

**Comment by CXSunshine** [comment]
ok，thanks~

**Comment by dongfangduoshou123** [comment]
Greate!
