### ISSUE TITLE
ImportError: No module named 'Cython'

### ISSUE THREAD

**Issue by TeslaHua** [STVIR/pysot#10]
conda list:

cython　　　0.29.7　　　py37he6710b0_0　　　defaults

我执行：sudo python setup.py build_ext --inplace
出现错误：
Traceback (most recent call last):
  File "setup.py", line 3, in <module>
    from Cython.Build import cythonize
ImportError: No module named 'Cython'

我明明已经装了Cython了，为什么还报错呢？

**Comment by lb1100** [comment]
python with sudo may not be the python in your pysot environment. Try it without sudo.

**Comment by TeslaHua** [comment]
@lb1100 哈哈，谢谢大佬。我刚刚已经解决了，就是这个原因。不加sudo的话，出现权限错误。加了sudo就默认启动系统自带的python，所以需要直接执行虚拟环境pysot下的python的绝对路径。
