### ISSUE TITLE
nll_loss loss function raise RuntimeError

### ISSUE THREAD

**Issue by trobr** [STVIR/pysot#101]
This happens when the batchsize is small,all image pair in batch are negetive.This lead to cls label in bacth is `-1` or `0`,then in `get_cls_loss` function,
```python
loss_pos = get_cls_loss(pred, label, pos)

def get_cls_loss(pred, label, select):
    if len(select.size()) == 0:
        return 0
    pred = torch.index_select(pred, 0, select)
    label = torch.index_select(label, 0, select)
    return F.nll_loss(pred, label)
```
the `pred` and `label` tensor both emtpy,and the nll_loss loss function raise
` RuntimeError: invalid argument 2: non-empty vector or matrix expected at /pytorch/aten/src/THCUNN/generic/ClassNLLCriterion.cu:31`

**Comment by lb1100** [comment]
Should be fixed. Try the latest code.

**Comment by trobr** [comment]
@lb1100 thanks
