### ISSUE TITLE
How to achieve multiple targets tracking

### ISSUE THREAD

**Issue by pangr** [STVIR/pysot#102]
Is there a way to achieve simultaneous tracking of multiple targets? Thanks

**Comment by YachaoDong** [comment]
> 有没有办法实现多个目标的同步跟踪？谢谢

同求！请问楼主现在有木有解决这个问题

**Comment by YachaoDong** [comment]
> Is there a way to achieve simultaneous tracking of multiple targets? Thanks

Hello，have U solved this problem? Thx!!

**Comment by pangr** [comment]
> > 有没有办法实现多个目标的同步跟踪？谢谢
> 
> 同求！请问楼主现在有木有解决这个问题
还在努力

**Comment by YachaoDong** [comment]
> > > 有没有办法实现多个目标的同步跟踪？谢谢
> > 
> > 
> > 同求！请问楼主现在有木有解决这个问题
> > 还在努力
可以加个联系方式，一起讨论。

**Comment by Victoria-1** [comment]
hello, have you achieved it, or any ideas?

**Comment by 17702513221** [comment]
我个人想法是使用yolov3检测要识别的人，然后挨个识别一遍其在下一帧出现的位置以此达到多目标检测

**Comment by yc-zc** [comment]
Well, this repo is pysot, which means it focuses on using python to solve the problem of single object tracing.
However, I would #pin this issue for discussion.
