### ISSUE TITLE
other method in paper

### ISSUE THREAD

**Issue by chenbolinstudent** [STVIR/pysot#103]
other method in paper whether use the same four training dataset?
is it fair?

**Comment by yc-zc** [comment]
> other method in paper whether use the same four training dataset?
> is it fair?

Sorry but I am having trouble to understand your question. 
You may use Chinese or othere languages if you find it's easier.

**Comment by yc-zc** [comment]
Since no further question is asked, I'm closing it for now.
Please reopen it or create a new issue if you have further question.
