### ISSUE TITLE
对画面旋转的鲁棒性不强

### ISSUE THREAD

**Issue by colinlin1982** [STVIR/pysot#105]
使用手机拍摄视频跟踪人脸时发现模型对画面旋转的鲁棒性不强，具体表现：
场景：在视频中有两个人，其中A不动保持侧脸；B初始为正脸，并左右移动、前进、后退、转身等。B左右移动时有靠近A。
当视频画面未旋转时，模型可以很好的跟踪到B的人脸（人头）。
使用第三方工具将视频文件画面旋转90度后，B转身时模型有很大几率跟踪到A的人脸。

最后我试了siamrpn_r50_l234_dwxcorr_lt这个模型。在上述场景中，无论视频画面是否旋转，B转身之前和转身之后，帧率下降非常明显。转身之前每秒差不多有3帧，转身之后每秒不到一帧。而且也不能解决鲁棒性问题。

**Comment by lzx1413** [comment]
Are you a product manager?

**Comment by yc-zc** [comment]
在我们的测试当中并没有这个问题。
建议你通过额外的人脸追踪数据集进一步训练。
