### ISSUE TITLE
Other trackers testing

### ISSUE THREAD

**Issue by jongwon20000** [STVIR/pysot#107]

**Comment by jongwon20000** [comment]
The README said "PySOT includes implementations of the following visual tracking algorithms (DASiamRPN, SiamRPN++, SiamRPN, SiamFC, etc.", but I cannot find the way to test them. Actually, I am not even sure about the default algorithm of PySOT. 
Could you give me a hand for that? Thank you.

**Comment by yc-zc** [comment]
Could you please just take a look at the code.
