### ISSUE TITLE
Problem? when trained  on vid, det, coco and youtubebb, got my  EAO=0.164 in epoch 19

### ISSUE THREAD

**Issue by qiusenhui** [STVIR/pysot#108]
Can you tell me what problem? when trained siamrpn_r50_l234_dwxcorr_gpu on vid, det, coco and youtubebb, i only got  EAO=0.164 in epoch 19 in VOT2018. EAO=0.202 in epoch 14 in VOT2018.
i use siamrpn_r50_l234_dwxcorr_gpu to train, only modify row 136 in config.py  _C.DATASET.NAMES = ('VID', 'COCO', 'DET', 'YOUTUBEBB', 'MOT')  to _C.DATASET.NAMES = ('VID', 'COCO', 'DET', 'YOUTUBEBB')

**Comment by lb1100** [comment]
No, that shouldn't affect the results. Maybe you are using the old version youtube crops that we provided ? Try with the new uploaded version. The old version is not correct.

**Comment by chenbolinstudent** [comment]
@lb1100
Try with the new uploaded version. 
when you upload the new uploaded version of youtube_bb?
thanks

**Comment by qiusenhui** [comment]
@lb1100 Thank you for your rely. 
1、I downloaded youtube dataset depend on your command(wget https://research.google.com/youtube-bb/yt_bb_detection_train.csv.gz)， Is it wrong?
2、I just only use one GPU1080TI, It takes six days to train once. Is it can get the best result?（config：siamrpn_r50_l234_dwxcorr_gpu）

thanks

**Comment by lb1100** [comment]
I replied you just after uploading the new version. It's uploaded yesterday. So try the new version. Sorry for the inconvenience.

**Comment by chenbolinstudent** [comment]
@lb1100 
where is the new version? I cannot find it ,
thanks

**Comment by Manguotree** [comment]
Can you say the catalogue level of cropped YOUTUBE-BB in /training_dataset/yt_bb?

**Comment by liuyun19951104** [comment]
can you tell me how to train? I have some own video dataset and want to train in it. but i don't know how it works.

**Comment by qiusenhui** [comment]
@chenbolinstudent 
https://github.com/STVIR/pysot/blob/master/TRAIN.md
YOUTUBEBB (New link for cropped data, BaiduYun, extract code: 6dd5. NOTE: Data in old link is not correct. Please use cropped data in this new link.)
Please clik the BaiduYun

**Comment by qiusenhui** [comment]
@Manguotree my catalogue level is as follows:
pysot-master
..trainning_dataset
....yt_bb
......crop511  train.json
........train0000~train0099

**Comment by qiusenhui** [comment]
@liuyun19951104 
This project is very detailed. I refer to its steps completely.

**Comment by chenbolinstudent** [comment]
@qiusenhui
 thanks , and when use these dataset，whether you can get the EAO=0.414?
whether I should change other ?
(such as  describe in #34  :Hi， is it your convenient to supply a download link about your croped youtube dataset? bug)
The width and height in the train.json file is the original value. You need to calculate the resize factor to resize the width and height. Refer the dataset.py to get the correct size.

thanks!

**Comment by chenbolinstudent** [comment]
and the val dataset is not used in the code,right?

**Comment by qiusenhui** [comment]
@chenbolinstudent 
1. I am training now, the result will be publish.
2. youtube dataset do not need to modify, they have croped. link as above

**Comment by smile-fyl** [comment]
> @chenbolinstudent
> 
> 1. I am training now, the result will be publish.
> 2. youtube dataset do not need to modify, they have croped. link as above

I have trained with new youtube dataset,but EAO=0.360.

**Comment by chenbolinstudent** [comment]
what is the problem?
how much gpu you use?

**Comment by smile-fyl** [comment]
> what is the problem?
> how much gpu you use?
2 pieces of 2080TI

**Comment by ZekuiQin** [comment]
> > @chenbolinstudent
> > 
> > 1. I am training now, the result will be publish.
> > 2. youtube dataset do not need to modify, they have croped. link as above
> 
> I have trained with new youtube dataset,but EAO=0.360.

I got EAO=0.344 on VOT2018. Would it be convenient for you to leave a contact information?I would like to ask you some questions  in details.（my wechat: gbzm571240083）

**Comment by liuyun19951104** [comment]
I still have a question. I want to train in my own dataset. Should i must crop it as 511*511? My picture is 288*288, is there any  question?

**Comment by liuyun19951104** [comment]
another question. Is val set is essential for training process?I don't set it

**Comment by yc-zc** [comment]
Since no further question is asked, I'm closing it for now.
Please reopen it or create a new issue if you have further question.

**Comment by Jee-King** [comment]
@liuyun19951104   Hi, do you know how to train siamrpn++ with your own dataset now?
