### ISSUE TITLE
problem：Build extensions 

### ISSUE THREAD

**Issue by carmen520** [STVIR/pysot#110]
#### Build extensions
```
python setup.py build_ext --inplace
```
(pysot) dmu@dmu-308:~$ python setup.py build_ext --inplace
python3: can't open file 'setup.py': [Errno 2] No such file or directory

**Comment by lb1100** [comment]
Please refer to INSTALL.md and run this code in the directory of pysot repo.

**Comment by dcode-baranidharan** [comment]
@carmen520 am also facing the same issue, share how to resolve it
