### ISSUE TITLE
我是个初学者，想请教下为什么SiamRPN论文中的section3.1中第一个模拟实验（shift等于0）时存在很大的center bias？shfit是什么？能解释下对一张图像shift意味着什么吗？

### ISSUE THREAD

**Issue by FanOfJames** [STVIR/pysot#111]
我是个初学者，想请教下为什么section3.1中第一个模拟实验（shift等于0）时存在很大的center bias？shfit是什么？能解释下对一张图像shift意味着什么吗？

**Comment by FanOfJames** [comment]
上面的section3.2指的是论文（SiamRPN++: Evolution of Siamese Visual Tracking with Very Deep   Networks）中的section3.2。

**Comment by beihaifusang** [comment]
对应的是训练代码中 augmentation 那里面的 shift augmentation 那一步 
至于central bias 原因，是因为 0-padding引起的，导致网络认为受 0-padding 的 feature 都是对应没有目标的区域 （如果没有 shift 的话），于是网络就倾向于认为 中心的feature是对应有目标的 （因为中心的feature不会被0-padding影响，或收到的影响相对边缘的feature弱）

**Comment by yc-zc** [comment]
由于本issue没有得到更进一步的提问，我现在将其关闭。
如有新的问题，请重新打开它或者创建一个新的issue。
