### ISSUE TITLE
siamrpn++_OTB100 result is poor

### ISSUE THREAD

**Issue by chenbolinstudent** [STVIR/pysot#112]
loading OTB100: 100%|██████████████████████████████████████| 100/100 [00:01<00:00, 55.33it/s, Woman]
eval success: 100%|███████████████████████████████████████████████████| 1/1 [00:00<00:00,  1.73it/s]
eval precision: 100%|█████████████████████████████████████████████████| 1/1 [00:00<00:00,  3.04it/s]
-----------------------------------------------------
|Tracker name| Success | Norm Precision | Precision |
-----------------------------------------------------
|   model    |  0.696  |     0.000      |   0.905   |

why is poorer than the paper ?

**Comment by chenbolinstudent** [comment]
and vot2018_LT

|Tracker Name| Precision | Recall |  F1   |
-------------------------------------------
|   model    |   0.633   | 0.586  | 0.608 |

why is poorer than the paper too ?

**Comment by chenbolinstudent** [comment]
UAV123

-----------------------------------------------------
|Tracker name| Success | Norm Precision | Precision |
-----------------------------------------------------
|   model    |  0.610  |     0.000      |   0.803   |

why is poorer than the paper ?

**Comment by shallowtoil** [comment]
> UAV123
> 
> ## |Tracker name| Success | Norm Precision | Precision |
> | model | 0.610 | 0.000 | 0.803 |
> 
> why is poorer than the paper ?

Which config file did you use for testing on UAV123, OTB or VOT?

**Comment by xi-mao** [comment]
你训练SiameseRPN++ 在OTB100的结果是多少？

**Comment by dkgupta90** [comment]
Dear @chenbolinstudent : Did you figure out why the results on all datasets are poorer than those reported in the paper? I too am struggling with the issue, and any help would be much appreciated.

**Comment by yc-zc** [comment]
Since no further question is asked, I'm closing it for now.
Please reopen it or create a new issue if you have further question.
