### ISSUE TITLE
Question about pre-trained backbone

### ISSUE THREAD

**Issue by chris-mh-wu** [STVIR/pysot#113]
Imagenet-based pre-trained backbones expect input images normalized in the same way: 
1. The images have to be loaded in to a range of [0, 1]
2.  then normalized using mean = [0.485, 0.456, 0.406] and std = [0.229, 0.224, 0.225]

My questions:
1. Do we need to follow the same rule for object tracking ?
2. For SiamRPN++, is there any constraint for the pre-trained backbone selection ?

**Comment by zhu2014yi** [comment]
I thinks there is no need to normalization in tracking.I have try to normalized in tracking but I find it to be bad compared with the none normalized video.

**Comment by lb1100** [comment]
About normalization, we just simply follow siamfc. We haven't done experiments about normalization.  But I think that won't make big difference.
About backbone, there are some constraint, but it's for the alignment of input size 255. Such as downsample layer must be 3x3 like our modified resent.

**Comment by chris-mh-wu** [comment]
@lb1100 👍 
one more question: for the modified resnet, how to get the weight of modified downsample layer ? 
(e.g. re-train based on imagenet dataset ?)

**Comment by lb1100** [comment]
Our pertained models are trained on ImageNet from stretch. We didn't use public weights. So we haven't encountered this problem.

**Comment by chris-mh-wu** [comment]
Get it, thanks ~

**Comment by shallowtoil** [comment]
> I thinks there is no need to normalization in tracking.I have try to normalized in tracking but I find it to be bad compared with the none normalized video.

Could you plz share your results for comparison? How's the difference?
