### ISSUE TITLE
test the OTB100 VOT2018 VOT2018-LT UAV123 LASOT 

### ISSUE THREAD

**Issue by chenbolinstudent** [STVIR/pysot#114]
why when test the OTB100 VOT2018 VOT2018-LT UAV123 LASOT , config.yaml is different?
and what is the config.yaml  of UAV123 LASOT ?

and /siamrpn_r50_l234_dwxcorr_8gpu/config.yaml is suittable for OTB100 VOT2018 VOT2018-LT UAV123 LASOT ?or just one of it ?

**Comment by yc-zc** [comment]
Because we found such parameters will lead to better result.

**Comment by yc-zc** [comment]
Since no further question is asked, I'm closing it for now.
Please reopen it or create a new issue if you have further question.
