### ISSUE TITLE
testing_dataset

### ISSUE THREAD

**Issue by carmen520** [STVIR/pysot#118]
(pysot) dmu@dmu-308:  Ling/pysot-master$ cd experiments/siammask_r50_l3
(pysot) dmu@dmu-308:  Ling/pysot-master/experiments/siammask_r50_l3$ python -u ../../tools/test.py \
 --snapshot model.pth \ # model path
usage: test.py [-h] [--dataset DATASET] [--config CONFIG]
               [--snapshot SNAPSHOT] [--video VIDEO] [--vis]

 

> test.py:` error: unrecognized arguments:  # model path

(pysot) dmu@dmu-308:  Ling/pysot-master/experiments/siammask_r50_l3$ --dataset VOT2019 bash: complete: --: 无效选项
complete: 用法: complete [-abcdefgjksuv] [-pr] [-DE] [-o 选项] [-A 动作] [-G 全局模式] [-W 词语列表]  [-F 函数] [-C 命令] [-X 过滤模式] [-P 前缀] [-S 后缀] [名称 ...]
\ # dataset name

> --dataset：未找到命令

(pysot) dmu@dmu-308:~/Ling/pysot-master/experiments/siammask_r50_l3$ --config config.yamlbash: complete: --: 无效选项
complete: 用法: complete [-abcdefgjksuv] [-pr] [-DE] [-o 选项] [-A 动作] [-G 全局模式] [-W 词语列表]  [-F 函数] [-C 命令] [-X 过滤模式] [-P 前缀] [-S 后缀] [名称 ...]
  config file

> --config：未找到命令

what‘s the problem?????/

**Comment by lb1100** [comment]
remove all comments after `\`. these three lines contains only a single command, don't split it.
