### ISSUE TITLE
目前只提供了SiamRPN++和SiamMask的模型嘛？

### ISSUE THREAD

**Issue by TeslaHua** [STVIR/pysot#12]
从评估的baselines看，pysot是不是只提供了SiamRPN++和SiamMask加上几种backbone的模型，其他三种DaSiamRPN、SiamRPN、SiamFC没有提供，没找到可下载的链接。

**Comment by lb1100** [comment]
Yes, but alexnet version siamrpn++ is a stronger baseline than SiamRPN, DaSiamRPN without compromising speed.

**Comment by TeslaHua** [comment]
@lb1100 谢谢大佬。训练的code有望公布一下嘛，期待。

**Comment by feixiangdekaka** [comment]
waiting for train code !

**Comment by NWPUWRY** [comment]
你好，怎么做SiamMask的demo, 将config中的mask改为true之后应该怎么办？
