### ISSUE TITLE
Can't reproduce report results on VOT2018

### ISSUE THREAD

**Issue by ZekuiQin** [STVIR/pysot#124]
I used your code to train SiamRPN++ and tested the model on VOT2018, but the EAO is only 0.344, which is much lower than your report results(0.415). The code and config file are totally same with yours, training datasets include VID,YTB(from your new link),COCO,DET.
![image](https://user-images.githubusercontent.com/40821171/61680318-aab25380-ad3b-11e9-963b-97a7efe81f66.png)

By the way, can you please provide other epoch model's benchmark results on VOT2018, such as epoch10~epoch20? I am confused whether most of epoch's EAO is high(greater than 0.4) or  0.415 is only a random result.

Thanks!

**Comment by ZekuiQin** [comment]
I got EAO=0.374 after hp search.

**Comment by charlesyann** [comment]
same question, hope to get some info

**Comment by yc-zc** [comment]
Since no further question is asked, I'm closing it for now.
Please reopen it or create a new issue if you have further question.

**Comment by yc-zc** [comment]
https://github.com/STVIR/pysot/issues/94
