### ISSUE TITLE
想问一下，这个code可以训练siammask么？还是只能训练siamrpn（train.md有写）？和王强老师里的siammask有什么不同？

### ISSUE THREAD

**Issue by gyftsy** [STVIR/pysot#126]

**Comment by donghang941114** [comment]
我也没有训练成功siammask，你训练出来了吗

**Comment by gyftsy** [comment]
没有 我没有用pysot来训练 用单独的siammask训练的


发自我的iPhone

------------------ 原始邮件 ------------------
发件人: 董航 <notifications@github.com&gt;
发送时间: 2019年12月7日 22:55
收件人: STVIR/pysot <pysot@noreply.github.com&gt;
抄送: Gary <835781085@qq.com&gt;, Author <author@noreply.github.com&gt;
主题: 回复：[STVIR/pysot] 想问一下，这个code可以训练siammask么？还是只能训练siamrpn（train.md有写）？和王强老师里的siammask有什么不同？ (#126)

**Comment by donghang941114** [comment]
我们能加一下微信吗，交流一下


发自我的iPhone

------------------ 原始邮件 ------------------
发件人: Gary <notifications@github.com&gt;
发送时间: 2019年12月7日 22:56
收件人: STVIR/pysot <pysot@noreply.github.com&gt;
抄送: 董航 <1746314075@qq.com&gt;, Comment <comment@noreply.github.com&gt;
主题: 回复：[STVIR/pysot] 想问一下，这个code可以训练siammask么？还是只能训练siamrpn（train.md有写）？和王强老师里的siammask有什么不同？ (#126)



没有 我没有用pysot来训练 用单独的siammask训练的 
 
 
 发自我的iPhone 
 
 ------------------ 原始邮件 ------------------ 
 发件人: 董航 <notifications@github.com&amp;gt; 
 发送时间: 2019年12月7日 22:55 
 收件人: STVIR/pysot <pysot@noreply.github.com&amp;gt; 
 抄送: Gary <835781085@qq.com&amp;gt;, Author <author@noreply.github.com&amp;gt; 
 主题: 回复：[STVIR/pysot] 想问一下，这个code可以训练siammask么？还是只能训练siamrpn（train.md有写）？和王强老师里的siammask有什么不同？ (#126)

**Comment by donghang941114** [comment]
你好，我训练siammask遇到了一些问题，可以交流一下吗


发自我的iPhone

------------------ 原始邮件 ------------------
发件人: Gary <notifications@github.com&gt;
发送时间: 2019年12月7日 22:56
收件人: STVIR/pysot <pysot@noreply.github.com&gt;
抄送: 董航 <1746314075@qq.com&gt;, Comment <comment@noreply.github.com&gt;
主题: 回复：[STVIR/pysot] 想问一下，这个code可以训练siammask么？还是只能训练siamrpn（train.md有写）？和王强老师里的siammask有什么不同？ (#126)



没有 我没有用pysot来训练 用单独的siammask训练的 
 
 
 发自我的iPhone 
 
 ------------------ 原始邮件 ------------------ 
 发件人: 董航 <notifications@github.com&amp;gt; 
 发送时间: 2019年12月7日 22:55 
 收件人: STVIR/pysot <pysot@noreply.github.com&amp;gt; 
 抄送: Gary <835781085@qq.com&amp;gt;, Author <author@noreply.github.com&amp;gt; 
 主题: 回复：[STVIR/pysot] 想问一下，这个code可以训练siammask么？还是只能训练siamrpn（train.md有写）？和王强老师里的siammask有什么不同？ (#126)

**Comment by yc-zc** [comment]
> _No description provided._

可以

**Comment by yc-zc** [comment]
由于本issue没有得到更进一步的提问，我现在将其关闭。
如有新的问题，请重新打开它或者创建一个新的issue。
