### ISSUE TITLE
How to print shapes from each layer of the network

### ISSUE THREAD

**Issue by Programmerwyl** [STVIR/pysot#128]
I want to use torchsummary to print the shape of the network.
But because the network is two inputs, it keeps failing.

How to set shape in the demo you provided
def main():
    # load config
    cfg.merge_from_file(args.config)
    cfg.CUDA = torch.cuda.is_available()
    device = torch.device('cuda' if cfg.CUDA else 'cpu')

    # create model
    model = ModelBuilder()

    # load model
    model.load_state_dict(torch.load(args.snapshot,
        map_location=lambda storage, loc: storage.cpu()))
    model.eval().to(device)

    
    **summary(model,(shape))**
    
    # build tracker
    tracker = build_tracker(model)

    print('model',model)
    first_frame = True
    if args.video_name:
        video_name = args.video_name.split('/')[-1].split('.')[0]
    else:
        video_name = 'webcam'
    cv2.namedWindow(video_name, cv2.WND_PROP_FULLSCREEN)

Thanks a lot

**Comment by yc-zc** [comment]
I think what you wanted to do is to open up this issue at the repo of torchsummary. 
Since this issue is not relevant, I'm closing it for now.
