### ISSUE TITLE
anchor question

### ISSUE THREAD

**Issue by Programmerwyl** [STVIR/pysot#129]
1.I want to know whether anchor is generated based on the size of the feature diagram or the original diagram?
2.There is only one anchor scale, which can do things because the shape of the object tracked will not change greatly，However, does this kind of sample limit the size of tracking objects? For too large and too small objects, the effect is relatively poor.
Thanks

**Comment by yc-zc** [comment]
1. feature diagram
2. no. it will perform well on too small objects, and probably better on too large objects. it only limits the ability to track an object which changes from too small to too large in a few frames, which isn't something we focus.

**Comment by Programmerwyl** [comment]
Hi yc-zc:
1.Thank you very much for your reply.
2.Does this mean that the anchors change according to the size of the object to be tracked.
That means whether the object being tracked is too large or too small,the anchor will adapt itself?
that is great.
thank you very much

**Comment by yc-zc** [comment]
> Hi yc-zc:
> 1.Thank you very much for your reply.
> 2.Does this mean that the anchors change according to the size of the object to be tracked.
> That means whether the object being tracked is too large or too small,the anchor will adapt itself?
> that is great.
> thank you very much

No worries, glad I can help. 
The scale of anchors is fixed, which means the size of anchors will not change. However, the scale of proposals will change in the regression branch of the rpn, where the w and h represents the change in x and y direction.

**Comment by Programmerwyl** [comment]
Hi yc_zc:
what does 'the scale of proposals' refer to?
it is delta？
···
  def _convert_bbox(self, delta, anchor):
        delta = delta.permute(1, 2, 3, 0).contiguous().view(4, -1)
        delta = delta.data.cpu().numpy()

        delta[0, :] = delta[0, :] * anchor[:, 2] + anchor[:, 0]
        delta[1, :] = delta[1, :] * anchor[:, 3] + anchor[:, 1]
        delta[2, :] = np.exp(delta[2, :]) * anchor[:, 2]
        delta[3, :] = np.exp(delta[3, :]) * anchor[:, 3]
        return delta

···
looking forward to your reply,Thank you very much.

**Comment by yc-zc** [comment]
> Hi yc_zc:
> what does 'the scale of proposals' refer to?
> it is delta？
> 
> ```
>   def _convert_bbox(self, delta, anchor):
>         delta = delta.permute(1, 2, 3, 0).contiguous().view(4, -1)
>         delta = delta.data.cpu().numpy()
>         delta[0, :] = delta[0, :] * anchor[:, 2] + anchor[:, 0]
>         delta[1, :] = delta[1, :] * anchor[:, 3] + anchor[:, 1]
>         delta[2, :] = np.exp(delta[2, :]) * anchor[:, 2]
>         delta[3, :] = np.exp(delta[3, :]) * anchor[:, 3]
>         return delta
> ```
> 
> looking forward to your reply,Thank you very much.

Happy new year!
The RPN was proposed by Kaiming He et al. in their paper of faster rcnn. As a detection framework, their network needs to detect object in different size, so anchors are generated in different scales and shapes. However, since we assume the object won't change much in size, the scale of anchor is fixed, that is, you cannot find code of scale in this repo.

**Comment by Programmerwyl** [comment]
Happy new year!
you are so nice!
I wonder if I can make sense of the fact that the object being detected has to be labeled first,so the scaling can be determined by the size of the object being detected.Since the size of the detected object does not change much in the video,scaling once is sufficient.
thank you very much!

**Comment by yc-zc** [comment]
> Happy new year!
> you are so nice!
> I wonder if I can make sense of the fact that the object being detected has to be labeled first,so the scaling can be determined by the size of the object being detected.Since the size of the detected object does not change much in the video,scaling once is sufficient.
> thank you very much!

Happy new year!
Thank you
Yes, for SOT task, we assume the ground truth of template will be provided at the first frame. I suggest you read the paper more carefully, it has detailed explanation on how to do the regressoin of the bounding box.

**Comment by Programmerwyl** [comment]
I will read the paper more carefully.
Thank you very much!

**Comment by qinc** [comment]
Please correct me if I'm wrong for the following observations:

Based on @zyc-ai 's description, and the paper, anchors should be generated based on the size of template bounding box, but in the code, wherever Anchors is generated it was always through code like this:
        self.anchors = Anchors(cfg.ANCHOR.STRIDE,
                               cfg.ANCHOR.RATIOS,
                               cfg.ANCHOR.SCALES)
which will give anchors with constant size (64x64, before applying ratios). For generating positive classified anchors, one anchor box need to have >0.6 IOU with the ground truth, that means if the ground truth bounding box is much bigger or smaller than 64x64, no anchor will be considered positive during training, and that object won't be detected during tracking at all.

A workaround is to defined multiple anchor scales, but the paper claims only one scale is needed, which is very confusing. This will only happen if all the tracking objects are around the same 64x64 size in the search image.

Am I missing something, please point out if there is code somewhere I've missed, thanks~!
