### ISSUE TITLE
Bug report.

### ISSUE THREAD

**Issue by iminfine** [STVIR/pysot#132]
In the 37th line of hp_search.py, the setting of range seems wrong.
parser.add_argument('--search-region', default='255,256,8', type=parse_range_int)

Why not consider to use the GA or TPE to search hp? Calculating all possibilities are time-consuming.
Besides,  the hp_search.py file seems incompleted. It is a separate file, not called by any other files, only writes prediction boxes of all parameter groups without evaluating them and determines the best hp.

**Comment by lb1100** [comment]
What's wrong with `search-region`? 

About GA or TPE, we haven't tried this yet. We are not sure this will work. Parameters are random from our observation.
