### ISSUE TITLE
EAO=0.415,vot2018

### ISSUE THREAD

**Issue by mengmeng18** [STVIR/pysot#133]
can anyone achieve EAO=0.415 in new four datasets? can you share your experience?

**Comment by charlesyann** [comment]
I cannot get it either, 0.35 at most.

**Comment by chenbolinstudent** [comment]
how much GPU and batch_size you use?

**Comment by yangkai12** [comment]
Can anyone get this result? I have the same issues.

**Comment by Ling-wei** [comment]
I got 0.370 (VOT2018) on Epoch15 (using four datasets)

**Comment by xi-mao** [comment]
Same question

**Comment by kongbia** [comment]
I got  EAO 0.374(VOT2018) on epoch 17 with 4 gpu ,and had fine-tuned the result with hp_search.py.Should I change the batch size to train with only 4gpus?

**Comment by bcy97** [comment]
I got the same result(0.384 after hp_search) with you. I used four dataset(youtube bb is downloaded from   author's link). Can anyone get 0.414?

**Comment by yangkai12** [comment]
I get the EAO=0.417 when the batchsize=48 on a single GPU

**Comment by yc-zc** [comment]
Since no further question is asked, I'm closing it for now.
Please reopen it or create a new issue if you have further question.

**Comment by yc-zc** [comment]
https://github.com/STVIR/pysot/issues/94
