### ISSUE TITLE
Why is the template branch and the search branch the same path to input images

### ISSUE THREAD

**Issue by Programmerwyl** [STVIR/pysot#134]
log:
template /media/wyl/01937159-8963-47f6-b239-efe7b18f2e8b/wyl/data/project/data/crop255/val2017/000000058029/000000.00.x.jpg
search /media/wyl/01937159-8963-47f6-b239-efe7b18f2e8b/wyl/data/project/data/crop255/val2017/000000058029/000000.00.x.jpg

    def get_image_anno(self, video, track, frame):
        frame = "{:06d}".format(frame)

        image_path = os.path.join(self.root, video.replace('\\','/'),
                                  self.path_format.format(frame, track, 'x'))
        image_anno = self.labels[video][track][frame]
        return image_path, image_anno

According to log and get_image_anno function ,I find  that the path to the template branch and the search branch for the input image is same
They are both x,not use z

**Comment by lb1100** [comment]
`z` is included in `x`. Just cropping center part will get `z`.
