### ISSUE TITLE
without use val dataset?

### ISSUE THREAD

**Issue by chenbolinstudent** [STVIR/pysot#138]
without use val dataset?
how about add it?

**Comment by lb1100** [comment]
You can add it if you like. Similar to training. However, loss or accuracy of paired images can't represent tracking performance since tracking is a sequential problem.

**Comment by yc-zc** [comment]
Since no further question is asked, I'm closing it for now.
Please reopen it or create a new issue if you have further question.

**Comment by haishibei** [comment]
> You can add it if you like. Similar to training. However, loss or accuracy of paired images can't represent tracking performance since tracking is a sequential problem.

Excuse me , Whether what you said means that the process of training doesn't make use of the vid.json  in the dataset VID?
