### ISSUE TITLE
If the color is set to 1.0 in the data augmentation, the image will be white after the transformation

### ISSUE THREAD

**Issue by Programmerwyl** [STVIR/pysot#139]
1.In config.yaml , the default COLOR is set to 1.0.
2. In augmentation/call. the image will be white after the transformation

![QQ截图20190730102315](https://user-images.githubusercontent.com/22095854/62095797-148aaa00-b2b4-11e9-85bf-ca62e3c710d2.png)

**Comment by adrift00** [comment]
Do you use the cv2.imshow() to visual the image? If this, maybe it because the cv2.imshow() can't show the image which dtype is float, you should change the type to np.uint8.

**Comment by Programmerwyl** [comment]
@adrift00 Thank you very much for your reply.
you are right, I did use opencv to visual.
I ignored that opencv cannot display arrays of float data types.
thanks.
