### ISSUE TITLE
关于siammasl的mask分支

### ISSUE THREAD

**Issue by kongbia** [STVIR/pysot#142]
siammask构建模型时mask_head和refine_head分别由mask.py的MaskCorr和Refine类生成，在训练过程中只使用了mask_head且似乎并未完善，而测试过程中使用的是refine_head，想问一下这两者应该使用哪一个。

**Comment by yulinhuyang** [comment]
同样的疑问啊。

**Comment by yulinhuyang** [comment]
求大佬解答
