### ISSUE TITLE
f复现代码后，帧率与文章中写的差距太大了，我的估计就10帧左右。有大佬遇到过类似的问题么？求解疑

### ISSUE THREAD

**Issue by baigang666** [STVIR/pysot#143]

**Comment by charlesyann** [comment]
trainning代码到现在还没有复现出作者paper的精度，你是怎么实现的呢？求指导

**Comment by MARMOTatZJU** [comment]
@charlesyann in my opinion, reproduction would not be possible unless you get the official pre-trained backbone parameters. To my observation, pre-trained backbone could be really tricky w.r.t. final benchmark score.

**Comment by yc-zc** [comment]
> _No description provided._

你的机器配置是？

**Comment by yc-zc** [comment]
> trainning代码到现在还没有复现出作者paper的精度，你是怎么实现的呢？求指导

新的问题请开新的issue

**Comment by yc-zc** [comment]
由于本issue没有得到更进一步的提问，我现在将其关闭。
如有新的问题，请重新打开它或者创建一个新的issue。
