### ISSUE TITLE
[pseudo PR] problem with mobile net without multi-layer

### ISSUE THREAD

**Issue by MARMOTatZJU** [STVIR/pysot#148]
In order to train mobilenet with normal RPN instead of MultiRPN, I had to modify _pysot/models/backbone/mobile_v2.py_ starting from line 130 as follows:
```
        if isinstance(self.used_layers, int):
            out = outputs[self.used_layers]
        else:
            out = [outputs[i] for i in self.used_layers]
```
This issue is due to the fact that in case of single layer settings, mobile_v2.py always outputs list object (list of a single tensor), while normal RPN expects a tensor(without list wrapping) in case of single layer. 
I couldn't have got any other better solution other than this (though modifying code in core package seems not recommanded). 
Would you mind pay a little attention to this issue and fix this incompatibility problem for the sake of researchers following your work ? Thx a lot.

**Comment by StrangerZhang** [comment]
Fixed! Enjoy!
