### ISSUE TITLE
Question about SiamMask model

### ISSUE THREAD

**Issue by JWarlock** [STVIR/pysot#15]
Hi, there!
    I'm trying to reproduce the result of SiamMask in PySOT Model Zoo -- 0.423/0.615/0.248 (EAO/A/R) @VOT2018. However, using the released model I only get 0.407/0.598/0.243 (EAO/A/R) @VOT2018. Also, the average speed is about 30 FPS, which is much lower than 56FPS.
    I have tried to set __C.MASK.MASK and __C.MASK.REFINE to True，but the result does not change. 
    I wonder if I was using the wrong command/params ? Is there anythin I should pay attention to other than the Quick Start tutorial and config.py？
    Thanks a lot!

**Comment by CXSunshine** [comment]
where can I get the code of siameseFC？Thanks~

**Comment by Dtappledoghuati** [comment]
您好，请问有成功跑通过siammask的训练吗，我总是遇到问题，可以指点一下吗，或者您有正确的config文件吗
