### ISSUE TITLE
libtorch如何加载pysot训练的.pth模型文件？

### ISSUE THREAD

**Issue by itfish** [STVIR/pysot#150]

**Comment by lb1100** [comment]
Duplicate of #146. Please watch this issue. If the problem solved, we'll update here.

**Comment by itfish** [comment]
my problem is not solved. could you give me the solution about how to use pysot's .pth model with c++ language?

**Comment by lb1100** [comment]
Sorry, what I meant is we will update this on #146. These two issues are duplicated.

**Comment by itfish** [comment]
ok,can you help me to solve this problem?

**Comment by mqingkui** [comment]
@itfish have you solved pth->pt problem？
