### ISSUE TITLE
Question about negative pair training

### ISSUE THREAD

**Issue by chris-mh-wu** [STVIR/pysot#152]
Would like to know the benefit of random negative example selection (instead of selecting all 7x7x5 anchors as negative example):

![image](https://user-images.githubusercontent.com/26220205/62746431-173e8980-ba82-11e9-978b-4404040f3b07.png)

**Comment by lb1100** [comment]
Positive samples in positive pairs are less than negative ones. If we introduced too much negative samples, model may overfit to negative examples. However, I don't think it will make a big difference. You can try to use all 7x7x5. We didn't do experiments on this.

**Comment by chris-mh-wu** [comment]
Thanks for your reply
