### ISSUE TITLE
为什么没有人问ubuntu下python3.7没有对应的opencv-python，网上帖子解决办法都是针对win的

### ISSUE THREAD

**Issue by JensenHJS** [STVIR/pysot#153]
为什么没有人问ubuntu下python3.7没有对应的opencv-python，网上帖子解决办法都是针对win的

**Comment by lb1100** [comment]
`pip install opencv-python`. 
Please refer to (INSTALL.md)[https://github.com/STVIR/pysot/blob/master/INSTALL.md]
