### ISSUE TITLE
如何接着e10 训练？

### ISSUE THREAD

**Issue by chenbolinstudent** [STVIR/pysot#154]
如何接着e10 训练？

**Comment by yc-zc** [comment]
我无法理解你的问题。
请提供更多的细节。

**Comment by yc-zc** [comment]
我无法理解你的问题。
请提供更多的细节。

**Comment by yc-zc** [comment]
由于本issue没有得到更进一步的提问，我现在将其关闭。
如有新的问题，请重新打开它或者创建一个新的issue。
