### ISSUE TITLE
Discussion of design of penalty

### ISSUE THREAD

**Issue by beihaifusang** [STVIR/pysot#158]
First, thank you for open sourcing such a great repo.

While understanding the code, I found it's a little bit tricky to understand various penalties used in selecting the output bbox from tracker. 
E.g., in siamron_tracker.py, `SiamRPNTracker.track(self, img)`, we have

![image](https://user-images.githubusercontent.com/17057383/63406239-e19f8600-c41b-11e9-8d3a-ebc442ab0ad4.png)

More specifically, may I ask why we choose to use `penalty = np.exp(-(r_c * s_c - 1) * cfg.TRACK.PENALTY_K)` as our final penalty? Are those choice discussed in any paper that I may not be aware of? 
(or probably buried in other great content of some siam-tracker paper?)
Besides, is there any interpretation for choosing to calculate penalty as in the code?

Thank you for help.

**Comment by lb1100** [comment]
Yeah, it's tricky. We mention it in the first paper(SiamRPN). We penalize scores whose scale or aspect ratio varies too much compared to the previous. 
But unfortunately, it is a hyper-parameter. Currently we only perform hyper-parameter searching on it. We haven't found a way to calculate it. The same as window_influence.

**Comment by beihaifusang** [comment]
Thank you for your explanation!
