### ISSUE TITLE
请教

### ISSUE THREAD

**Issue by yeqingQian** [STVIR/pysot#16]
importError: cannot import name 'region'，总是出现该错误，使用pip install region也显示安装成功了，我想咨询下这个是什么原因

**Comment by StrangerZhang** [comment]
In project root, 
`
python setup.py build_ext --inplace
`
should solve your problem

**Comment by chenbolinstudent** [comment]
那还需要 pip install region 吗？

**Comment by lb1100** [comment]
`region` is built by `python setup.py build_ext --inplace`. It's in the package. No need to `pip install`.

**Comment by hy1hao** [comment]
> `region` is built by `python setup.py build_ext --inplace`. It's in the package. No need to `pip install`.

sorry to bother you after few years, when i python setup.py, follows the information:

cimport c_region
        ^
------------------------------------------------------------

toolkit\utils\region.pyx:11:8: 'c_region.pxd' not found


do u know the reason?thanks

**Comment by wyzhang233** [comment]
I have alredy built 'python setup.py build_ext --inplace',and have .pyd,but still cannot import region.The __init__.py show 'unresolved reference'region''
