### ISSUE TITLE
The usage of cpu memory  rise all the time.

### ISSUE THREAD

**Issue by xi-mao** [STVIR/pysot#161]
when i trained code with docker , i find the  usage of cpu memory is rising all the time until out of memory。 but if i don't use docker ，it work well。 I don't know why。 Anyone else find the phenomenon？ 
besides，the config.py set NUM_WORK=1,i think it is too small ,why don't use a larger number?

**Comment by lb1100** [comment]
I'm sorry that I'm not familiar with docker. About `num_workers`, it's 1 for each thread/gpu. We believe that's enough. But you can try with more workers.

**Comment by xi-mao** [comment]
@lb1100  besides,i have a question that, the rpn in the code is DaSiameserpn or SiameseRPN?

**Comment by lb1100** [comment]
It's similar. DaSiamRPN and SiamRPN only differ during training.

**Comment by yc-zc** [comment]
> when i trained code with docker , i find the usage of cpu memory is rising all the time until out of memory。 but if i don't use docker ，it work well。 I don't know why。 Anyone else find the phenomenon？
> besides，the config.py set NUM_WORK=1,i think it is too small ,why don't use a larger number?

我觉得这更像是一个docker的问题。
你的docker用的是nvidia-docker2？具体什么版本？dockerfile能提供一下吗？

**Comment by yc-zc** [comment]
Since no further question is asked, I'm closing it for now.
Please reopen it or create a new issue if you have further question.
