### ISSUE TITLE
想请教一下：COCO2017数据集预处理的图像仿射变换后和train2017.json的truth box坐标的关系？ 急，在线等~

### ISSUE THREAD

**Issue by cunjif** [STVIR/pysot#163]
如题，请问经过par_crop.py 和 gen_json.py文件处理后的COCO2017数据集输出的crop511 和 train2017.json文件中truth box坐标的关系。手动按坐标框貌似在训练图片上框不到东西，逗逼了~
      另外， 请问`crop_like_SiamFC`函数中，下面两行代码的处理是什么意思啊？

> wc_z = target_size[1] + context_amount * sum(target_size)
> hc_z = target_size[0] + context_amount * sum(target_size)

        万分感谢。

**Comment by Joker1994k** [comment]
https://github.com/STVIR/pysot/blob/15ba130ff95dfb1bb8fc4d435582f484b4d1fdfc/pysot/datasets/dataset.py#L213

这个函数吧

**Comment by cunjif** [comment]
>
https://github.com/STVIR/pysot/blob/15ba130ff95dfb1bb8fc4d435582f484b4d1fdfc/training_dataset/coco/par_crop.py#L48
>
我想问这个来着😂...
这两个处理是对应的嘛？
为什么要这样处理？

**Comment by cunjif** [comment]
@Joker1994k

**Comment by lb1100** [comment]
Details in [SiamFC](https://www.robots.ox.ac.uk/~luca/siamese-fc.html), which is our baseline. We didn't change the crop function.

**Comment by yc-zc** [comment]
由于本issue没有得到更进一步的提问，我现在将其关闭。
如有新的问题，请重新打开它或者创建一个新的issue。

**Comment by buaacarzp** [comment]
> ```
>   如题，请问经过par_crop.py 和 gen_json.py文件处理后的COCO2017数据集输出的crop511 和 train2017.json文件中truth box坐标的关系。手动按坐标框貌似在训练图片上框不到东西，逗逼了~
>   另外， 请问`crop_like_SiamFC`函数中，下面两行代码的处理是什么意思啊？
> ```
> 
> > wc_z = target_size[1] + context_amount * sum(target_size)
> > hc_z = target_size[0] + context_amount * sum(target_size)
> 
> ```
>     万分感谢。
> ```
在吗？我也想问这个
```
 wc_z = w + context_amount * (w+h)
 hc_z = h + context_amount * (w+h)
```
既然已经crop成511了，bbox的坐标肯定也跟随resize到511的尺寸下了，为什么这里还要对Bbox的宽和高进行padding？
