### ISSUE TITLE
ImportError: No module named pysot.core.config

### ISSUE THREAD

**Issue by creat2012** [STVIR/pysot#165]
import pysot 没有问题。
为什么会出现这个问题？

**Comment by yc-zc** [comment]
你的pysot版本是？

**Comment by chun-chun123** [comment]
可以把pysot文件夹放在所用Python目录下

**Comment by yc-zc** [comment]
由于本issue没有得到更进一步的提问，我现在将其关闭。
如有新的问题，请重新打开它或者创建一个新的issue。
