### ISSUE TITLE
cannot achieve SiameseRPN ‘ performance on OTB2015~

### ISSUE THREAD

**Issue by xi-mao** [STVIR/pysot#166]
I trained SiameseRPN with ytbb and imagenet according to the paper。but i only got  best auc 0.613 on OTB2015. the paper report result is 0.637.  I don't know  why 。 is there something  differences in the code？  anyone achieve the results？

**Comment by dkgupta90** [comment]
Hi @xi-mao Did you figure out the issue? I am not able to generate numbers reported in the papers for SiamRPN and SiamRPN++.

**Comment by xi-mao** [comment]
@dkgupta90   No, i haven't reproduced  the results. it's too stochastic.
