### ISSUE TITLE
problem about modify the EXEMPLAR_SIZE？

### ISSUE THREAD

**Issue by liuyun19951104** [STVIR/pysot#167]
I try to train the model in my own dataset. And I have change the Base Size and Exemplar Size. however it is strange that the loc_loss is 0 through the all train process. Why is it?

**Comment by lb1100** [comment]
Maybe there is no positive examples (No anchor whose iou with gt > threshold). I think there is something wrong  about your image size and anchor setting.

**Comment by liuyun19951104** [comment]
@lb1100 Thanks. Your answer is ok. I am puzzled now. I have tried to change some parameter such as EXEMPLAR_SIZE, BASE_SIZE, and ANCHOR SCALES. However, all these lead the decline of the result. Do you know why? or have some suggestions?

**Comment by yc-zc** [comment]
Since no further question is asked, I'm closing it for now.
Please reopen it or create a new issue if you have further question.
