### ISSUE TITLE
print value of layers but it‘s not the same everytime

### ISSUE THREAD

**Issue by JensenHJS** [STVIR/pysot#170]
I download your model that have trained.   I use test data to test and test commands in the terminal. And I try to print values of  Alexnet layers,such as the value of one convolution. I find the output is not the same each time. The model.pth is not changed and test data is not cahnged. Why the specific values of  a layer(such as convolution layer) is not the same? I know that the vales of each layers is determined by the trained model.pth

**Comment by lb1100** [comment]
I suggest you check your code. The inference code is deterministic.

**Comment by JensenHJS** [comment]
I try to rewrite the  code in alexnet.py：
def forward(self, x):
      x = self.layer1(x)
      for param in self.layer1[0].named_parameters():# layer1[0] is a conv layer of layer1
          print(param) # it will print two tensors,one is weight another is bias
      x = self.layer2(x)
      x = self.layer3(x)
      x = self.layer4(x)
      x = self.layer5(x)
      return x
#after print(param) ,there will be two tensors.the tensor of weight is too large,but the second tensor is only 96 numbers. It is not the same after I use test command to print

**Comment by yc-zc** [comment]
> I try to rewrite the code in alexnet.py：
> def forward(self, x):
> x = self.layer1(x)
> for param in self.layer1[0].named_parameters():# layer1[0] is a conv layer of layer1
> print(param) # it will print two tensors,one is weight another is bias
> x = self.layer2(x)
> x = self.layer3(x)
> x = self.layer4(x)
> x = self.layer5(x)
> return x
> #after print(param) ,there will be two tensors.the tensor of weight is too large,but the second tensor is only 96 numbers. It is not the same after I use test command to print

Sorry but I'm having trouble understanding your question. 
You may use Chinese or other languages you find more comfortable.

**Comment by yc-zc** [comment]
Since no further question is asked, I'm closing it for now.
Please reopen it or create a new issue if you have further question.
