### ISSUE TITLE
Question about the failure to run the demo (KeyError: 'Non-existent config key: BACKBONE.LAYERS')

### ISSUE THREAD

**Issue by winer1997** [STVIR/pysot#173]
（下面有中文版）
Such as the title，when I want to run the "tools/demo.py" often return such errors

`Traceback (most recent call last):
  File "tools/demo.py", line 109, in <module>
    main()
  File "tools/demo.py", line 60, in main
    cfg.merge_from_file(args.config)
  File "/home/winer/.conda/envs/pysot/lib/python3.7/site-packages/yacs/config.py", line 213, in merge_from_file
    self.merge_from_other_cfg(cfg)
  File "/home/winer/.conda/envs/pysot/lib/python3.7/site-packages/yacs/config.py", line 217, in merge_from_other_cfg
    _merge_a_into_b(cfg_other, self, self, [])
  File "/home/winer/.conda/envs/pysot/lib/python3.7/site-packages/yacs/config.py", line 460, in _merge_a_into_b
    _merge_a_into_b(v, b[k], root, key_list + [k])
  File "/home/winer/.conda/envs/pysot/lib/python3.7/site-packages/yacs/config.py", line 473, in _merge_a_into_b
    raise KeyError("Non-existent config key: {}".format(full_key))
KeyError: 'Non-existent config key: BACKBONE.LAYERS'`

I have downloaded the model and put it in the corresponding directory. And also tried running in python 3.6 and python 3.7 as well as Ubuntu 16 and Ubuntu 18, but all failed. Can you help me solve this problem? 
Oh, since I only have one computer at the moment, so I am running the code in the VM. There is no way to provide a separate GPU for it. I don't know if this affects the code.

Thank you so much!

-----------------------------------------------------------------

换回中文再写一遍，毕竟英语水平仍有待提升....

如题，每次在运行demo.py的代码时候都会报这个错
`KeyError: 'Non-existent config key: BACKBONE.LAYERS'`
已经按照说明里面配置好了环境，要下载的model也都下载过了但是还是不行。也在python36/37还有Ubuntu16/18全都试验过了，没一个能跑的，每次都是这么一个错误，其他地方也没找到解决方法。这个代码我是在VM里面跑的所以没办法给独立显卡，但是我看上面好像还用了CUDA，不知道有没有影响？

如果有人能解决这个问题还请指点，谢谢！

**Comment by MaxLin86** [comment]
我觉得你可以检查一下static_dict里的key值，是不是多了或者少了哪些部分

**Comment by winer1997** [comment]
> 我觉得你可以检查一下static_dict里的key值，是不是多了或者少了哪些部分

可以问一下这个值能在哪里查到么？
之前一直在做硬件那边，python和CV方面刚接触一个月，有很多地方都还不清楚，谢谢了

**Comment by MaxLin86** [comment]
在模型读取之后打个断点

**Comment by winer1997** [comment]
> 在模型读取之后打个断点

好的明白了，我先去调试一下试试，谢谢

**Comment by bsb6666** [comment]
请问解决问题了吗？

**Comment by winer1997** [comment]
> 不能用百度云下载的config.yaml，要用程序自带的。
> 替换experiments的模型时要注意。

谢谢！也是刚刚发现问题所在，打算上来加个标注的时候看到了你的回复。这个方法确实有效，好像作者更新了项目里的config.yaml，但是百度云的没更新，用程序里的就好了。
再次感谢！
