### ISSUE TITLE
consultation

### ISSUE THREAD

**Issue by tiankongzhang** [STVIR/pysot#175]
您好，请问你们工程下下载youtube_bb代码下载数据时出现这样视频无法下载：
Unable to download webpage: HTTP Error 429: Too Many Requests (caused by HTTPError()); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output
请问有没有方法解决，谢谢解答！

**Comment by YaoyaoChang** [comment]
same issue

**Comment by yc-zc** [comment]
我不认为这个issue与本项目相关。
请检查你的网络链接。

**Comment by yc-zc** [comment]
由于本issue没有得到更进一步的提问，我现在将其关闭。
如有新的问题，请重新打开它或者创建一个新的issue。
