### ISSUE TITLE
Setup buildup problem

### ISSUE THREAD

**Issue by 13331112522** [STVIR/pysot#18]
Hi, as I followed the instruction of install.md, I encountered the c1.exe failed with exit status 2 problem when I run python setup.py build_ext --inplace. How can I fix it?
Thanks a lot.

**Comment by colinlin1982** [comment]
In Win10, set environment params:
VS140COMNTOOLS: to ${VS_INSTALL_PATH}\Common7\Tools\
VS90COMNTOOLS: to ${VS_INSTALL_PATH}\VC\bin
