### ISSUE TITLE
样本污染问题

### ISSUE THREAD

**Issue by jufeng123** [STVIR/pysot#180]
siamRPN有没有什么措施可以解决长时完全遮挡的样本污染问题？

**Comment by TCBocean** [comment]
The tracker doesn't seem to have a strategy to update the sample, so I guess there should be no sample contamination problem.

**Comment by yc-zc** [comment]
由于本issue没有得到更进一步的提问，我现在将其关闭。
如有新的问题，请重新打开它或者创建一个新的issue。
