### ISSUE TITLE
How to continue training epoch 10? 

### ISSUE THREAD

**Issue by qiusenhui** [STVIR/pysot#184]
[Warning] missing keys: ['bneck1.5.se.se.2.bias', 'bneck1.2.conv3.weight'.............................
AssertionError: load NONE from pretrained checkpoint

When i tried to continue training epoch 10(PRETRAINED: "snapshot/checkpoint_e10.pth"), the error occurred， as shown above.

**Comment by yc-zc** [comment]
Your weights was not load properly.

**Comment by yc-zc** [comment]
Your weights was not load properly.

**Comment by yc-zc** [comment]
Since no further question is asked, I'm closing it for now.
Please reopen it or create a new issue if you have further question.
