### ISSUE TITLE
problem of config.yaml 

### ISSUE THREAD

**Issue by github-aaliu** [STVIR/pysot#185]
感觉代码中自带的config.yaml 的配置有点问题，而且和作者提供的自己训练的模型中附带的config.yaml也不一样

**Comment by winer1997** [comment]
其实是因为代码里面自带的config.yaml改过了，作者网盘中附带的那个没更新。
你可以试一下就知道了，如果用网盘中的那个多半会报错KeyError: 'Non-existent config key: BACKBONE.LAYERS'

**Comment by github-aaliu** [comment]
感谢你的回复，我训的是siamrpn_alex_dwxcorr，总的参数列表comfig.py里有个参数__C.BACKBONE.TRAIN_EPOCH = 10，意思是backbone从第10个epoch才开始训练，这应该是针对backbone有预训练模型的情况，而alexnet没有预训练模型（或者也没加载），但是他本身的config.yaml也没去覆盖这个参数，其中还有很多的参数问题，我只是举了一个

**Comment by winer1997** [comment]
> 感谢你的回复，我训的是siamrpn_alex_dwxcorr，总的参数列表comfig.py里有个参数__C.BACKBONE.TRAIN_EPOCH = 10，意思是backbone从第10个epoch才开始训练，这应该是针对backbone有预训练模型的情况，而alexnet没有预训练模型（或者也没加载），但是他本身的config.yaml也没去覆盖这个参数，其中还有很多的参数问题，我只是举了一个

抱歉这么晚才回复，因为最近在干别的刚刚看到，如果是这样的话目前我也不太清楚，因为我在做的项目最终平台提供不了高额运算力，所以换了其他算法。不好意思，还请再找别人问一下吧

**Comment by chun-chun123** [comment]
训练时候应该选择多gpu文件夹下的config.yaml

**Comment by Dennisky** [comment]
我用siamrpn_r50_l234_dwxcorr能跑通测试代码，为什么用siamrpn_r50_l234_dwxcorr_otb的时候就会报错
    --config config.yamt Traceback (most recent call last):
    File"/home/ob ject_track ing/pysot-master /pysot/utils/model_load.py", line 59, in load_pretrain check_keys(model, pretrained_dict) File "/home/object_track ing/pysot-master /pysot/utils/model_load.py", line 35, in check_keys "10ad NONE from pretrained checkpoint AssertionError:load NONE from pretrained checkpoint During handling of the above exception, another exception occurred:
    Traceback(most recent call last):
    File "../../tools/test.py", line 226, in <module> main() File "../../tools/test.py", line 50, in main model = load_pretrain(model, args.snapshot).cuda().eval() File"/home/xieyilin/object_tracking/pysot-master/pysot/utils/model_load.py", line 68, in load_pretrain check_keys(model, pretrained_dict) File "/home/xieyilin/object_track ing/pysot-master/pysot/utils/model_load.py", line 35, in check_keys load NONE from pretrained checkpont AssertionError: load NONE from pretrained checkpoint

**Comment by Dtappledoghuati** [comment]
请问有成功跑通过siammask吗，我训练总是出问题，应该是config.yaml文件的参数配置问题
