### ISSUE TITLE
Train epoch=20,but in the snapshot : only have e1-e19

### ISSUE THREAD

**Issue by smile-fyl** [STVIR/pysot#188]
When I was training this project  two weeks ago,in the snapshot folder,here will generate 20 files(e1-e20).But now,I find in this folder only have 19 files(e1-e19).Both train epoch are the same(train epoch=20).But I don't know why？Thanks for your reply.

**Comment by yc-zc** [comment]
Please provide steps to reproduce.

**Comment by yc-zc** [comment]
Since no further question is asked, I'm closing it for now.
Please reopen it or create a new issue if you have further question.
