### ISSUE TITLE
RuntimeError: PyTorch was compiled without NumPy support

### ISSUE THREAD

**Issue by xujiao3628** [STVIR/pysot#19]
RuntimeError: PyTorch was compiled without NumPy support
这个怎么解决呀？得用什么版本的numpy呀

**Comment by lb1100** [comment]
I think your pytorch is not installed correctly. Please refer to [INSTALL.md](https://github.com/STVIR/pysot/blob/master/INSTALL.md) to initialize your environment.

**Comment by StevenWangNPU** [comment]
> RuntimeError: PyTorch was compiled without NumPy support
> 这个怎么解决呀？得用什么版本的numpy呀

我也出现这个问题，请问您是怎么解决的啊？
