### ISSUE TITLE
The size of tensor a (17) must match the size of tensor b (25) at non-singleton dimension 4

### ISSUE THREAD

**Issue by 1878708493** [STVIR/pysot#190]
执行训练过程中，loss.py中weight_l1_loss函数里面的diff = (pred_loc - label_loc).abs()语句发生了标题中的错误，pred_loc的size是17 x 17但是label_loc的size是25 x 25，对照论文中的网络结构，pred_loc的size应该没有错，为什么label_loc的size要设置成25呢？

**Comment by 1878708493** [comment]
执行训练过程中，loss.py中weight_l1_loss函数里面的diff = (pred_loc - label_loc).abs()语句发生了标题中的错误，pred_loc的size是17 x 17但是label_loc的size是25 x 25，对照论文中的网络结构，pred_loc的size应该没有错，为什么label_loc的size要设置成25呢？

**Comment by github-aaliu** [comment]
后面也还有很多参数没设置去覆盖config.py里的默认参数（默认参数在训练某些模型的时候是错的），感觉就是没提供完整的config.yaml

**Comment by 1878708493** [comment]
> 执行训练过程中，loss.py中weight_l1_loss函数里面的差异=（pred_loc-label_loc）.abs（）语句发生了标题中的错误，pred_loc的大小是17 x 17但是label_loc的大小是25 x 25，对照论文中的网络结构，pred_loc的大小应该没有错，为什么label_loc的大小要设置成25呢？

a

**Comment by 1878708493** [comment]
> 后面也还有很多参数没设置去覆盖config.py里的默认参数（默认参数在训练某些模型的时候是错的），感觉就是没提供完整的config.yaml

对，感觉确实有些参数不太对

**Comment by meiyu422321** [comment]
刚好路过看到。可能是你们用的是测试的config，多gpu文件夹下的配置文件才是训练用

**Comment by 1878708493** [comment]
> 刚好路过看到。可能是你们用的是测试的config，多gpu文件夹下的配置文件才是训练用

哇，好像真的是，16gpu的那个配置是对的！多谢大哥指点！！

**Comment by yc-zc** [comment]
Since no further question is asked, I'm closing it for now.
Please reopen it or create a new issue if you have further question.
