### ISSUE TITLE
about test own training weight

### ISSUE THREAD

**Issue by Emanuel-c** [STVIR/pysot#196]
i have already trained the pysot in coco dataset, and got the checkpoint_e1.pth to checkpoint_e20.pth weight ,how should i test all weight in terminal @lb1100 @StrangerZhang @foolwood

**Comment by Emanuel-c** [comment]
I fond the order to run the test
`START=10
END=20
seq $START 1 $END | \
    xargs -I {} echo "snapshot/checkpoint_e{}.pth" | \
    xargs -I {} \ 
    python -u ../../tools/test.py \
        --snapshot {} \
	--config config.yaml \
	--dataset VOT2018 2>&1 | tee logs/test_dataset.log`
because I only download dataset VOT2016,so when I change the dataset VOT2018 to VOT2016, it shows the following exception:
`Traceback (most recent call last):
  File "../../tools/test.py", line 226, in <module>
    main()
  File "../../tools/test.py", line 58, in main
    load_img=False)
  File "/home/lab/cym/pysot/toolkit/datasets/__init__.py", line 40, in create_dataset
    raise Exception("unknow dataset {}".format(kwargs['name']))
Exception: unknow dataset `/home/lab/cym/pysot/testing_dataset/VOT2016` 

how can I resolve it ,please help me

**Comment by ThomasBomjan** [comment]
I got some error during testing I created VOT2018 folder and put  VOT2018.json
After quick run 
>> |python -u ../../tools/test.py  --snapshot snapshot/checkpoint_e5  --config config.yaml  --dataset VOT2018 2>&1 | tee logs/test_dataset.log

I got this error AssertionError: >> /home/tt/pysot/tools/../testing_dataset/VOT2018/ants1/color/00000001.jpg
loading VOT2018:   0%|                                                | 0/60 [00:00<?, ?it/s, ants

Did you fix it?
