### ISSUE TITLE
使用backbone/resnet_atrous作为backbone的时候layer3 和 layer4并没有改变feature map的大小

### ISSUE THREAD

**Issue by cunjif** [STVIR/pysot#197]
https://github.com/STVIR/pysot/blob/052b9678a7ed336752f74dc6af31cc00eb004551/pysot/models/backbone/resnet_atrous.py#L131

layer3 在注释上应该把feature map从15x15降为7x7, 但是layer 3层并没有改变feature map的大小啊，同时 layer4层也没有改变feature map的大小，我测试的时候 layer3 的输入为15x15，输出layer 4的输出时仍然为15x15
😂

**Comment by beihaifusang** [comment]
是的，因为用atrous conv 替代了 stride-2 的普通conv

**Comment by cunjif** [comment]
@beihaifusang 这么说，是不是较大模板的feature map有益于xcorr操作

**Comment by beihaifusang** [comment]
嗯嗯，文章里也说了这样子有助于 location 的回归

**Comment by hqabcxyxz** [comment]
@beihaifusang 您好，请问您知道为何最终输出的得分图大小是25么？  x和z经过res50之后变成了31和15，互相卷积之后不是应该是（31-15）/1+1=17大小么？

**Comment by beihaifusang** [comment]
15x15的只用了中间 7x7 的部分

**Comment by yc-zc** [comment]
Since no further question is asked, I'm closing it for now.
Please reopen it or create a new issue if you have further question.
