### ISSUE TITLE
RuntimeError: Error(s) in loading state_dict for ModelBuilder: on own dataset when using demo.py

### ISSUE THREAD

**Issue by dbofseuofhust** [STVIR/pysot#198]
Traceback (most recent call last):
  File "../tools/demo.py", line 111, in <module>
    main()
  File "../tools/demo.py", line 71, in main
    map_location=lambda storage, loc: storage.cpu()))
  File "/home/dongbin/anaconda3/envs/pysot/lib/python3.6/site-packages/torch/nn/modules/module.py", line 719, in load_state_dict
    self.__class__.__name__, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for ModelBuilder:
	Missing key(s) in state_dict: "backbone.conv1.weight", "backbone.bn1.weight", "backbone.bn1.bias", "backbone.bn1.running_mean", "backbone.bn1.running_var", "backbone.layer1.0.conv1.weight", "backbone.layer1.0.bn1.weight", "backbone.layer1.0.bn1.bias", "backbone.layer1.0.bn1.running_mean", "backbone.layer1.0.bn1.running_var", "backbone.layer1.0.conv2.weight", "backbone.layer1.0.bn2.weight", "backbone.layer1.0.bn2.bias", "backbone.layer1.0.bn2.running_mean", "backbone.layer1.0.bn2.running_var", "backbone.layer1.0.conv3.weight", "backbone.layer1.0.bn3.weight", "backbone.layer1.0.bn3.bias", "backbone.layer1.0.bn3.running_mean", "backbone.layer1.0.bn3.running_var", "backbone.layer1.0.downsample.0.weight", "backbone.layer1.0.downsample.1.weight", "backbone.layer1.0.downsample.1.bias", "backbone.layer1.0.downsample.1.running_mean", "backbone.layer1.0.downsample.1.running_var", "backbone.layer1.1.conv1.weight", "backbone.layer1.1.bn1.weight", "backbone.layer1.1.bn1.bias", "backbone.layer1.1.bn1.running_mean", "backbone.layer1.1.bn1.running_var", "backbone.layer1.1.conv2.weight", "backbone.layer1.1.bn2.weight", "backbone.layer1.1.bn2.bias", "backbone.layer1.1.bn2.running_mean", "backbone.layer1.1.bn2.running_var", "backbone.layer1.1.conv3.weight", "backbone.layer1.1.bn3.weight", "backbone.layer1.1.bn3.bias", "backbone.layer1.1.bn3.running_mean", "backbone.layer1.1.bn3.running_var", "backbone.layer1.2.conv1.weight", "backbone.layer1.2.bn1.weight", "backbone.layer1.2.bn1.bias", "backbone.layer1.2.bn1.running_mean", "backbone.layer1.2.bn1.running_var", "backbone.layer1.2.conv2.weight", "backbone.layer1.2.bn2.weight", "backbone.layer1.2.bn2.bias", "backbone.layer1.2.bn2.running_mean", "backbone.layer1.2.bn2.running_var", "backbone.layer1.2.conv3.weight", "backbone.layer1.2.bn3.weight", "backbone.layer1.2.bn3.bias", "backbone.layer1.2.bn3.running_mean", "backbone.layer1.2.bn3.running_var", "backbone.layer2.0.conv1.weight", "backbone.layer2.0.bn1.weight", "backbone.layer2.0.bn1.bias", "backbone.layer2.0.bn1.running_mean", "backbone.layer2.0.bn1.running_var", "backbone.layer2.0.conv2.weight", "backbone.layer2.0.bn2.weight", "backbone.layer2.0.bn2.bias", "backbone.layer2.0.bn2.running_mean", "backbone.layer2.0.bn2.running_var", "backbone.layer2.0.conv3.weight", "backbone.layer2.0.bn3.weight", "backbone.layer2.0.bn3.bias", "backbone.layer2.0.bn3.running_mean", "backbone.layer2.0.bn3.running_var", "backbone.layer2.0.downsample.0.weight", "backbone.layer2.0.downsample.1.weight", "backbone.layer2.0.downsample.1.bias", "backbone.layer2.0.downsample.1.running_mean", "backbone.layer2.0.downsample.1.running_var", "backbone.layer2.1.conv1.weight", "backbone.layer2.1.bn1.weight", "backbone.layer2.1.bn1.bias", "backbone.layer2.1.bn1.running_mean", "backbone.layer2.1.bn1.running_var", "backbone.layer2.1.conv2.weight", "backbone.layer2.1.bn2.weight", "backbone.layer2.1.bn2.bias", "backbone.layer2.1.bn2.running_mean", "backbone.layer2.1.bn2.running_var", "backbone.layer2.1.conv3.weight", "backbone.layer2.1.bn3.weight", "backbone.layer2.1.bn3.bias", "backbone.layer2.1.bn3.running_mean", "backbone.layer2.1.bn3.running_var", "backbone.layer2.2.conv1.weight", "backbone.layer2.2.bn1.weight", "backbone.layer2.2.bn1.bias", "backbone.layer2.2.bn1.running_mean", "backbone.layer2.2.bn1.running_var", "backbone.layer2.2.conv2.weight", "backbone.layer2.2.bn2.weight", "backbone.layer2.2.bn2.bias", "backbone.layer2.2.bn2.running_mean", "backbone.layer2.2.bn2.running_var", "backbone.layer2.2.conv3.weight", "backbone.layer2.2.bn3.weight", "backbone.layer2.2.bn3.bias", "backbone.layer2.2.bn3.running_mean", "backbone.layer2.2.bn3.running_var", "backbone.layer2.3.conv1.weight", "backbone.layer2.3.bn1.weight", "backbone.layer2.3.bn1.bias", "backbone.layer2.3.bn1.running_mean", "backbone.layer2.3.bn1.running_var", "backbone.layer2.3.conv2.weight", "backbone.layer2.3.bn2.weight", "backbone.layer2.3.bn2.bias", "backbone.layer2.3.bn2.running_mean", "backbone.layer2.3.bn2.running_var", "backbone.layer2.3.conv3.weight", "backbone.layer2.3.bn3.weight", "backbone.layer2.3.bn3.bias", "backbone.layer2.3.bn3.running_mean", "backbone.layer2.3.bn3.running_var", "backbone.layer3.0.conv1.weight", "backbone.layer3.0.bn1.weight", "backbone.layer3.0.bn1.bias", "backbone.layer3.0.bn1.running_mean", "backbone.layer3.0.bn1.running_var", "backbone.layer3.0.conv2.weight", "backbone.layer3.0.bn2.weight", "backbone.layer3.0.bn2.bias", "backbone.layer3.0.bn2.running_mean", "backbone.layer3.0.bn2.running_var", "backbone.layer3.0.conv3.weight", "backbone.layer3.0.bn3.weight", "backbone.layer3.0.bn3.bias", "backbone.layer3.0.bn3.running_mean", "backbone.layer3.0.bn3.running_var", "backbone.layer3.0.downsample.0.weight", "backbone.layer3.0.downsample.1.weight", "backbone.layer3.0.downsample.1.bias", "backbone.layer3.0.downsample.1.running_mean", "backbone.layer3.0.downsample.1.running_var", "backbone.layer3.1.conv1.weight", "backbone.layer3.1.bn1.weight", "backbone.layer3.1.bn1.bias", "backbone.layer3.1.bn1.running_mean", "backbone.layer3.1.bn1.running_var", "backbone.layer3.1.conv2.weight", "backbone.layer3.1.bn2.weight", "backbone.layer3.1.bn2.bias", "backbone.layer3.1.bn2.running_mean", "backbone.layer3.1.bn2.running_var", "backbone.layer3.1.conv3.weight", "backbone.layer3.1.bn3.weight", "backbone.layer3.1.bn3.bias", "backbone.layer3.1.bn3.running_mean", "backbone.layer3.1.bn3.running_var", "backbone.layer3.2.conv1.weight", "backbone.layer3.2.bn1.weight", "backbone.layer3.2.bn1.bias", "backbone.layer3.2.bn1.running_mean", "backbone.layer3.2.bn1.running_var", "backbone.layer3.2.conv2.weight", "backbone.layer3.2.bn2.weight", "backbone.layer3.2.bn2.bias", "backbone.layer3.2.bn2.running_mean", "backbone.layer3.2.bn2.running_var", "backbone.layer3.2.conv3.weight", "backbone.layer3.2.bn3.weight", "backbone.layer3.2.bn3.bias", "backbone.layer3.2.bn3.running_mean", "backbone.layer3.2.bn3.running_var", "backbone.layer3.3.conv1.weight", "backbone.layer3.3.bn1.weight", "backbone.layer3.3.bn1.bias", "backbone.layer3.3.bn1.running_mean", "backbone.layer3.3.bn1.running_var", "backbone.layer3.3.conv2.weight", "backbone.layer3.3.bn2.weight", "backbone.layer3.3.bn2.bias", "backbone.layer3.3.bn2.running_mean", "backbone.layer3.3.bn2.running_var", "backbone.layer3.3.conv3.weight", "backbone.layer3.3.bn3.weight", "backbone.layer3.3.bn3.bias", "backbone.layer3.3.bn3.running_mean", "backbone.layer3.3.bn3.running_var", "backbone.layer3.4.conv1.weight", "backbone.layer3.4.bn1.weight", "backbone.layer3.4.bn1.bias", "backbone.layer3.4.bn1.running_mean", "backbone.layer3.4.bn1.running_var", "backbone.layer3.4.conv2.weight", "backbone.layer3.4.bn2.weight", "backbone.layer3.4.bn2.bias", "backbone.layer3.4.bn2.running_mean", "backbone.layer3.4.bn2.running_var", "backbone.layer3.4.conv3.weight", "backbone.layer3.4.bn3.weight", "backbone.layer3.4.bn3.bias", "backbone.layer3.4.bn3.running_mean", "backbone.layer3.4.bn3.running_var", "backbone.layer3.5.conv1.weight", "backbone.layer3.5.bn1.weight", "backbone.layer3.5.bn1.bias", "backbone.layer3.5.bn1.running_mean", "backbone.layer3.5.bn1.running_var", "backbone.layer3.5.conv2.weight", "backbone.layer3.5.bn2.weight", "backbone.layer3.5.bn2.bias", "backbone.layer3.5.bn2.running_mean", "backbone.layer3.5.bn2.running_var", "backbone.layer3.5.conv3.weight", "backbone.layer3.5.bn3.weight", "backbone.layer3.5.bn3.bias", "backbone.layer3.5.bn3.running_mean", "backbone.layer3.5.bn3.running_var", "backbone.layer4.0.conv1.weight", "backbone.layer4.0.bn1.weight", "backbone.layer4.0.bn1.bias", "backbone.layer4.0.bn1.running_mean", "backbone.layer4.0.bn1.running_var", "backbone.layer4.0.conv2.weight", "backbone.layer4.0.bn2.weight", "backbone.layer4.0.bn2.bias", "backbone.layer4.0.bn2.running_mean", "backbone.layer4.0.bn2.running_var", "backbone.layer4.0.conv3.weight", "backbone.layer4.0.bn3.weight", "backbone.layer4.0.bn3.bias", "backbone.layer4.0.bn3.running_mean", "backbone.layer4.0.bn3.running_var", "backbone.layer4.0.downsample.0.weight", "backbone.layer4.0.downsample.1.weight", "backbone.layer4.0.downsample.1.bias", "backbone.layer4.0.downsample.1.running_mean", "backbone.layer4.0.downsample.1.running_var", "backbone.layer4.1.conv1.weight", "backbone.layer4.1.bn1.weight", "backbone.layer4.1.bn1.bias", "backbone.layer4.1.bn1.running_mean", "backbone.layer4.1.bn1.running_var", "backbone.layer4.1.conv2.weight", "backbone.layer4.1.bn2.weight", "backbone.layer4.1.bn2.bias", "backbone.layer4.1.bn2.running_mean", "backbone.layer4.1.bn2.running_var", "backbone.layer4.1.conv3.weight", "backbone.layer4.1.bn3.weight", "backbone.layer4.1.bn3.bias", "backbone.layer4.1.bn3.running_mean", "backbone.layer4.1.bn3.running_var", "backbone.layer4.2.conv1.weight", "backbone.layer4.2.bn1.weight", "backbone.layer4.2.bn1.bias", "backbone.layer4.2.bn1.running_mean", "backbone.layer4.2.bn1.running_var", "backbone.layer4.2.conv2.weight", "backbone.layer4.2.bn2.weight", "backbone.layer4.2.bn2.bias", "backbone.layer4.2.bn2.running_mean", "backbone.layer4.2.bn2.running_var", "backbone.layer4.2.conv3.weight", "backbone.layer4.2.bn3.weight", "backbone.layer4.2.bn3.bias", "backbone.layer4.2.bn3.running_mean", "backbone.layer4.2.bn3.running_var", "neck.downsample2.downsample.0.weight", "neck.downsample2.downsample.1.weight", "neck.downsample2.downsample.1.bias", "neck.downsample2.downsample.1.running_mean", "neck.downsample2.downsample.1.running_var", "neck.downsample3.downsample.0.weight", "neck.downsample3.downsample.1.weight", "neck.downsample3.downsample.1.bias", "neck.downsample3.downsample.1.running_mean", "neck.downsample3.downsample.1.running_var", "neck.downsample4.downsample.0.weight", "neck.downsample4.downsample.1.weight", "neck.downsample4.downsample.1.bias", "neck.downsample4.downsample.1.running_mean", "neck.downsample4.downsample.1.running_var", "rpn_head.cls_weight", "rpn_head.loc_weight", "rpn_head.rpn2.cls.conv_kernel.0.weight", "rpn_head.rpn2.cls.conv_kernel.1.weight", "rpn_head.rpn2.cls.conv_kernel.1.bias", "rpn_head.rpn2.cls.conv_kernel.1.running_mean", "rpn_head.rpn2.cls.conv_kernel.1.running_var", "rpn_head.rpn2.cls.conv_search.0.weight", "rpn_head.rpn2.cls.conv_search.1.weight", "rpn_head.rpn2.cls.conv_search.1.bias", "rpn_head.rpn2.cls.conv_search.1.running_mean", "rpn_head.rpn2.cls.conv_search.1.running_var", "rpn_head.rpn2.cls.head.0.weight", "rpn_head.rpn2.cls.head.1.weight", "rpn_head.rpn2.cls.head.1.bias", "rpn_head.rpn2.cls.head.1.running_mean", "rpn_head.rpn2.cls.head.1.running_var", "rpn_head.rpn2.cls.head.3.weight", "rpn_head.rpn2.cls.head.3.bias", "rpn_head.rpn2.loc.conv_kernel.0.weight", "rpn_head.rpn2.loc.conv_kernel.1.weight", "rpn_head.rpn2.loc.conv_kernel.1.bias", "rpn_head.rpn2.loc.conv_kernel.1.running_mean", "rpn_head.rpn2.loc.conv_kernel.1.running_var", "rpn_head.rpn2.loc.conv_search.0.weight", "rpn_head.rpn2.loc.conv_search.1.weight", "rpn_head.rpn2.loc.conv_search.1.bias", "rpn_head.rpn2.loc.conv_search.1.running_mean", "rpn_head.rpn2.loc.conv_search.1.running_var", "rpn_head.rpn2.loc.head.0.weight", "rpn_head.rpn2.loc.head.1.weight", "rpn_head.rpn2.loc.head.1.bias", "rpn_head.rpn2.loc.head.1.running_mean", "rpn_head.rpn2.loc.head.1.running_var", "rpn_head.rpn2.loc.head.3.weight", "rpn_head.rpn2.loc.head.3.bias", "rpn_head.rpn3.cls.conv_kernel.0.weight", "rpn_head.rpn3.cls.conv_kernel.1.weight", "rpn_head.rpn3.cls.conv_kernel.1.bias", "rpn_head.rpn3.cls.conv_kernel.1.running_mean", "rpn_head.rpn3.cls.conv_kernel.1.running_var", "rpn_head.rpn3.cls.conv_search.0.weight", "rpn_head.rpn3.cls.conv_search.1.weight", "rpn_head.rpn3.cls.conv_search.1.bias", "rpn_head.rpn3.cls.conv_search.1.running_mean", "rpn_head.rpn3.cls.conv_search.1.running_var", "rpn_head.rpn3.cls.head.0.weight", "rpn_head.rpn3.cls.head.1.weight", "rpn_head.rpn3.cls.head.1.bias", "rpn_head.rpn3.cls.head.1.running_mean", "rpn_head.rpn3.cls.head.1.running_var", "rpn_head.rpn3.cls.head.3.weight", "rpn_head.rpn3.cls.head.3.bias", "rpn_head.rpn3.loc.conv_kernel.0.weight", "rpn_head.rpn3.loc.conv_kernel.1.weight", "rpn_head.rpn3.loc.conv_kernel.1.bias", "rpn_head.rpn3.loc.conv_kernel.1.running_mean", "rpn_head.rpn3.loc.conv_kernel.1.running_var", "rpn_head.rpn3.loc.conv_search.0.weight", "rpn_head.rpn3.loc.conv_search.1.weight", "rpn_head.rpn3.loc.conv_search.1.bias", "rpn_head.rpn3.loc.conv_search.1.running_mean", "rpn_head.rpn3.loc.conv_search.1.running_var", "rpn_head.rpn3.loc.head.0.weight", "rpn_head.rpn3.loc.head.1.weight", "rpn_head.rpn3.loc.head.1.bias", "rpn_head.rpn3.loc.head.1.running_mean", "rpn_head.rpn3.loc.head.1.running_var", "rpn_head.rpn3.loc.head.3.weight", "rpn_head.rpn3.loc.head.3.bias", "rpn_head.rpn4.cls.conv_kernel.0.weight", "rpn_head.rpn4.cls.conv_kernel.1.weight", "rpn_head.rpn4.cls.conv_kernel.1.bias", "rpn_head.rpn4.cls.conv_kernel.1.running_mean", "rpn_head.rpn4.cls.conv_kernel.1.running_var", "rpn_head.rpn4.cls.conv_search.0.weight", "rpn_head.rpn4.cls.conv_search.1.weight", "rpn_head.rpn4.cls.conv_search.1.bias", "rpn_head.rpn4.cls.conv_search.1.running_mean", "rpn_head.rpn4.cls.conv_search.1.running_var", "rpn_head.rpn4.cls.head.0.weight", "rpn_head.rpn4.cls.head.1.weight", "rpn_head.rpn4.cls.head.1.bias", "rpn_head.rpn4.cls.head.1.running_mean", "rpn_head.rpn4.cls.head.1.running_var", "rpn_head.rpn4.cls.head.3.weight", "rpn_head.rpn4.cls.head.3.bias", "rpn_head.rpn4.loc.conv_kernel.0.weight", "rpn_head.rpn4.loc.conv_kernel.1.weight", "rpn_head.rpn4.loc.conv_kernel.1.bias", "rpn_head.rpn4.loc.conv_kernel.1.running_mean", "rpn_head.rpn4.loc.conv_kernel.1.running_var", "rpn_head.rpn4.loc.conv_search.0.weight", "rpn_head.rpn4.loc.conv_search.1.weight", "rpn_head.rpn4.loc.conv_search.1.bias", "rpn_head.rpn4.loc.conv_search.1.running_mean", "rpn_head.rpn4.loc.conv_search.1.running_var", "rpn_head.rpn4.loc.head.0.weight", "rpn_head.rpn4.loc.head.1.weight", "rpn_head.rpn4.loc.head.1.bias", "rpn_head.rpn4.loc.head.1.running_mean", "rpn_head.rpn4.loc.head.1.running_var", "rpn_head.rpn4.loc.head.3.weight", "rpn_head.rpn4.loc.head.3.bias". 
	Unexpected key(s) in state_dict: "epoch", "state_dict", "optimizer".

**Comment by dbofseuofhust** [comment]
Thanks for you useful code，after I trained my dataset（1 class）, I use python demo.py to test, I occur this error,could you help me solve this problem?
I have cloned the lasted repo, and my config.yaml is as follows:
META_ARC: "siamrpn_r50_l234_dwxcorr"

BACKBONE:
    TYPE: "resnet50"
    KWARGS:
        used_layers: [2, 3, 4]

ADJUST:
    ADJUST: true
    TYPE: "AdjustAllLayer"
    KWARGS:
        in_channels: [512, 1024, 2048]
        out_channels: [256, 256, 256]

RPN:
    TYPE: 'MultiRPN'
    KWARGS:
        anchor_num: 5
        in_channels: [256, 256, 256]
        weighted: true

MASK:
    MASK: false

ANCHOR:
    STRIDE: 8
    RATIOS: [0.33, 0.5, 1, 2, 3]
    SCALES: [8]
    ANCHOR_NUM: 5

TRACK:
    TYPE: 'SiamRPNTracker'
    PENALTY_K: 0.05
    WINDOW_INFLUENCE: 0.42
    LR: 0.38
    EXEMPLAR_SIZE: 127
    INSTANCE_SIZE: 255
    BASE_SIZE: 8
    CONTEXT_AMOUNT: 0.5

**Comment by Emanuel-c** [comment]
I have met the same problem, the training result is 20 checkpoint_e{}.pth set, which weight do you use in the demo, i don't know why the model.pth can work in demo and how did it created.

**Comment by yc-zc** [comment]
Your weights was not properly loaded.

**Comment by ThomasBomjan** [comment]
@yc-zc I also got same issues 
After running 

>>python tools/demo.py --config experiments/siamrpn_r50_l234_dwxcorr_8gpu/config.yaml --snapshot experiments/siamrpn_r50_l234_dwxcorr_8gpu/checkpoint_e9.pth 

>Unexpected key(s) in state_dict: "epoch", "state_dict", "optimizer".

**Comment by yc-zc** [comment]
Since no further question is asked, I'm closing it for now.
Please reopen it or create a new issue if you have further question.
