### ISSUE TITLE
Why the final hot-map shape is 25x25?

### ISSUE THREAD

**Issue by hqabcxyxz** [STVIR/pysot#203]
I notice that in paper SiamRPN++, `Search map(x)` shape is 255,`Target map(z)` shape is 127, after resnet-50 forward, X shape become 31, Z shape become 15.   
I think the final hot map shape should be (31-15)/1+1=17,but  `cfg.TRAIN.OUTPUT_SIZE` is 25,why?   

In `TrkDataset()`,I notice that 
```python
        desired_size = (cfg.TRAIN.SEARCH_SIZE - cfg.TRAIN.EXEMPLAR_SIZE) / \
            cfg.ANCHOR.STRIDE + 1 + cfg.TRAIN.BASE_SIZE
```

why must add `cfg.TRAIN.BASE_SIZE`?

**Comment by adrift00** [comment]
![image](https://user-images.githubusercontent.com/35949066/68526629-1afbd980-0319-11ea-92ce-916648d4a2fe.png)
Because the template feature map will be croped to 7x7, it is implemented in the AdjustLayer.

**Comment by yc-zc** [comment]
Since no further question is asked, I'm closing it for now.
Please reopen it or create a new issue if you have further question.
