### ISSUE TITLE
How to evaluate my own tracker?

### ISSUE THREAD

**Issue by ShiLongCheng** [STVIR/pysot#204]
Thank's for your contribution in visual object tracking. But I have some issues.
I found you have simple explanation about how to evaluate other tracker. So can you write a README file explain how to evaluate my own tracker in OTB100 or OTB50?
Thank you again.

**Comment by yc-zc** [comment]
I would suggest you check out https://github.com/StrangerZhang/pysot-toolkit .
Since this issue is not relevant, I'm closing it for now. 
Please reopen it or create a new issue if you have further question.
