### ISSUE TITLE
Why use INSTANCE_SIZE=287?

### ISSUE THREAD

**Issue by adrift00** [STVIR/pysot#205]
> self.score_size = (cfg.TRACK.INSTANCE_SIZE - cfg.TRACK.EXEMPLAR_SIZE) // \
            cfg.ANCHOR.STRIDE + 1 + cfg.TRACK.BASE_SIZE

Why use the INSTANCE_SIZE=287 in inference phase and it not equal to the SEARCH_SIZE=255？

**Comment by chun-chun123** [comment]
I also have the same question

**Comment by adrift00** [comment]
may be for larger search area
