### ISSUE TITLE
请问如何调整学习率与gpu个数的关系

### ISSUE THREAD

**Issue by kongbia** [STVIR/pysot#206]
在8gpu和16gpu的config中，只有batchsize的差异，学习率需要进行相应调整吗

**Comment by StrangerZhang** [comment]
No need to adjust the learning rate, our gradient reduction uses sum operation.

**Comment by kongbia** [comment]
好的，谢谢！

**Comment by smile-fyl** [comment]
> No need to adjust the learning rate, our gradient reduction uses sum operation.

Exceuse me. I want to know the relation of 'batchsize' and 'learning rate'.When I set the value of 'batchsize' differently, the results of EAO is different too.So when I modify 'batchsize', how can I modify    'learning rate'correspondingly.There are too many 'LR',such as'BACKBONE:LAYERS_LR','TRIN:BASE_LR' etc.

**Comment by yc-zc** [comment]
> > No need to adjust the learning rate, our gradient reduction uses sum operation.
> 
> Exceuse me. I want to know the relation of 'batchsize' and 'learning rate'.When I set the value of 'batchsize' differently, the results of EAO is different too.So when I modify 'batchsize', how can I modify 'learning rate'correspondingly.There are too many 'LR',such as'BACKBONE:LAYERS_LR','TRIN:BASE_LR' etc.

I think you can find the answer in the paper.

**Comment by yc-zc** [comment]
Since no further question is asked, I'm closing it for now.
Please reopen it or create a new issue if you have further question.
