### ISSUE TITLE
Opencv Assertion failed

### ISSUE THREAD

**Issue by hero-y** [STVIR/pysot#208]
hello, I am running the demo.py, and use the --video parameter, but it shows that  cv2.error: OpenCV(4.1.0) /io/opencv/modules/imgproc/src/resize.cpp:3718: error: (-215:Assertion failed) !ssize.empty() in function 'resize'
![image](https://user-images.githubusercontent.com/45655880/66836316-b3f63980-ef93-11e9-9b1a-f9294621997b.png)
Can you help me ? Thank you

**Comment by JimmyLauren** [comment]
same here, any solutions?

**Comment by JimmyLauren** [comment]
the problems caused by cv2.selectROI. the width and height are 0
