### ISSUE TITLE
Can it run in Jetson Nano

### ISSUE THREAD

**Issue by ZhaoZeng101** [STVIR/pysot#21]

**Comment by lb1100** [comment]
We only tested this code on PCs. If you can run PyTorch with CUDA support on Jetson Nano, I believe it can run on it too.

**Comment by ZhaoZeng101** [comment]
Thanks, I tried on Jetson Nano,well done

**Comment by mengqlTHU** [comment]
@ZhaoZeng101 Have you successfully run it on jetson nano? I also tried but when I run a demo of bag.avi, after selecting ROI, the video just freeze and the whole system just stuck and I have to restart the nano.

**Comment by colinlin1982** [comment]
I have run demo.py in Jetson Nano with siamrpn_alex_dwxcorr_otb, at 3fps while showing opencv window, or 5fps while hiding window.
IMX219-77 and 720p video file tested.

**Comment by ZhaoZeng101** [comment]
@mengqlTHU 
The jetson nano has only 4G of memory, which is a bit of a headache when running large images. It is recommended to run large images, you need to compress the image before running.

**Comment by mengqlTHU** [comment]
@ZhaoZeng101 Thank you. I have found two things are important: First you have to use a power supply with larger output current.[https://www.jetsonhacks.com/2019/04/10/jetson-nano-use-more-power/](url). Second you have to set up a swap file to use more memory. [https://www.jetsonhacks.com/2019/04/14/jetson-nano-use-more-memory/](url)

**Comment by zeleniyslonik** [comment]
I am sorry to write in the closed topics, but have anybody tried converting the model to TensorRT? Does doing this give any significant acceleration to the inference process?
