### ISSUE TITLE
训练效果不稳定，请问如何评估一组超参数或者一个改进是否有改进效果？

### ISSUE THREAD

**Issue by JamesLearning** [STVIR/pysot#210]
直接用这里提供的siamrpn_r50_l234_dwxcorr_8gpu去跑，对epoch11-20都在VOT2018做hp_search.py一次，然后用eval.py获得其中最好成绩。
在train.py用不同的seed，重复以上实验，然后最后的eao最好的和最差的差不多都差6个点了。
训练效果受随机性影响这么大，如果我要实验一组新的超参数，或者研究一项改进，要怎么样才能证明它有改进，而不是随机性碰巧的？
谢谢回复。

**Comment by 121649982** [comment]
你好，可以提供一下你的QQ号吗?我最近也在用这个，但是还没训练起来，向你请教一下。我QQ：121649982

**Comment by MARMOTatZJU** [comment]
Consider to test your modification on GOT-10k benchmark which provides a more stable benchmarking protocol.

**Comment by yc-zc** [comment]
> 直接用这里提供的siamrpn_r50_l234_dwxcorr_8gpu去跑，对epoch11-20都在VOT2018做hp_search.py一次，然后用eval.py获得其中最好成绩。
> 在train.py用不同的seed，重复以上实验，然后最后的eao最好的和最差的差不多都差6个点了。
> 训练效果受随机性影响这么大，如果我要实验一组新的超参数，或者研究一项改进，要怎么样才能证明它有改进，而不是随机性碰巧的？
> 谢谢回复。

一般我们会设置固定的随机种子并将pytorch的deterministic设置为True。

**Comment by yc-zc** [comment]
由于本issue没有得到更进一步的提问，我现在将其关闭。
如有新的问题，请重新打开它或者创建一个新的issue。
