### ISSUE TITLE
训练的模型完全跟不上东西

### ISSUE THREAD

**Issue by 1878708493** [STVIR/pysot#211]
您好，我在单机下使用siamrpn_alex_dwxcorr_16gpu中的config去训练模型，训练好之后使用模型在OTB100数据集上测试，发现完全跟踪不上目标。不是会跟丢，是完全没有在跟踪，目标框神游。
config中的配置和训练代码全部使用官方提供的没有改，我不知道是什么地方出现了问题，还望大佬解惑~

**Comment by sansanfree** [comment]
我和你一样，你解决了这个问题了吗？貌似用resnet50就可以
