### ISSUE TITLE
单机两卡，gup使用率为0

### ISSUE THREAD

**Issue by github-aaliu** [STVIR/pysot#214]
CUDA_VISIBLE_DEVICES=0,1
python -m torch.distributed.launch \
    --nproc_per_node=2 \
    --master_port=2333 \
    ../../tools/train.py --cfg config.yaml
我是这样写的运行程序，可以运行，但是gpu的使用率为0,却占gpu内存了，求解是什么情况。该怎么改？

**Comment by Tonyhuang1998** [comment]
请问运行你这段代码时报错No module named torch.distributed  该怎么解决呢？
