### ISSUE TITLE
Youtube_bb cropped dataset on Baidu is unavailable 

### ISSUE THREAD

**Issue by Junochiu** [STVIR/pysot#216]
Hi! as the title mentioned, the link to the BaiduYun for the cropped Youtube_bb dataset is unavailable.
Since i got a lot of errors saying : 

> YouTube said:Unable to extract video data

so I think it is better that I use the dataset you provided on BaiduYun~
could you kindly put up the correct link to BaiduYun? :)
Thanks!

**Comment by lb1100** [comment]
The link was updated about 3 month ago. Check [TRAIN.md](https://github.com/STVIR/pysot/blob/master/TRAIN.md)

**Comment by Junochiu** [comment]
Hi, the BaiduYun link in TRAIN.md show me this ~

<img width="953" alt="BaiduYun" src="https://user-images.githubusercontent.com/48847495/67355577-29609c00-f58a-11e9-8de8-40f64c5f0096.png">

Maybe it's overdue or something?
thanks!

**Comment by lb1100** [comment]
It looks good to me. Check if you are using the latest link with extract code.

**Comment by Junochiu** [comment]
problem solved! Thanks!

**Comment by ny222333** [comment]
Hi! as the title mentioned, the link to the BaiduYun for the cropped Youtube_bb dataset is unavailable  again！could you share with me if you downloaded?thanks!
