### ISSUE TITLE
Would single gpu will affect the results?

### ISSUE THREAD

**Issue by smile-fyl** [STVIR/pysot#221]
Thanks for your good work! Now,I reperformance this project with two gpus ,EAO=0.41;In the second time, I set nproc_per_node=1,I find this project can work with single gpu,I want to know:would single gpu will affect the results?

**Comment by pangr** [comment]
Counld you share that how you got the result(EAO=0.41)? which backbone?

**Comment by smile-fyl** [comment]
> Counld you share that how you got the result(EAO=0.41)? which backbone?

Backbone is ResNet. I modified batch_size and adjusted hyper-parameters.

**Comment by pangr** [comment]
> > Counld you share that how you got the result(EAO=0.41)? which backbone?
> 
> Backbone is ResNet. I modified batch_size and adjusted hyper-parameters.
How much that hyper-parameters could improve?

**Comment by alyssa121** [comment]
> Thanks for your good work! Now,I reperformance this project with two gpus ,EAO=0.41;In the second time, I set nproc_per_node=1,I find this project can work with single gpu,I want to know:would single gpu will affect the results?

Could you share the exact batch_size and hyper-parameters that you had adjusted? Thanks very much!!!

**Comment by cappuccino19** [comment]
could you share the training procedure. I also train with single GPU. I got the hint below. I try several methods, but I can't deal with it. I follow the mannul totally.


Traceback (most recent call last):
File "../../tools/train.py", line 319, in 
main()
File "../../tools/train.py", line 314, in main
train(train_loader, dist_model, optimizer, lr_scheduler, tb_writer)
File "../../tools/train.py", line 176, in train
for idx, data in enumerate(train_loader):
File "/home/gao/anaconda3/envs/pysot/lib/python3.7/site-packages/torch/utils/d

ata/dataloader.py", line 336, in next
return self._process_next_batch(batch)
File "/home/gao/anaconda3/envs/pysot/lib/python3.7/site-packages/torch/utils/d

ata/dataloader.py", line 357, in _process_next_batch
raise batch.exc_type(batch.exc_msg)
AttributeError: Traceback (most recent call last):
File "/home/gao/anaconda3/envs/pysot/lib/python3.7/site-packages/torch/utils/d

ata/dataloader.py", line 106, in _worker_loop
samples = collate_fn([dataset[i] for i in batch_indices])
File "/home/gao/anaconda3/envs/pysot/lib/python3.7/site-packages/torch/utils/d

ata/dataloader.py", line 106, in 
samples = collate_fn([dataset[i] for i in batch_indices])
File "/media/gao/pysot-master/pysot/datasets/dataset.py", line 253, in __getit

em__
template_box = self._get_bbox(template_image, template[1])
File "/media/gao/pysot-master/pysot/datasets/dataset.py", line 214, in _get_bb

ox
imh, imw = image.shape[:2]
AttributeError: 'NoneType' object has no attribute 'shape'

**Comment by yc-zc** [comment]
No.
