### ISSUE TITLE
The relation of 'batchsize' and 'learning rate'.

### ISSUE THREAD

**Issue by smile-fyl** [STVIR/pysot#223]
Exceuse me. I want to know the relation of 'batchsize' and 'learning rate'.When I set the value of 'batchsize' differently, the results of EAO is different too.So when I modify 'batchsize', how can I modify    'learning rate'correspondingly.There are too many 'LR',such as'BACKBONE:LAYERS_LR','TRIN:BASE_LR' etc.

**Comment by yc-zc** [comment]
In general, the learning rate should increase as the batch size increase. 
For the other question, I suggest you read the paper more carefully, it's already there!

**Comment by yc-zc** [comment]
Since no further question is asked, I'm closing it for now.
Please reopen it or create a new issue if you have further question.
