### ISSUE TITLE
torch.distributed的一些问题

### ISSUE THREAD

**Issue by github-aaliu** [STVIR/pysot#224]
torch.distributed新手，问几个问题
1.看程序好像每个核都load了参数，为什么还要主核发布参数呢
2.为什么不直接用DistributedDataParallel
3.可不可以直接all_reduce一下loss，这样不是会快一些吗，唯一的区别应该就是bn层吧？
4.all_reduce参数的时候为什么用sum而不用平均呢

**Comment by lb1100** [comment]
1. Parameters in head/neck are initialized randomly, so broadcasting parameters are required.
2. I'm not familiar with DistributedDataParallel, you can have a try and see whether it's faster.
3. Couldn't understand your question
4. In distributed scenerio, it's similar to increase batch size. According to linear scaling rule, learning rate should be increased while increasing batch size. Using sum of the gradients are the same with increasing lr.

**Comment by yc-zc** [comment]
Since no further question is asked, I'm closing it for now.
Please reopen it or create a new issue if you have further question.
