### ISSUE TITLE
(Testing with LaSOT dataset.)   ImportError: No module named pysot.core.config

### ISSUE THREAD

**Issue by Arun118** [STVIR/pysot#225]
ImportError: No module named pysot.core.config

**Comment by salmedina** [comment]
What worked for me was to add the pysot path to `PYTHONPATH`

```
export PYTHONPATH=/home/user/Devel/pysot
```

Where `/home/user/Devel/pysot` is the path to the cloned repo in my local machine.

**Comment by yc-zc** [comment]
Since no further question is asked, I'm closing it for now.
Please reopen it or create a new issue if you have further question.
