### ISSUE TITLE
框回归后处理问题

### ISSUE THREAD

**Issue by igurantee** [STVIR/pysot#228]
你好，

siammask_tracker.py第114-115行：
cx = bbox[0] + self.center_pos[0]
cy = bbox[1] + self.center_pos[1]
这里bbox是预测的框相对于255*255的区域左上角的坐标，而center_pos是这个255*255的区域中心在原图中的坐标，可是如果要求预测框在原图中的坐标不是应该加上原点(top_left)在原图中的坐标吗？望解答，谢谢！

**Comment by adrift00** [comment]
tracker里生成的anchor是以255*255的中心点为参考的，所以回归后也是bbox也是相对于255*255中心点的坐标。

**Comment by czh55** [comment]
train和tracker使用不同的参考，这样不影响效果吗？

**Comment by yc-zc** [comment]
由于本issue没有得到更进一步的提问，我现在将其关闭。
如有新的问题，请重新打开它或者创建一个新的issue。
