### ISSUE TITLE
Mobilenetv2 pretrained backbone?

### ISSUE THREAD

**Issue by adrift00** [STVIR/pysot#230]
@lb1100 
Why is there no pretrained backbone for mobilenetv2? And there is no train config for mobilenetv2. Would you upload the pretrained backbone and config file of mobilenetv2?

**Comment by adrift00** [comment]
Why is there no pretrained backbone for mobilenetv2? And there are no train config for mobilenetv2.

**Comment by marghesc** [comment]
Can you provide pretrained weights and mobilenetv2 config?
