### ISSUE TITLE
Different benchmark with vot-toolkit and pysot-toolkit?

### ISSUE THREAD

**Issue by Puzzle0612** [STVIR/pysot#235]
The final benchmark results generated by the vot-toolkit(MATLAB) and this pysot-toolkit with the same  .txt files are different?
![sendpix0](https://user-images.githubusercontent.com/33413429/68730580-0a44af80-0608-11ea-9bd9-f71fe86829ad.jpg)
![sendpix2](https://user-images.githubusercontent.com/33413429/68730634-437d1f80-0608-11ea-9526-d283e4ebfff8.jpg)

**Comment by yc-zc** [comment]
Are you sure you are in the right repo?
