### ISSUE TITLE
how to crop the template patch

### ISSUE THREAD

**Issue by kl456123** [STVIR/pysot#236]
![Screenshot from 2019-11-13 17-05-17](https://user-images.githubusercontent.com/10957718/68748755-f4e77980-0637-11ea-99aa-8c3a39e7b41b.png)

I just want to know why not crop directly using target's bbox(w*h).
Does the context of target matter?

**Comment by yc-zc** [comment]
Short ansert: because that's what they do in SiamFC

**Comment by zyc-ai** [comment]
Since no further question is asked, I'm closing this issue for now. 
Please create a new issue should you have other questions.
