### ISSUE TITLE
如何对主干网络进行训练？

### ISSUE THREAD

**Issue by Lady-zxc** [STVIR/pysot#237]
我想要使用自定义的主干网络，该如何训练SiamRPN？
需要先对主干网络进行单独训练，得到类似项目中所提供的预训练的backbone模型，然后再训练SiamRPN吗？如果需要，应该如何训练主干网络呢？
望解答，谢谢！

**Comment by MaxLin86** [comment]
使用自定义的主干网络，可以直接拼起来一起训，也可以单独训练

**Comment by yc-zc** [comment]
> 我想要使用自定义的主干网络，该如何训练SiamRPN？
> 需要先对主干网络进行单独训练，得到类似项目中所提供的预训练的backbone模型，然后再训练SiamRPN吗？如果需要，应该如何训练主干网络呢？
> 望解答，谢谢！

我会建议你这样做，预热是很有必要的。
你可以参考论文和项目中都使用的， 预先对backbone进行五次训练。你也可以尝试其他的训练策略

**Comment by yc-zc** [comment]
由于本issue没有得到更进一步的提问，我现在将其关闭。
如有进一步问题，可以重新打开或者创建一个新的issue。
