### ISSUE TITLE
Where did you get backbone pretrained model resnet50.model in train.md?why this?

### ISSUE THREAD

**Issue by czh55** [STVIR/pysot#241]

**Comment by yc-zc** [comment]
Sorry but I am having troubles to understand your question.
You may use Chinese or other languages if you find it's easier.

**Comment by czh55** [comment]
在google网盘上传的预训练模型resnet50.model这个是自己训练的吗？或者是从哪里得到的？

**Comment by yc-zc** [comment]
> 在google网盘上传的预训练模型resnet50.model这个是自己训练的吗？或者是从哪里得到的？

论文当中有提到是怎么训练的，训练代码当中也有backbone相关的训练代码。

**Comment by yc-zc** [comment]
Since no further question is asked, I'm closing it for now.
Please reopen it or create a new issue if you have further question.

**Comment by divastar** [comment]
This code is asking for resnet50 pretraind.
    if cfg.BACKBONE.PRETRAINED:
        cur_path = os.path.dirname(os.path.realpath(__file__))
        backbone_path = os.path.join(cur_path, '../', cfg.BACKBONE.PRETRAINED)
        load_pretrain(model.backbone, backbone_path)

Should I download pretraind resnet50 from the internet and load it here?

**Comment by ZhiyuanChen** [comment]
> This code is asking for resnet50 pretraind.
> if cfg.BACKBONE.PRETRAINED:
> cur_path = os.path.dirname(os.path.realpath(**file**))
> backbone_path = os.path.join(cur_path, '../', cfg.BACKBONE.PRETRAINED)
> load_pretrain(model.backbone, backbone_path)
> 
> Should I download pretraind resnet50 from the internet and load it here?

Yes
