### ISSUE TITLE
what's different

### ISSUE THREAD

**Issue by fAnchao1** [STVIR/pysot#243]
could you tell me whta's the different between siamrpn_alex_dwxcorr_16gpu and siamrpn_alex_dwxcorr.thx

**Comment by yc-zc** [comment]
I couldn't understand your question. 
If you mean the training process, the lr_schedule would have been different given the number of GPU.

**Comment by yc-zc** [comment]
Since this issue didn't receive any response, I'm closing it for now.
Please reopen it or create a new issue if you have further question.
