### ISSUE TITLE
ImportError: No module named yacs.config

### ISSUE THREAD

**Issue by SteelMinh** [STVIR/pysot#245]
Hello,
I try to run the demo.py file (like in the introduction), but i get an "ImportError" as in the title.

Here is the whole bug report:

Traceback (most recent call last):
  File "tools/demo.py", line 14, in <module>
    from pysot.core.config import cfg
  File "/home/minh/pysot/pysot/core/config.py", line 8, in <module>
    from yacs.config import CfgNode as CN
ImportError: No module named yacs.config

**Comment by yc-zc** [comment]
> Hello,
> I try to run the demo.py file (like in the introduction), but i get an "ImportError" as in the title.
> 
> Here is the whole bug report:
> 
> Traceback (most recent call last):
> File "tools/demo.py", line 14, in
> from pysot.core.config import cfg
> File "/home/minh/pysot/pysot/core/config.py", line 8, in
> from yacs.config import CfgNode as CN
> ImportError: No module named yacs.config

Hi, I have encountered the same problem, and resolved by switching to conda environment. 

I assume this is resulted because of the version of your yacs. Which version are you using?

**Comment by yc-zc** [comment]
Since no further question is asked, I'm closing this issue for now. 
Please reopen it or create a new issue if you have further question.

**Comment by rifat-22** [comment]
Hello, is there any update regarding this? I am facing the same problem.

**Comment by lululovecode** [comment]
change your terminal sentence from "python" to "python3"
