### ISSUE TITLE
SiamMask E ?

### ISSUE THREAD

**Issue by MohamedAliRashad** [STVIR/pysot#247]
[SiamMask E](https://github.com/baoxinchen/siammask_e) repo has redirected me to here for the model weights and configuration but i can't find the model in [PySot Model ZOO](https://github.com/STVIR/pysot/blob/master/MODEL_ZOO.md), Any help please ?

**Comment by sxs11** [comment]
i think you can get them from https://github.com/STVIR/pysot/blob/master/MODEL_ZOO.md.
The link named "siammask_r50_l3" maybe what you need

**Comment by MohamedAliRashad** [comment]
@sxs11 
Don't think so

![Uploading Screenshot from 2019-11-26 15-23-36.png…]()

it explicitly says siammaske + SiamMaskE is talked about it in its paper as an improvement to SiamMask.

**Comment by MohamedAliRashad** [comment]
The issue has been solved here https://github.com/baoxinchen/siammask_e/issues/4
