### ISSUE TITLE
can you offer the training of siammask?

### ISSUE THREAD

**Issue by chenbolinstudent** [STVIR/pysot#249]
can you offer the training of siammask?
thanks

**Comment by yc-zc** [comment]
What do you mean by training of SiamMask?

**Comment by chenbolinstudent** [comment]
pysot里面没有 siammask的训练代码吗？怎么训练siammask呢？



---Original---

**Comment by chenbolinstudent** [comment]
can you offer the training code of siammask in pysot?

**Comment by yc-zc** [comment]
> can you offer the training code of siammask in pysot?

https://github.com/STVIR/pysot/blob/master/tools/train.py
