### ISSUE TITLE
SiamRPN++ only got 0.36 EAO if dropping out smoothness during testing?

### ISSUE THREAD

**Issue by kshgz** [STVIR/pysot#25]
I evaluated the official checkpoint  `siamrpn_r50_l234_dwxcorr`  on VOT2018, I found that if i drop out bounding box  smoothness ,  it only got about 0.36 EAO (fast away from 0.41 using smoothness). It shows that this `post-processing` refinement is important to boost the performance. But, why it was not mentioned at all in the paper?

**Comment by yongwuSHU** [comment]
how i drop out bounding box smoothness? thank you reply. @kshgz
