### ISSUE TITLE
Can anyone reproduce eao=0.41 with the model downloaded from Model Zoo?

### ISSUE THREAD

**Issue by JamesLearning** [STVIR/pysot#252]
I just downloaded the model siamrpn_r50_l234_dwxcorr from [PySOT Model Zoo](https://github.com/STVIR/pysot/blob/master/MODEL_ZOO.md).
Then I ran hp_search.py, on VOT2018 dataset.
But the final result is eao=0.359, which is so far from 0.415.

Can anyone reproduce eao=0.41 with the model downloaded from Model Zoo?

**Comment by JamesLearning** [comment]
Following the instruction 'Quick Start: Using PySOT' in https://github.com/STVIR/pysot/blob/master/README.md
Download models, Test tracker, Eval tracker
and finally got eao=0.373
also far from 0.415

```
------------------------------------------------------------
|Tracker Name| Accuracy | Robustness | Lost Number |  EAO  |
------------------------------------------------------------
|   model    |  0.606   |   0.253    |    54.0     | 0.373 |
------------------------------------------------------------
```

**Comment by yc-zc** [comment]
Since this issue is duplicate, I'm closing it for now.
Please reopen it or create a new issue if you have further question.

**Comment by yc-zc** [comment]
https://github.com/STVIR/pysot/issues/94
