### ISSUE TITLE
can anyone can retrain and get the result of OTB100 ?

### ISSUE THREAD

**Issue by chenbolinstudent** [STVIR/pysot#253]
can anyone can retrain and get the result of OTB100 ?
-----------------------------------------------------
|Tracker name| Success | Norm Precision | Precision |
-----------------------------------------------------
|   model    |  0.696  |     0.000      |   0.905   |
-----------------------------------------------------

**Comment by yc-zc** [comment]
Since no further question is asked, I'm closing it for now.
Please reopen it or create a new issue if you have further question.
