### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'shape'

### ISSUE THREAD

**Issue by chenbolinstudent** [STVIR/pysot#257]
AttributeError: 'NoneType' object has no attribute 'shape'
 what is the problem?
thanks

**Comment by yc-zc** [comment]
Could you provide more details on how to reproduce the Error?

**Comment by xiaqing10** [comment]
Maybe the picture is None, you should check input imgs first.

**Comment by yc-zc** [comment]
Since no further question is asked, I'm closing it for now.
Please reopen it or create a new issue if you have further question.

**Comment by ThomasBomjan** [comment]
I got same issue. Did you manage to solve it ?
