### ISSUE TITLE
为什么加载完预训练模型之后就卡住不动了？有大佬可以解答一下吗

### ISSUE THREAD

**Issue by chun-chun123** [STVIR/pysot#259]

**Comment by yc-zc** [comment]
你加载的是什么模型？内存多大显存多大怎么配置的？

**Comment by chun-chun123** [comment]
加载的是model.zoo里提供的训练好的siamRPN的模型
按照分布式跑训练的时候用三块卡就会卡住
单块卡就没问题
![image](https://user-images.githubusercontent.com/56161480/71236814-d8c3b000-233a-11ea-8b39-03ffa4d8ef19.png)

**Comment by yc-zc** [comment]
> 加载的是model.zoo里提供的训练好的siamRPN的模型
> 按照分布式跑训练的时候用三块卡就会卡住
> 单块卡就没问题
> ![image](https://user-images.githubusercontent.com/56161480/71236814-d8c3b000-233a-11ea-8b39-03ffa4d8ef19.png)

你有尝试过双卡或者四卡吗？

**Comment by chun-chun123** [comment]
我试过双卡也不行

**Comment by yc-zc** [comment]
> 我试过双卡也不行

那我觉得应该是你分布式没有配置正确……

**Comment by chun-chun123** [comment]
那请问您知道怎么配置吗？我没有对原代码做改动

**Comment by yc-zc** [comment]
> 那请问您知道怎么配置吗？我没有对原代码做改动

你的运行命令是？我记得train.md当中只提供了多节点训练的示例，实际上是不需要的。

**Comment by chun-chun123** [comment]
CUDA_VISIBLE_DEVICES=0,1,2
python -m torch.distributed.launch \
    --nproc_per_node=3 \
    --master_port=2333 \
    ../../tools/train.py --cfg config.yaml

我的命令行是用的这个，把单节点多GPU的改了一下

**Comment by chun-chun123** [comment]
感觉一旦多卡加载完模型，程序就一直再等待而没有读取数据，请问您知道为什么吗？

**Comment by yc-zc** [comment]
> 感觉一旦多卡加载完模型，程序就一直再等待而没有读取数据，请问您知道为什么吗？

感觉是因为你调用了分布式而只在单机跑导致的，试试去掉分布式的代码？

**Comment by chun-chun123** [comment]
去掉分布式代码还能多卡跑吗？

**Comment by caiyujue** [comment]
只有一块显卡，该怎么跑训练程序啊，我直接运行python  ../../tools/train.py --cfg config.yaml，报错了了，求解答呀

**Comment by chun-chun123** [comment]
> 只有一块显卡，该怎么跑训练程序啊，我直接运行python ../../tools/train.py --cfg config.yaml，报错了了，求解答呀

CUDA_VISIBLE_DEVICES=0
python -m torch.distributed.launch
--nproc_per_node=1
--master_port=2333
../../tools/train.py --cfg config.yaml

节点数改成0就行了

**Comment by caiyujue** [comment]
感谢，但还是报错诶，这是我的命令行信息，win7系统上跑的

![image](https://user-images.githubusercontent.com/52164412/71758215-fa469f00-2ed7-11ea-8f1e-b74a293ad286.png)

**Comment by chun-chun123** [comment]
> 感谢，但还是报错诶，这是我的命令行信息，win7系统上跑的
> 
> ![image](https://user-images.githubusercontent.com/52164412/71758215-fa469f00-2ed7-11ea-8f1e-b74a293ad286.png)

我是Ubuntu跑的，win7就不清楚了

**Comment by Dtappledoghuati** [comment]
您好。请问有跑通过siammask吗，一直显示config.yaml文件有问题，请问怎么解决

**Comment by zyc-ai** [comment]
> 感谢，但还是报错诶，这是我的命令行信息，win7系统上跑的
> 
> ![image](https://user-images.githubusercontent.com/52164412/71758215-fa469f00-2ed7-11ea-8f1e-b74a293ad286.png)

Windows不支持分布式训练

**Comment by zyc-ai** [comment]
由于本议题没有得到更进一步的提问，我现在将其关闭。
请创建一个新的议题如果你有其他问题。
