### ISSUE TITLE
when do you offer the training code ?

### ISSUE THREAD

**Issue by chenbolinstudent** [STVIR/pysot#26]
when do you offer the training code ?
thanks

**Comment by yuluu** [comment]
same question

**Comment by chenbolinstudent** [comment]
@lb1100   
when do you offer the training code ?

**Comment by MARMOTatZJU** [comment]
@chenbolinstudent Personally I suppose that they didn't anticipate the postpone of submission of VOT2019, thus the release of training code would be after that due.
