### ISSUE TITLE
What is "train.json" file format?

### ISSUE THREAD

**Issue by mqjinwon** [STVIR/pysot#262]
I made train.json file from vid dataset, but I'm not sure it is right.
could someone check it is the right format?

![image](https://user-images.githubusercontent.com/42585679/70884611-d0f1cc00-2019-11ea-9890-cad741123004.png)

**Comment by chun-chun123** [comment]
"a/ILSVRC2015_train_00000000": {
        "00": {
            "000000": [323, 216, 1050, 428]
             "000001": [323, 218,1052,428]
               ..........
Just like this.

**Comment by mqjinwon** [comment]
thank you!!
