### ISSUE TITLE
I can't get the results（Accuracy and EAO） in the paper

### ISSUE THREAD

**Issue by MaMingyueIT** [STVIR/pysot#264]
I used mobileV2 for test and eval and got the following results：
|Tracker Name| Accuracy | Robustness | Lost Number |  EAO  |
------------------------------------------------------------
|   model    |  0.588   |   0.239    |    51.0     | 0.406 |

So why can't I get the accuracy of 0.601?

**Comment by yc-zc** [comment]
Since this issue is duplicate, I'm closing it for now.
Please reopen it or create a new issue if you have further question.

**Comment by yc-zc** [comment]
https://github.com/STVIR/pysot/issues/94

**Comment by marghesc** [comment]
@MaMingyueIT What config file are you using for mobilenetv2 backbone?
