### ISSUE TITLE
Figure 5. Channels of depthwise correlation output in conv4

### ISSUE THREAD

**Issue by chenbolinstudent** [STVIR/pysot#268]
怎么可视化（Figure 5. Channels of depthwise correlation output in conv4）？

Channels of depthwise correlation output in conv4 在代码中是指哪一个的输出？

请问有谁知道的吗？谢谢

**Comment by yc-zc** [comment]
抱歉之前忘记回复你了
类似问题建议在网上直接搜索，比如 https://blog.csdn.net/liyaohhh/article/details/50990927
conv4即是ResNet的conv4。

**Comment by chenbolinstudent** [comment]
谢谢，请问具体在代码哪一行的输出呢？
里面说到depthwise correlation output，那是在resnet.atrous.py 还是在rpn.py的输出？
还有conv4里面的分类还是回归分支的？
resnet50 的 conv4的特征大小是31*31，而你输出的热力图看上去为什么是很大的？

**Comment by yc-zc** [comment]
> 谢谢，请问具体在代码哪一行的输出呢？
> 里面说到depthwise correlation output，那是在resnet.atrous.py 还是在rpn.py的输出？
> 还有conv4里面的分类还是回归分支的？
> resnet50 的 conv4的特征大小是31*31，而你输出的热力图看上去为什么是很大的？

depthwise correlation的代码在rpn.py当中
resnet是用作特征提取的，不涉及到分类或者回归
本文对resnet进行了修改

**Comment by yc-zc** [comment]
我有注意到你在过去的几个月当中开启了很多个issues，很高兴你能对我司的项目这样关注和认可。
但是，你的绝大多数issues，比如这个，都可以在论文和代码当中找到答案。这对我来说有些费解--我接触跟踪这个领域也不过两周。我诚恳的建议你仔细阅读论文以及代码，很多问题作者都已经回答过。

**Comment by chenbolinstudent** [comment]
谢谢您的回复，depthwise correlation的 search的输出特征大小是29*29，而论文中热力图看上去的特征大小很大，这是为什么呢？
