### ISSUE TITLE
conda create --name pysot python=3.7 conda activate pysot

### ISSUE THREAD

**Issue by chenbolinstudent** [STVIR/pysot#27]
why I run it and false
conda create --name pysot python=3.7
conda activate pysot

CondaHTTPError: HTTP 404 NOT FOUND for url <https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge/noarch/repodata.json>
Elapsed: 00:09.424438

The remote server could not find the noarch directory for the
requested channel with url: https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge

As of conda 4.3, a valid channel must contain a `noarch/repodata.json` and
associated `noarch/repodata.json.bz2` file, even if `noarch/repodata.json` is
empty. please request that the channel administrator create
`noarch/repodata.json` and associated `noarch/repodata.json.bz2` files.
$ mkdir noarch
$ echo '{}' > noarch/repodata.json
$ bzip2 -k noarch/repodata.json

You will need to adjust your conda configuration to proceed.
Use `conda config --show channels` to view your configuration's current state.
Further configuration help can be found at <https://conda.io/docs/config.html>.

**Comment by linkinpark213** [comment]
The Tsinghua Anaconda mirror is closed. You can swap for SJTU mirror by running:
```
conda config --add channels https://mirrors.sjtug.sjtu.edu.cn/anaconda/pkgs/free/
```

**Comment by chenbolinstudent** [comment]
Collecting package metadata: failed

UnavailableInvalidChannel: The channel is not accessible or is invalid.
  channel name: anaconda/cloud/conda-forge
  channel url: https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
  error code: 404

You will need to adjust your conda configuration to proceed.
Use `conda config --show channels` to view your configuration's current state,
and use `conda config --show-sources` to view config file locations.

**Comment by linkinpark213** [comment]
Oh, I forgot that you also need to delete the Tsinghua channel in your configurations. But I suppose you should be able to access anaconda packages already.
```
conda config --remove channels 'https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/' 
```
By the way, can you post the returned message of `conda config --show channels`?

**Comment by chenbolinstudent** [comment]
yes

and now :

channels:
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/pytorch/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/menpo/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/bioconda/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/msys2/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/
  - defaults
public@n609-169:~$ conda create --name pysot python=3.6
Solving environment: failed

CondaHTTPError: HTTP 404 NOT FOUND for url <https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge/noarch/repodata.json>
Elapsed: 00:26.773396

The remote server could not find the noarch directory for the
requested channel with url: https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge

As of conda 4.3, a valid channel must contain a `noarch/repodata.json` and
associated `noarch/repodata.json.bz2` file, even if `noarch/repodata.json` is
empty. please request that the channel administrator create
`noarch/repodata.json` and associated `noarch/repodata.json.bz2` files.
$ mkdir noarch
$ echo '{}' > noarch/repodata.json
$ bzip2 -k noarch/repodata.json

You will need to adjust your conda configuration to proceed.
Use `conda config --show channels` to view your configuration's current state.
Further configuration help can be found at <https://conda.io/docs/config.html>.

**Comment by chenbolinstudent** [comment]
and I can run conda config --add channels https://mirrors.sjtug.sjtu.edu.cn/anaconda/pkgs/free/
before 
but I cannot run it now

**Comment by chenbolinstudent** [comment]
yes 
public@root1-MS-7A94:~$ conda config --show channels
channels:
  - https://mirrors.sjtug.sjtu.edu.cn/anaconda/pkgs/free/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/pytorch/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/menpo/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/bioconda/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/msys2/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main/
public@root1-MS-7A94:~$ 
public@root1-MS-7A94:~$ conda create --name pysot python=3.6
Collecting package metadata: failed

UnavailableInvalidChannel: The channel is not accessible or is invalid.
  channel name: anaconda/cloud/conda-forge
  channel url: https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
  error code: 404

You will need to adjust your conda configuration to proceed.
Use `conda config --show channels` to view your configuration's current state,
and use `conda config --show-sources` to view config file locations.

**Comment by linkinpark213** [comment]
There are 6 more channels from Tsinghua's mirror. You can remove them all by:
```
conda config --remove channels https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/pytorch/
conda config --remove channels https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/menpo/
conda config --remove channels https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/bioconda/
conda config --remove channels https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge/
conda config --remove channels https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/msys2/
conda config --remove channels https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main/
```
or you can delete the file `~/.condarc` and try `conda create --name pysot python=3.6` again.

**Comment by chenbolinstudent** [comment]
thanks , it is ok

**Comment by chenbolinstudent** [comment]
is it ok for cuda9.1or 9.2   python2.7   torch4.0 ?

**Comment by linkinpark213** [comment]
I don't think Python 2.7 is OK. And the PyTorch version should be 0.4.1 or higher.

**Comment by chenbolinstudent** [comment]
when use Python 2.7 , where need to change?

**Comment by lb1100** [comment]
Python 2 hasn't been tested. And it will not be supported by community in recent few months. We won't provide support for Python2.7 either. So better to try Python 3.

**Comment by chenbolinstudent** [comment]
(base) cbl@N606-TITAN32:~$ conda create --name pysot python=3.7
WARNING: The conda.compat module is deprecated and will be removed in a future release.
Collecting package metadata: - ERROR urllib3.connection:_match_hostname(378): Certificate did not match expected hostname: mirrors.sjtug.sjtu.edu.cn. Certificate: {'subject': ((('commonName', 'drcom.szu.edu.cn'),),), 'subjectAltName': [('DNS', 'drcom.szu.edu.cn')]}                                                                                                                                 \ ERROR urllib3.connection:_match_hostname(378): Certificate did not match expected hostname: mirrors.sjtug.sjtu.edu.cn. Certificate: {'subject': ((('commonName', 'drcom.szu.edu.cn'),),), 'subjectAltName': [('DNS', 'drcom.szu.edu.cn')]}                            | ERROR urllib3.connection:_match_hostname(378): Certificate did not match expected hostname: mirrors.sjtug.sjtu.edu.cn. Certificate: {'subject': ((('commonName', 'drcom.szu.edu.cn'),),), 'subjectAltName': [('DNS', 'drcom.szu.edu.cn')]}                            / ERROR urllib3.connection:_match_hostname(378): Certificate did not match expected hostname: mirrors.sjtug.sjtu.edu.cn. Certificate: {'subject': ((('commonName', 'drcom.szu.edu.cn'),),), 'subjectAltName': [('DNS', 'drcom.szu.edu.cn')]}                            failed

CondaHTTPError: HTTP 000 CONNECTION FAILED for url <https://mirrors.sjtug.sjtu.edu.cn/anaconda/pkgs/free/noarch/repodata.json>
Elapsed: -

An HTTP error occurred when trying to retrieve this URL.
HTTP errors are often intermittent, and a simple retry will get you on your way.
SSLError(MaxRetryError('HTTPSConnectionPool(host=\'mirrors.sjtug.sjtu.edu.cn\', port=443): Max retries exceeded with url: /anaconda/pkgs/free/noarch/repodata.json (Caused by SSLError(SSLCertVerificationError("hostname \'mirrors.sjtug.sjtu.edu.cn\' doesn\'t match \'drcom.szu.edu.cn\'")))'))


what is the matter?
