### ISSUE TITLE
why the instance_size is 287 while it doesn't show in the paper?

### ISSUE THREAD

**Issue by chun-chun123** [STVIR/pysot#271]

**Comment by yc-zc** [comment]
By instance_size, what do you actually mean?

**Comment by chun-chun123** [comment]
在16GPU训练SiamRPN文件夹下的config.yaml中，track时搜索区域instance_size=287，但是论文中并未提及这个数

**Comment by lb1100** [comment]
这个是在vot比赛的时候修改的，实际上只是个测试的超参数，和window_influence，lr之类的一样。这个在之前放出的测试代码中就已经是修改过的了。https://github.com/foolwood/DaSiamRPN/blob/master/code/run_SiamRPN.py#L47

**Comment by chun-chun123** [comment]
> 这个是在vot比赛的时候修改的，实际上只是个测试的超参数，和window_influence，lr之类的一样。这个在之前放出的测试代码中就已经是修改过的了。https://github.com/foolwood/DaSiamRPN/blob/master/code/run_SiamRPN.py#L47

好的，非常感谢
