### ISSUE TITLE
Question about  pre-trained backbone network

### ISSUE THREAD

**Issue by zxb-caffe** [STVIR/pysot#272]
Hello, 
can you provide Baidu pan links to the pre-trained backbone network?
能不能提供预训练骨干网的百度网盘链接？

**Comment by VegetableChlcken** [comment]
> Hello,
> can you provide Baidu pan links to the pre-trained backbone network?
> 能不能提供预训练骨干网的百度网盘链接？

你好,骨干网络是因为源代码没提供训练方法所以训练不了吗,我每当开始训练骨干网络的时候代码就会报错说backbone没parameters这个属性.
