### ISSUE TITLE
我在win7系统上跑的程序，可以运行demo和test，但训练就没办法了

### ISSUE THREAD

**Issue by caiyujue** [STVIR/pysot#274]

**Comment by caiyujue** [comment]
![image](https://user-images.githubusercontent.com/52164412/71762813-30ebdc00-2f0f-11ea-804d-9e612570c352.png)

**Comment by caiyujue** [comment]
这是我的报错信息，我去torch/distributed文件夹下找了init.py文件，是这样的
def is_available():
    return (hasattr(torch._C, "_c10d_init") and hasattr(torch._C, "_rpc_init")
            and hasattr(torch._C, "_dist_autograd_init"))
if is_available():
    from .distributed_c10d import *  # noqa: F401
    # Variables prefixed with underscore are not auto imported
    # See the comment in `distributed_c10d.py` above `_backend` on why we expose
    # this.
    from .distributed_c10d import _backend  # noqa: F401
is.available()返回的一直是false，所以没有from .distributed_c10d import *，然后就会报no attributed ‘init_process_qroup'这个错’

**Comment by caiyujue** [comment]
这个该如何解决啊，还是说程序就不支持在windows7系统上进行训练

**Comment by yc-zc** [comment]
> 这个该如何解决啊，还是说程序就不支持在windows7系统上进行训练

Windows不支持torch.distributed，请不要分布式训练。

**Comment by caiyujue** [comment]
> > 这个该如何解决啊，还是说程序就不支持在windows7系统上进行训练
> 
> Windows不支持torch.distributed，请不要分布式训练。

那我该如何训练呢，我试过直接python ../../tools/train.py --cfg config.yaml，也不行

**Comment by caiyujue** [comment]
还是说直接用ubutun系统跑会更方便

**Comment by caiyujue** [comment]
求解答

**Comment by yc-zc** [comment]
> > > 这个该如何解决啊，还是说程序就不支持在windows7系统上进行训练
> > 
> > 
> > Windows不支持torch.distributed，请不要分布式训练。
> 
> 那我该如何训练呢，我试过直接python ../../tools/train.py --cfg config.yaml，也不行

把分布式代码去掉

**Comment by caiyujue** [comment]
感谢，我还是投入Ubutun 的怀抱吧，成功后过来返图

**Comment by caiyujue** [comment]
应该算是能跑起来了，但训练数据还在下所以暂时只能到这，全是大文件下到猴年马月去了
/home/caiyujue/图片/2020-01-09 15-44-14屏幕截图.png

**Comment by caiyujue** [comment]
终于下好了一个训练数据集coco，跑下来是这样的，就是有点慢，显卡太渣了
![2020-01-10 10-33-25屏幕截图](https://user-images.githubusercontent.com/52164412/72121071-e5b14d80-3394-11ea-9207-7e9ae83210ba.png)

**Comment by yc-zc** [comment]
由于本issue没有得到更进一步的提问，我现在将其关闭。
如有新的问题，请重新打开它或者创建一个新的issue。

**Comment by job333** [comment]
> > > > 这个该如何解决啊，还是说程序就不支持在windows7系统上进行训练
> > > 
> > > 
> > > Windows不支持torch.distributed，请不要分布式训练。
> > 
> > 
> > 那我该如何训练呢，我试过直接python ../../tools/train.py --cfg config.yaml，也不行
> 
> 把分布式代码去掉

分布式代码该怎么去掉呢
