### ISSUE TITLE
VOT Testing AssertionError: 

### ISSUE THREAD

**Issue by ThomasBomjan** [STVIR/pysot#277]
I created VOT2018 folder and put VOT2018.json file inside, To do a quick check I run 

>> python -u ../../tools/test.py \
        --snapshot snapshot/checkpoint_e5.pth \
	--config config.yaml \	--dataset VOT2018 2>&1 | tee logs/test_dataset.log

And got this error. 

>>AssertionError: /home/thomas/pysot/tools/../testing_dataset/VOT2018/ants1/color/00000001.jpg
loading VOT2018:   0%|                                                    | 0/60 [00:00<?, ?it/s, ants1]

What is problem? Do I need to download VOT2018 (images) datset and put it inside VOT2018 folder?  I found out pysot-toolkit, but did not get it properly,  how to download VOT2018 datset?

**Comment by yc-zc** [comment]
Based on the provided informations, I would say your are right. 
Please refer to the VOT toolkit for dataset issues. https://github.com/votchallenge/vot-toolkit

**Comment by ZXJxx** [comment]
i met the same issue,would you please tell me how to solve it?Thank you very much!
