### ISSUE TITLE
MobilenetV2 config file. Can you share the mobilenetv2 training config.

### ISSUE THREAD

**Issue by SteveTsg** [STVIR/pysot#279]
Which layer should I train in backbone net？
In pysot/core/config，only resnet50 backbone train layer provided. For Mobilenetv2, which layer should I train? Thank you.

**Comment by yc-zc** [comment]
It mainly depends on how you modified the backbone

**Comment by SteveTsg** [comment]
Right, I used the oringal mobilenetv2 to train as the experiments/siamrpn_mobilev2_l234_dwxcorr/config.yaml said.
But this config do not have a backbone layer train recommendation, it will merged with pysot/core/config.yaml, that means the the backbone train layer will be the same with resnet50, right? My question is ： Is this really okay? Thank you

**Comment by anchor666** [comment]
Have you tried to train with mobilenet? After merging with pysot/core/config.py and changing the training layer of backbone, I got poor results

**Comment by SteveTsg** [comment]
> Have you tried to train with mobilenet? After merging with pysot/core/config.py and changing the training layer of backbone, I got poor results

Yes，I trained it. I got a not bad results. I use the defualt config in siamrpn_mobilev2_l234_dwxcorr

**Comment by DjangoChaogh** [comment]
> > Have you tried to train with mobilenet? After merging with pysot/core/config.py and changing the training layer of backbone, I got poor results
> 
> Yes，I trained it. I got a not bad results. I use the defualt config in siamrpn_mobilev2_l234_dwxcorr

where you get the backbone of mobilenet, I download from website, however, it seems mismatching the model used in SiamRPN++. Thank you

**Comment by SteveTsg** [comment]
> > > Have you tried to train with mobilenet? After merging with pysot/core/config.py and changing the training layer of backbone, I got poor results
> > 
> > 
> > Yes，I trained it. I got a not bad results. I use the defualt config in siamrpn_mobilev2_l234_dwxcorr
> 
> where you get the backbone of mobilenet, I download from website, however, it seems mismatching the model used in SiamRPN++. Thank you

Modify it，and I also tried pretrain my own mobilenetv2 in imagenet

**Comment by zyc-ai** [comment]
> Right, I used the oringal mobilenetv2 to train as the experiments/siamrpn_mobilev2_l234_dwxcorr/config.yaml said.
> But this config do not have a backbone layer train recommendation, it will merged with pysot/core/config.yaml, that means the the backbone train layer will be the same with resnet50, right? My question is ： Is this really okay? Thank you

It's hard to tell, you have to try it yourself

**Comment by haishibei** [comment]
> > Have you tried to train with mobilenet? After merging with pysot/core/config.py and changing the training layer of backbone, I got poor results
> 
> Yes，I trained it. I got a not bad results. I use the defualt config in siamrpn_mobilev2_l234_dwxcorr



> > Have you tried to train with mobilenet? After merging with pysot/core/config.py and changing the training layer of backbone, I got poor results
> 
> Yes，I trained it. I got a not bad results. I use the defualt config in siamrpn_mobilev2_l234_dwxcorr

Can you share us with the result on your own pretrained  MobileNet_v2?

**Comment by haishibei** [comment]
> 
> 
> > > > Have you tried to train with mobilenet? After merging with pysot/core/config.py and changing the training layer of backbone, I got poor results
> > > 
> > > 
> > > Yes，I trained it. I got a not bad results. I use the defualt config in siamrpn_mobilev2_l234_dwxcorr
> > 
> > 
> > where you get the backbone of mobilenet, I download from website, however, it seems mismatching the model used in SiamRPN++. Thank you
> 
> Modify it，and I also tried pretrain my own mobilenetv2 in imagenet

and I have another question: how long did you take to train your own mobilenet_v2 ？ and what is your environment(eg: what type of your GPU)?

**Comment by SteveTsg** [comment]
> 您可以在自己训练有素的MobileNet_v2上与我们分享结果吗？

the EOA of VOT2018 is 0.275

>我还有一个问题：您花了多长时间训练自己的mobilenet_v2？您的环境是什么（例如：哪种类型的GPU）？

my server have 8 2080ti; I dont remember how long it spent

**Comment by haishibei** [comment]
@SteveTsg ，thanks your reply. I have some question to consult you, and can I add your wechat， the number of my wechat is "jzb12390"

**Comment by zyc-ai** [comment]
Close since the issue is resolved.
Please create a new issue should you have other questions

**Comment by EEEEEREN** [comment]
> > > > Have you tried to train with mobilenet? After merging with pysot/core/config.py and changing the training layer of backbone, I got poor results
> > > 
> > > 
> > > Yes，I trained it. I got a not bad results. I use the defualt config in siamrpn_mobilev2_l234_dwxcorr
> > 
> > 
> > where you get the backbone of mobilenet, I download from website, however, it seems mismatching the model used in SiamRPN++. Thank you
> 
> Modify it，and I also tried pretrain my own mobilenetv2 in imagenet



> > Have you tried to train with mobilenet? After merging with pysot/core/config.py and changing the training layer of backbone, I got poor results
> 
> Yes，I trained it. I got a not bad results. I use the defualt config in siamrpn_mobilev2_l234_dwxcorr

could u tell me where did u get the mobilenetv2?  in the paper of  MobileNetv2 ?

**Comment by xyl-507** [comment]
@SteveTsg Hi！
Can you share us your **pretrained mobilenet V2**？Our lab does not have the conditions for pre-training. It takes **a month** to train on my own. Thank you very much！！
