### ISSUE TITLE
Inference on New Dataset

### ISSUE THREAD

**Issue by arjung128** [STVIR/pysot#281]
Can these trackers be used to do inference (not evaluation as I don't have the labels) on a new dataset?

The README.md states: "If you want to test tracker on new dataset, please refer to pysot-toolkit to setting testing_dataset." But pysot-toolkit seems to be for evaluation on a new tracker, not a new dataset... Isn't that right? Or have I misunderstood?

Thanks!

**Comment by yc-zc** [comment]
Of course it can. 

The README.md states: "If you want to **TEST** tracker on new dataset". It is about test, not inference.

**Comment by zyc-ai** [comment]
Since no further question is asked, I'm closing it for now.
