### ISSUE TITLE
'function' object has no attribute 'parameters' when I start to train the backbone in the 10 epoch

### ISSUE THREAD

**Issue by VegetableChlcken** [STVIR/pysot#283]
start training backbone.
Traceback (most recent call last):
  File "../../tools/train.py", line 322, in <module>
    main()
  File "../../tools/train.py", line 317, in main
    train(train_loader, dist_model, optimizer, lr_scheduler, tb_writer)
  File "../../tools/train.py", line 194, in train
    optimizer, lr_scheduler = build_opt_lr(model.module, epoch)
  File "../../tools/train.py", line 77, in build_opt_lr
    for param in getattr(model.backbone, layer).parameters():
AttributeError: 'function' object has no attribute 'parameters'

How can I deal with it?

**Comment by yc-zc** [comment]
Try change getattr(model.backbone, layer).parameters() to getattr(model.backbone(), layer).parameters()

**Comment by zyc-ai** [comment]
What backbone are you using?

**Comment by VegetableChlcken** [comment]
resnet50



At 2020-05-14 17:24:59, "Zhiyuan Chen" <notifications@github.com> wrote:

What backbone are you using?

**Comment by zyc-ai** [comment]
> resnet50 At 2020-05-14 17:24:59, "Zhiyuan Chen" <notifications@github.com> wrote: What backbone are you using? — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.

Sorry for this extremely late reply. `getattr(model.backbone, layer)` should have returned a backbone (nn.module) object, but what you got is a function.

**Comment by shupingbaba** [comment]
I have encountered the same problem. Could you please tell me the specific solution?

**Comment by ZhiyuanChen** [comment]
> I have encountered the same problem. Could you please tell me the specific solution?

Can you try `getattr(model.backbone, layer)()`instead?

**Comment by shupingbaba** [comment]
Thank you very much for your answer, I have solved this problem.
