### ISSUE TITLE
Training SiamRPN with lasot

### ISSUE THREAD

**Issue by ljh9999** [STVIR/pysot#287]
When I changed the dataset to Lasot for training, I encountered this problem:
TypeError: conv2d (): argument 'input' (position 1) must be Tensor, not list.
Is there something wrong with me? thank you for your answer.

**Comment by zyc-ai** [comment]
So maybe try convert it to a Tensor?

**Comment by zyc-ai** [comment]
Since no further question is asked, I'm closing this issue for now. 
Please create a new issue should you have other questions.
