### ISSUE TITLE
Epoch and progress 

### ISSUE THREAD

**Issue by ThomasBomjan** [STVIR/pysot#288]
[2020-01-25 20:15:58,362-rk0-train.py#249] Epoch: [1][820/**21428]** lr: 0.001000
	batch_time: 2.702518 (2.461709)	data_time: 0.000050 (0.000049)
	cls_loss: 0.149893 (0.150506)	loc_loss: 0.154537 (0.176229)
	total_loss: 0.335337 (0.361980)	
[2020-01-25 20:15:58,363-rk0-log_helper.py#105] Progress: 820 / **428560** [0%], Speed: 2.462 s/iter, ETA 12:04:29 (D:H:

I am doing training with coco data set but I am only using 1500 images, in that case training should be quite fast  How to change those **21428** and **428560** number. I check **config.yaml** but did not get it.

**Comment by ny222333** [comment]
How long did it take you when trained coco,I am training while it is so slow.

[2020-03-04 21:35:27,359-rk0-log_helper.py#106] Progress: 820 / 187500 [0%], Speed: 0.936 s/iter, ETA 2:00:33 (D:H:M)

**Comment by ThomasBomjan** [comment]
It might take more than 1.5 days depends. If you are doing it just for testing then go to pysot config and change the vides per epoch.

**Comment by ny222333** [comment]
6%|█▊                            | 14413/234375 [9:55:18<145:29:35,  2.38s/it]tensor(0.2907, device='cuda:0', grad_fn=<MeanBackward0>)
one epoch took 1.5 days, or the total time took 1.5 days?my one epoch takes about 145 hours.

**Comment by ny222333** [comment]
sorry!I forgot to change the vides per epoch.Now it's OK.thanks.

**Comment by ny222333** [comment]
for idx, data in enumerate(train_loader):
        if epoch != idx // num_per_epoch + start_epoch:
            epoch = idx // num_per_epoch + start_epoch       

it means the whole datasets trained only once ?

**Comment by jiayuan-running** [comment]
I have the same problem,can you tell me what your changes in your config.py or config.yaml?

**Comment by Singapore-mor** [comment]
> for idx, data in enumerate(train_loader):
> if epoch != idx // num_per_epoch + start_epoch:
> epoch = idx // num_per_epoch + start_epoch
> 
> it means the whole datasets trained only once ?

I have the same question, do you figure it out?
