### ISSUE TITLE
/home/public/anaconda3/bin/python -u ../../tools/test.py --snapshot model.pth --dataset VOT2018 --config config.yaml

### ISSUE THREAD

**Issue by chenbolinstudent** [STVIR/pysot#29]
/home/public/anaconda3/bin/python -u ../../tools/test.py --snapshot model.pth --dataset VOT2018 --config config.yaml

but:ModuleNotFoundError: No module named 'pysot'

**Comment by HugoFeng** [comment]
you may need to export PYTHONPATH  as mentioned in environment setup section

**Comment by chenbolinstudent** [comment]
ok,but

self.img_names[0]= /home/cbl/PycharmProjects/pysot-master/testing_dataset/VOT2018/ants1/color/00000001.jpg
loading VOT2018:   0%|                                                | 0/60 [00:00<?, ?it/s, ants1]Traceback (most recent call last):
  File "/home/cbl/PycharmProjects/pysot-master/tools/test.py", line 221, in <module>
    main()
  File "/home/cbl/PycharmProjects/pysot-master/tools/test.py", line 56, in main
    load_img=False)
  File "/home/cbl/PycharmProjects/pysot-master/toolkit/datasets/__init__.py", line 32, in create_dataset
    dataset = VOTDataset(**kwargs)
  File "/home/cbl/PycharmProjects/pysot-master/toolkit/datasets/vot.py", line 119, in __init__
    load_img=load_img)
  File "/home/cbl/PycharmProjects/pysot-master/toolkit/datasets/vot.py", line 31, in __init__
    init_rect, img_names, gt_rect, None, load_img)
  File "/home/cbl/PycharmProjects/pysot-master/toolkit/datasets/video.py", line 29, in __init__
    assert img is not None, self.img_names[0]
AssertionError: /home/cbl/PycharmProjects/pysot-master/testing_dataset/VOT2018/ants1/color/00000001.jpg

what is the matter?

**Comment by chenbolinstudent** [comment]
@HugoFeng

**Comment by lb1100** [comment]
Please check whether `/home/cbl/PycharmProjects/pysot-master/testing_dataset/VOT2018/ants1/color/00000001.jpg` exists.

**Comment by chenbolinstudent** [comment]
/home/cbl/PycharmProjects/pysot-master/testing_dataset/VOT2018/ants1/color/00000001.jpg is not exit.
how I set the  /home/cbl/PycharmProjects/pysot-master/testing_dataset/VOT2018/?
the code cannot produce the  /home/cbl/PycharmProjects/pysot-master/testing_dataset/VOT2018/ants1/color/00000001.jpg?

**Comment by chenbolinstudent** [comment]
@lb1100

**Comment by StrangerZhang** [comment]
Please refer to [Download testing datasets](https://github.com/STVIR/pysot#download-testing-datasets)

**Comment by chenbolinstudent** [comment]
@ StrangerZhang

can you say the detail of it ,I have download it
