### ISSUE TITLE
The problem of SiamMask training

### ISSUE THREAD

**Issue by handworker** [STVIR/pysot#290]
Hi, when I try to train SiamMask, there is an output error: 
    File "train_pysot.py", line 106, in build_opt_lr
    'lr': cfg.TRAIN.LR.BASE_LR}]
  File "/home/wqq/anaconda3/envs/pysot/lib/python3.7/site-packages/yacs/config.py", line 141, in __getattr__
    raise AttributeError(name)
AttributeError: BASE_LR
It seems that there is something wrong in the config.yaml file in experiments/siammask_r50_l3. Any suggestions? Thanks.

**Comment by zyc-ai** [comment]
It seems some of the config files are having problems. 
Please use the properly configured one for now like [this](https://github.com/STVIR/pysot/blob/master/experiments/siamrpn_r50_l234_dwxcorr_8gpu/config.yaml)

**Comment by handworker** [comment]
> It seems some of the config files are having problems.
> Please use the properly configured one for now like [this](https://github.com/STVIR/pysot/blob/master/experiments/siamrpn_r50_l234_dwxcorr_8gpu/config.yaml)
OK, Thanks.

**Comment by Dtappledoghuati** [comment]
Hello, I encountered the same problem as you when training siammask. How do you solve it? Thank you!

**Comment by way790110** [comment]
same problem,How do you solve it?

**Comment by Dtappledoghuati** [comment]
> It seems some of the config files are having problems.
> Please use the properly configured one for now like [this](https://github.com/STVIR/pysot/blob/master/experiments/siamrpn_r50_l234_dwxcorr_8gpu/config.yaml)

Still unresolved, can you provide further ideas

**Comment by way790110** [comment]
https://github.com/STVIR/pysot/blob/7835f640aa9dcc2beffb2e13e9318c6c3dbc6af4/tools/train.py#L106
try delete "LR."

**Comment by Dtappledoghuati** [comment]
这个问题我已经解决了，但还是会有错误，就是矩阵维度，
RuntimeError: Given groups=1, weight of size [256, 1024, 1, 1], expected input[28, 2048, 15, 15] to have 1024 channels, but got 2048 channels instead
将维度改正后，又出现
TypeError: unsupported operand type(s) for *: 'int' and 'NoneType'
我不会解决，所以放弃了

**Comment by zyc-ai** [comment]
> 这个问题我已经解决了，但还是会有错误，就是矩阵维度，
> RuntimeError: Given groups=1, weight of size [256, 1024, 1, 1], expected input[28, 2048, 15, 15] to have 1024 channels, but got 2048 channels instead
> 将维度改正后，又出现
> TypeError: unsupported operand type(s) for *: 'int' and 'NoneType'
> 我不会解决，所以放弃了

None一般是因为没读到图片

**Comment by zyc-ai** [comment]
由于本议题没有得到更进一步的提问，我现在将其关闭。
请创建一个新的议题如果你有其他问题。

**Comment by haishibei** [comment]
> 
> 
> https://github.com/STVIR/pysot/blob/7835f640aa9dcc2beffb2e13e9318c6c3dbc6af4/tools/train.py#L106
> 
> try delete "LR."

sorry to bother you , i want to know whether  you have trained successfully?

**Comment by haishibei** [comment]
> 
> 
> 这个问题我已经解决了，但还是会有错误，就是矩阵维度，
> RuntimeError: Given groups=1, weight of size [256, 1024, 1, 1], expected input[28, 2048, 15, 15] to have 1024 channels, but got 2048 channels instead
> 将维度改正后，又出现
> TypeError: unsupported operand type(s) for *: 'int' and 'NoneType'
> 我不会解决，所以放弃了

do you succeed?
