### ISSUE TITLE
The problem of evaluation

### ISSUE THREAD

**Issue by zhdbw1022** [STVIR/pysot#291]
我在运行test.py没有什么问题，但是在跑评估运行到eval success的时候报错了:
multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "E:\Anaconda3\envs\pysot\lib\multiprocessing\pool.py", line 121, in worker
    result = (True, func(*args, **kwds))
  File "E:\pysot\toolkit\evaluation\ope_benchmark.py", line 50, in eval_success
    success_ret_[video.name] = success_overlap(gt_traj, tracker_traj, n_frame)
  File "E:\pysot\toolkit\utils\statistics.py", line 105, in success_overlap
    iou[mask] = overlap_ratio(gt_bb[mask], result_bb[mask])
IndexError: too many indices for array
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "E:/pysot/tools/eval.py", line 146, in <module>
    main()
  File "E:/pysot/tools/eval.py", line 52, in main
    trackers), desc='eval success', total=len(trackers), ncols=100):
  File "E:\Anaconda3\envs\pysot\lib\site-packages\tqdm\std.py", line 1107, in __iter__
    for obj in iterable:
  File "E:\Anaconda3\envs\pysot\lib\multiprocessing\pool.py", line 748, in next
    raise value
IndexError: too many indices for array

请问这是pytorch的版本问题嘛？我的pytorch版本是0.4.1 ，cuda8

**Comment by LIANGKE23** [comment]
我也遇到了同样的问题

**Comment by boy-new-2019** [comment]
同问，是硬件问题还是啥吗？

**Comment by boy-new-2019** [comment]
> 我在运行test.py没有什么问题，但是在跑评估运行到eval success的时候报错了:
> multiprocessing.pool.RemoteTraceback:
> """
> Traceback (most recent call last):
> File "E:\Anaconda3\envs\pysot\lib\multiprocessing\pool.py", line 121, in worker
> result = (True, func(*args, **kwds))
> File "E:\pysot\toolkit\evaluation\ope_benchmark.py", line 50, in eval_success
> success_ret_[video.name] = success_overlap(gt_traj, tracker_traj, n_frame)
> File "E:\pysot\toolkit\utils\statistics.py", line 105, in success_overlap
> iou[mask] = overlap_ratio(gt_bb[mask], result_bb[mask])
> IndexError: too many indices for array
> """
> 
> The above exception was the direct cause of the following exception:
> 
> Traceback (most recent call last):
> File "E:/pysot/tools/eval.py", line 146, in 
> main()
> File "E:/pysot/tools/eval.py", line 52, in main
> trackers), desc='eval success', total=len(trackers), ncols=100):
> File "E:\Anaconda3\envs\pysot\lib\site-packages\tqdm\std.py", line 1107, in **iter**
> for obj in iterable:
> File "E:\Anaconda3\envs\pysot\lib\multiprocessing\pool.py", line 748, in next
> raise value
> IndexError: too many indices for array
> 
> 请问这是pytorch的版本问题嘛？我的pytorch版本是0.4.1 ，cuda8

请问解决了吗

**Comment by zhdbw1022** [comment]
好像是路径只适用于linux系统，我之前用win10跑不通，换linux就可以。

**Comment by zhdbw1022** [comment]
> > 我在运行test.py没有什么问题，但是在跑评估运行到eval success的时候报错了:
> > multiprocessing.pool.RemoteTraceback:
> > """
> > Traceback (most recent call last):
> > File "E:\Anaconda3\envs\pysot\lib\multiprocessing\pool.py", line 121, in worker
> > result = (True, func(*args, **kwds))
> > File "E:\pysot\toolkit\evaluation\ope_benchmark.py", line 50, in eval_success
> > success_ret_[video.name] = success_overlap(gt_traj, tracker_traj, n_frame)
> > File "E:\pysot\toolkit\utils\statistics.py", line 105, in success_overlap
> > iou[mask] = overlap_ratio(gt_bb[mask], result_bb[mask])
> > IndexError: too many indices for array
> > """
> > The above exception was the direct cause of the following exception:
> > Traceback (most recent call last):
> > File "E:/pysot/tools/eval.py", line 146, in
> > main()
> > File "E:/pysot/tools/eval.py", line 52, in main
> > trackers), desc='eval success', total=len(trackers), ncols=100):
> > File "E:\Anaconda3\envs\pysot\lib\site-packages\tqdm\std.py", line 1107, in **iter**
> > for obj in iterable:
> > File "E:\Anaconda3\envs\pysot\lib\multiprocessing\pool.py", line 748, in next
> > raise value
> > IndexError: too many indices for array
> > 请问这是pytorch的版本问题嘛？我的pytorch版本是0.4.1 ，cuda8
> 
> 请问解决了吗

好像是路径只适用于linux系统，我之前用win10跑不通，换linux就可以。

**Comment by boy-new-2019** [comment]
> > > 我在运行test.py没有什么问题，但是在跑评估运行到eval success的时候报错了:
> > > multiprocessing.pool.RemoteTraceback:
> > > """
> > > Traceback (most recent call last):
> > > File "E:\Anaconda3\envs\pysot\lib\multiprocessing\pool.py", line 121, in worker
> > > result = (True, func(*args, **kwds))
> > > File "E:\pysot\toolkit\evaluation\ope_benchmark.py", line 50, in eval_success
> > > success_ret_[video.name] = success_overlap(gt_traj, tracker_traj, n_frame)
> > > File "E:\pysot\toolkit\utils\statistics.py", line 105, in success_overlap
> > > iou[mask] = overlap_ratio(gt_bb[mask], result_bb[mask])
> > > IndexError: too many indices for array
> > > """
> > > The above exception was the direct cause of the following exception:
> > > Traceback (most recent call last):
> > > File "E:/pysot/tools/eval.py", line 146, in
> > > main()
> > > File "E:/pysot/tools/eval.py", line 52, in main
> > > trackers), desc='eval success', total=len(trackers), ncols=100):
> > > File "E:\Anaconda3\envs\pysot\lib\site-packages\tqdm\std.py", line 1107, in **iter**
> > > for obj in iterable:
> > > File "E:\Anaconda3\envs\pysot\lib\multiprocessing\pool.py", line 748, in next
> > > raise value
> > > IndexError: too many indices for array
> > > 请问这是pytorch的版本问题嘛？我的pytorch版本是0.4.1 ，cuda8
> > 
> > 
> > 请问解决了吗
> 
> 好像是路径只适用于linux系统，我之前用win10跑不通，换linux就可以。

额。。。好吧，谢谢

**Comment by byq817** [comment]
我也遇到了这个问题,我是ubuntu系统,请问有人解决了吗

**Comment by zyc-ai** [comment]
https://github.com/STVIR/pysot/issues/292

**Comment by Cassiel829** [comment]
@zhdbw1022 在windows下要把trackers = [x.split('/')[-1] for x in trackers]替换成trackers = [x.split('//')[-1] for x in trackers]

**Comment by zyc-ai** [comment]
> @zhdbw1022 在windows下要把trackers = [x.split('/')[-1] for x in trackers]替换成trackers = [x.split('//')[-1] for x in trackers]

这个错误已经修复了
