### ISSUE TITLE
IndexError: too many indices for array, and how to solve it

### ISSUE THREAD

**Issue by LIANGKE23** [STVIR/pysot#292]
When I eval, I find   

eval success:   0%|                                                         | 0/100 [00:00<?, ?it/s]./results\OTB100\results\OTB100\model\Basketball.txt\basketball.txt
./results\OTB100\results\OTB100\model\Biker.txt\basketball.txt
./results\OTB100\results\OTB100\model\Bird1.txt\basketball.txt
multiprocessing.pool.RemoteTraceback:
"""

File "C:\ProgramData\Anaconda3\lib\multiprocessing\pool.py", line 748, in next
    raise value
IndexError: too many indices for array

**Comment by vkumar1997** [comment]
run test first, then eval

**Comment by zyh0904** [comment]
我也遇到了，已经解决了，你可以试试。作者用的不是Windows系统，所以代码各种地方会产生的路径问题 把tools/eval.py里trackers = [x.split('/')[-1] for x in trackers]这行代码的'/'改成'//'

**Comment by zyc-ai** [comment]
Duplicate with https://github.com/STVIR/pysot/issues/291
