### ISSUE TITLE
do you test DWsiam in pysot?

### ISSUE THREAD

**Issue by chenbolinstudent** [STVIR/pysot#297]
do you test DWsiam in pysot of VOT2016  and VOT2018?
thanks

**Comment by zyc-ai** [comment]
I'm having troubles understanding your question. 
Did you mean have we tested the dwsiam on VOT2016 and VOT2018?

**Comment by chenbolinstudent** [comment]
yes




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Zhiyuan Chen"<notifications@github.com&gt;; 
发送时间: 2020年2月22日(星期六) 上午10:52
收件人: "STVIR/pysot"<pysot@noreply.github.com&gt;; 
抄送: "陈柏霖"<2549853330@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [STVIR/pysot] do you test DWsiam in pysot? (#297)




I'm having troubles understanding your question.
 Did you mean have we tested the dwsiam on VOT2016 and VOT2018?

**Comment by zyc-ai** [comment]
> yes
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "Zhiyuan Chen"<notifications@github.com&gt;; 发送时间: 2020年2月22日(星期六) 上午10:52 收件人: "STVIR/pysot"<pysot@noreply.github.com&gt;; 抄送: "陈柏霖"<2549853330@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 主题: Re: [STVIR/pysot] do you test DWsiam in pysot? (#297) I'm having troubles understanding your question. Did you mean have we tested the dwsiam on VOT2016 and VOT2018? — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.

What do you mean by DWsiam?

**Comment by zyc-ai** [comment]
If you couldn't find it in the README, that means no.
