### ISSUE TITLE
template = data['template'].cuda()

### ISSUE THREAD

**Issue by masommao** [STVIR/pysot#308]
There was an error when I transferred the siamprn model to onnx or solidified the model：
    template = data['template'].cuda()
IndexError: too many indices for tensor of dimension 4

 function：
def siammodel2onnx():
    # load config
    cfg.merge_from_file(args.config)
    cfg.CUDA = torch.cuda.is_available() and cfg.CUDA
    device = torch.device('cuda' if cfg.CUDA else 'cpu')

    # create model
    model = ModelBuilder()
    # load model
    model.load_state_dict(torch.load(args.snapshot,
                                     map_location=lambda storage, loc: storage.cpu()))
    model.eval().to(device)
    #print(model)
    #trace_model = torch.jit.trace(model, torch.Tensor(1, 3,1000, 100))
    #trace_model.save('./siamrpn.pt')
    #Export the trained model to ONNX
    dummy_input = Variable(
        torch.randn(1, 3, 960, 540))  
    torch.onnx.export(model, dummy_input, "output/siamrpn.onnx")

**Comment by 13732283659** [comment]
@masommao hello masommao，Have you solved the problem?
