### ISSUE TITLE
pth->onnx->openvino infer framework error: Layer 149 input port 1 is not connected to any data

### ISSUE THREAD

**Issue by shupinghu** [STVIR/pysot#309]
I transfer the .pth model to onnx model using the method in issue  #125, then I want to use openvino infer framework, but error "Layer 149 input port 1 is not connected to any data", is there anybody try to use openvino infer framework?

**Comment by shupinghu** [comment]
error occurs in "auto executable_network = core.LoadNetwork(network_reader, "CPU");"

**Comment by zyc-ai** [comment]
It seems to be an openvino problem.

**Comment by zyc-ai** [comment]
#368
