### ISSUE TITLE
the pre-trained baseline models  were trained by VID and youtube-bb?

### ISSUE THREAD

**Issue by dypromise** [STVIR/pysot#31]
Dear authors!
the pre-trained baseline models  were trained by VID and youtube-bb dataset? or just VID is enough? I trained on VID and filter some large objects but the model overfits a lot. Any training details i will appreciate so much

**Comment by StrangerZhang** [comment]
All the baseline models trained on VID, YOUTUBE-BB, COCO and DET, please refer to [SiamRPN++](https://arxiv.org/abs/1812.11703)
