### ISSUE TITLE
What's the json format of test_dataset?

### ISSUE THREAD

**Issue by sherlockedlee** [STVIR/pysot#310]
I want to test on a new dataset not on the list,so I want to know how to write json file in VOT format,What's the precise json format of test_dataset?Thank u very much.

**Comment by sherlockedlee** [comment]
When I convert the labels in VOT styles,some errors occur:
`loading VOT2019: 100%|██████████████████████| 100/100 [00:00<00:00, 141.18it/s]
Traceback (most recent call last):
  File "./pysot/tools/test.py", line 226, in <module>
    main()
  File "./pysot/tools/test.py", line 73, in main
    for idx, (img, gt_bbox) in enumerate(video):
  File "./pysot/toolkit/datasets/video.py", line 81, in __iter__
    yield cv2.imread(self.img_names[i]), self.gt_traj[i]
IndexError: list index out of range
`
what might be the reason?

**Comment by wagh311** [comment]
I have the same problem, can you tell me the solution?Thanks!
