### ISSUE TITLE
resnet50 的卷积是 3 4 6 3

### ISSUE THREAD

**Issue by chenbolinstudent** [STVIR/pysot#315]
resnet50 的卷积是 3 4 6 3 ，您画错了吗？画成 3 3 6 3

**Comment by zyc-ai** [comment]
你指的是哪里画错了呢？

**Comment by zyc-ai** [comment]
由于没有得到更进一步的提问，我现在将本议题关闭。
请创建一个新的议题，如果你有其他问题。
