### ISSUE TITLE
siamRPN++ 的 Loss 公式 是什么？

### ISSUE THREAD

**Issue by chenbolinstudent** [STVIR/pysot#317]
siamRPN++ 的 Loss 公式 是什么？
谢谢

**Comment by zyc-ai** [comment]
siamRPN++是一个模型结构，你想用什么loss都可以。

**Comment by zyc-ai** [comment]
由于本议题没有得到更进一步的提问，我现在将其关闭。
请创建一个新的议题如果你有其他的问题。
