### ISSUE TITLE
Assertion Error    when  testing

### ISSUE THREAD

**Issue by HaoyuanXu** [STVIR/pysot#318]
I created VOT2018 folder and put VOT2018.json file inside, To do a quick check I run

python -u ../../tools/test.py 
--snapshot snapshot/checkpoint_e5.pth 
--config config.yaml \	--dataset VOT2018 2>&1 | tee logs/test_dataset.log

And got this error.

AssertionError: /home/thomas/pysot/tools/../testing_dataset/VOT2018/ants1/color/00000001.jpg
loading VOT2018: 0%| | 0/60 [00:00<?, ?it/s, ants1]

 There is no 'color' in the path of 'ants' .What is problem?

**Comment by zzzmm1** [comment]
You should download VOT2018 datasets and put the sequences in your VOT2018 file. 
It is worth noting that u should create a new file named color under the directory, like ./ants1/color, then put the ants data and annotation in the color file.
This is my solution.

**Comment by HaoyuanXu** [comment]
Thank you very much for your reply！It's an effective solution

**Comment by calmelo** [comment]
> You should download VOT2018 datasets and put the sequences in your VOT2018 file.
> It is worth noting that u should create a new file named color under the directory, like ./ants1/color, then put the ants data and annotation in the color file.
> This is my solution.

How can I download the dataset? Maybe use the json file?
