### ISSUE TITLE
Download testing datasets

### ISSUE THREAD

**Issue by chenbolinstudent** [STVIR/pysot#32]
to Download testing datasets ,
how to set the dataset?
could you say the detail of it ?
thanks

**Comment by StrangerZhang** [comment]
Put the VOT2018 in the testing_dataset, also download [VOT2018.json](https://pan.baidu.com/s/1js0Qhykqqur7_lNRtle1tA#list/path=%2F) and put it in the VOT2018 directory

**Comment by chenbolinstudent** [comment]
VOT2018/ants1/color
里面 ants1的 图片，gtroudtruth ，color等的层次关系是什么？
