### ISSUE TITLE
How long do you train the model ?

### ISSUE THREAD

**Issue by cjdjr** [STVIR/pysot#321]
I find it costs lost of time to train a model using four 2080ti.
How long do you train the model "siamrpn_r50_l234_dwxcorr_otb_8gpu"? And what type of gpu you used to train the model?

**Comment by zyc-ai** [comment]
How long do you mean by "lots of time"?

**Comment by cjdjr** [comment]
> How long do you mean by "lots of time"?

7 days.

**Comment by MARMOTatZJU** [comment]
@cjdjr  and what about the results?

**Comment by zyh0904** [comment]
I only have one GPU, how can i train the model ????? how to change the code ??

**Comment by zyc-ai** [comment]
> > How long do you mean by "lots of time"?
> 
> 7 days.

Wow, that's a lot more than expected. 
How many data did you feed to the model? And how many epoch did you trained? 
What is the batch size and how long does it take to train a step?

**Comment by HanlynnKe** [comment]
Just share my own situation. It takes me less than 6 days to train my model "siamrpn_r50_l234_dwxcorr" by one 2080ti.
I have been training for nearly a day, and this is the log an hour ago:
```shell
[2020-04-23 22:18:59,538-rk0-train.py#259] Epoch: [5][11908/21428] lr: 0.003624
        batch_time: 1.168020 (1.196387) data_time: 0.751045 (0.779244)
        cls_loss: 0.126547 (0.071734)   loc_loss: 0.167179 (0.211817)
        total_loss: 0.327163 (0.325915)
[2020-04-23 22:18:59,539-rk0-log_helper.py#105] Progress: 97620 / 428560 [22%], Speed: 1.196 s/iter, ETA 4:13:58 (D:H:M)
```

**Comment by zyc-ai** [comment]
Since no further question is asked, I'm closing this issue for now. 
Please create a new issue should you have other questions.
