### ISSUE TITLE
我制作了一个只有30张的coco数据集，用于训练但还是以20/485000的进度要跑很久 I made a coco dataset with only 30 sheets for training but still run for a long time at 20/485000

### ISSUE THREAD

**Issue by jiayuan-running** [STVIR/pysot#326]
一开始使用的是readme里下载的coco数据集，cfg里相关参数也进行了修改，但进度process一直是20/485000慢慢移，后面想看跑完整个训练的效果就换了自己的数据集改成的coco格式，1900张左右也还是一样，换成30张也是一样，看代码应该是dataset.py的原因，请问如何修改能使process进度正常？

**Comment by jiayuan-running** [comment]
pysot-master\experiments\siamrpn_r50_l234_dwxcorr_8gpu里的logs记录的
[2020-03-18 16:12:16,266-rk0-model_load.py# 48] load pretrained model from /media/jiayuan/ElementsSE/pysot-master/tools/resnet50.model
[2020-03-18 16:12:16,397-rk0-model_load.py# 42] remove prefix 'module.'
[2020-03-18 16:12:16,398-rk0-model_load.py# 33] used keys:265
[2020-03-18 16:12:16,403-rk0-train.py# 58] build train dataset
[2020-03-18 16:12:16,403-rk0-dataset.py# 39] loading COCO
[2020-03-18 16:12:16,405-rk0-dataset.py# 64] COCO loaded
[2020-03-18 16:12:16,405-rk0-dataset.py# 93] COCO start-index 0 select [26/26] path_format {}.{}.{}.jpg
[2020-03-18 16:14:02,448-rk0-train.py#272] Version Information: 

Progress: 20 / 428560 [0%], Speed: 1.143 s/iter, ETA 5:16:00 (D:H:M)
对了我是笔记本单gpu跑，
意思是30张也要跑5个小时吗？

**Comment by Dtappledoghuati** [comment]
您好，我是训练siammask，但是我在建立训练数据集的时候就出错了，您能帮我看看吗

**Comment by Dtappledoghuati** [comment]
[2020-03-18 17:21:45,190-rk0-model_load.py# 48] load pretrained model from /media/misstian/tnq/pysot-master/tools/../pretrained_models/resnet50.model
[2020-03-18 17:21:45,349-rk0-model_load.py# 42] remove prefix 'module.'
[2020-03-18 17:21:45,350-rk0-model_load.py# 33] used keys:265
[2020-03-18 17:21:45,354-rk0-train.py# 58] build train dataset
Traceback (most recent call last):
File "../../tools/train.py", line 317, in
main()
File "../../tools/train.py", line 290, in main
train_loader = build_data_loader()
File "../../tools/train.py", line 60, in build_data_loader
train_dataset = TrkDataset()
File "/media/misstian/tnq/pysot-master/tools/pysot/datasets/dataset.py", line 158, in init
subdata_cfg = getattr(cfg.DATASET, name)
File "/home/misstian/anaconda3/envs/pysot/lib/python3.7/site-packages/yacs/config.py", line 141, in getattr
raise AttributeError(name)
AttributeError: C

**Comment by jiayuan-running** [comment]
File "/home/misstian/anaconda3/envs/pysot/lib/python3.7/site-packages/yacs/config.py", yacs包没装好？ 看错误提示去找找看，我之前出国读取包的错误有原因是我环境里没把pysot和toolkit复制进site-packages里。

**Comment by jiayuan-running** [comment]
有没有大佬能告诉我一下这个读取训练集的长度参数怎么修改啊。。。我不想训练30张图片还得跑五天的。。

**Comment by Dtappledoghuati** [comment]
> File "/home/misstian/anaconda3/envs/pysot/lib/python3.7/site-packages/yacs/config.py", yacs包没装好？ 看错误提示去找找看，我之前出国读取包的错误有原因是我环境里没把pysot和toolkit复制进site-packages里
但是我测试可以跑通，会不会是数据集读取的问题，就是数据集名称之类的，我只想跑coco，其他都注释掉了，可否看一下你的config.yaml文件，以及你的数据集设置？

**Comment by Dtappledoghuati** [comment]
请问你的训练集放在什么地方呢，以及如果单独使用一个数据集，你的config.py文件怎么修改设置的？

**Comment by jiayuan-running** [comment]
META_ARC: "siamrpn_r50_l234_dwxcorr"


BACKBONE:
&nbsp; &nbsp; TYPE: "resnet50"
&nbsp; &nbsp; KWARGS:
&nbsp; &nbsp; &nbsp; &nbsp; used_layers: [2, 3, 4]
&nbsp; &nbsp; PRETRAINED: 'resnet50.model'
&nbsp; &nbsp; TRAIN_LAYERS: ['layer2', 'layer3', 'layer4']
&nbsp; &nbsp; TRAIN_EPOCH: 10
&nbsp; &nbsp; LAYERS_LR: 0.1


ADJUST:
&nbsp; &nbsp; ADJUST: true
&nbsp; &nbsp; TYPE: "AdjustAllLayer"
&nbsp; &nbsp; KWARGS:
&nbsp; &nbsp; &nbsp; &nbsp; in_channels: [512, 1024, 2048]
&nbsp; &nbsp; &nbsp; &nbsp; out_channels: [256, 256, 256]


RPN:
&nbsp; &nbsp; TYPE: 'MultiRPN'
&nbsp; &nbsp; KWARGS:
&nbsp; &nbsp; &nbsp; &nbsp; anchor_num: 5
&nbsp; &nbsp; &nbsp; &nbsp; in_channels: [256, 256, 256]
&nbsp; &nbsp; &nbsp; &nbsp; weighted: true


MASK:
&nbsp; &nbsp; MASK: false


ANCHOR:
&nbsp; &nbsp; STRIDE: 8
&nbsp; &nbsp; RATIOS: [0.33, 0.5, 1, 2, 3]
&nbsp; &nbsp; SCALES: [8]
&nbsp; &nbsp; ANCHOR_NUM: 5


TRACK:
&nbsp; &nbsp; TYPE: 'SiamRPNTracker'
&nbsp; &nbsp; PENALTY_K: 0.04
&nbsp; &nbsp; WINDOW_INFLUENCE: 0.44
&nbsp; &nbsp; LR: 0.33
&nbsp; &nbsp; EXEMPLAR_SIZE: 127
&nbsp; &nbsp; INSTANCE_SIZE: 255
&nbsp; &nbsp; BASE_SIZE: 8
&nbsp; &nbsp; CONTEXT_AMOUNT: 0.5


TRAIN:
&nbsp; &nbsp; EPOCH: 200
&nbsp; &nbsp; START_EPOCH: 0
&nbsp; &nbsp; BATCH_SIZE: 1
&nbsp; &nbsp; BASE_LR: 0.005
&nbsp; &nbsp; CLS_WEIGHT: 1.0
&nbsp; &nbsp; LOC_WEIGHT: 1.2
&nbsp; &nbsp; RESUME: ''


&nbsp; &nbsp; LR:
&nbsp; &nbsp; &nbsp; &nbsp; TYPE: 'log'
&nbsp; &nbsp; &nbsp; &nbsp; KWARGS:
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; start_lr: 0.005
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; end_lr: 0.0005
&nbsp; &nbsp; LR_WARMUP:
&nbsp; &nbsp; &nbsp; &nbsp; TYPE: 'step'
&nbsp; &nbsp; &nbsp; &nbsp; EPOCH: 5
&nbsp; &nbsp; &nbsp; &nbsp; KWARGS:
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; start_lr: 0.001
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; end_lr: 0.005
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; step: 1


DATASET:
&nbsp; &nbsp; NAMES:&nbsp;
&nbsp; &nbsp; - 'COCO'
&nbsp; &nbsp;&nbsp;


&nbsp; &nbsp; TEMPLATE:
&nbsp; &nbsp; &nbsp; &nbsp; SHIFT: 4
&nbsp; &nbsp; &nbsp; &nbsp; SCALE: 0.05
&nbsp; &nbsp; &nbsp; &nbsp; BLUR: 0.0
&nbsp; &nbsp; &nbsp; &nbsp; FLIP: 0.0
&nbsp; &nbsp; &nbsp; &nbsp; COLOR: 1.0


&nbsp; &nbsp; SEARCH:
&nbsp; &nbsp; &nbsp; &nbsp; SHIFT: 64
&nbsp; &nbsp; &nbsp; &nbsp; SCALE: 0.18
&nbsp; &nbsp; &nbsp; &nbsp; BLUR: 0.2
&nbsp; &nbsp; &nbsp; &nbsp; FLIP: 0.0
&nbsp; &nbsp; &nbsp; &nbsp; COLOR: 1.0


&nbsp; &nbsp; NEG: 0.2
&nbsp; &nbsp; GRAY: 0.0





------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Dtappledoghuati"<notifications@github.com&gt;; 
发送时间: 2020年3月19日(星期四) 中午11:06
收件人: "STVIR/pysot"<pysot@noreply.github.com&gt;; 
抄送: "吕佳元"<841713241@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [STVIR/pysot] 我制作了一个只有30张的coco数据集，用于训练但还是以20/485000的进度要跑很久 I made a coco dataset with only 30 sheets for training but still run for a long time at 20/485000 (#326)





 
请问你的训练集放在什么地方呢，以及如果单独使用一个数据集，你的config.py文件怎么修改设置的？

**Comment by jiayuan-running** [comment]
修改了一些参数 现在已经可以很快的跑通了 后续调参的细节有空回来再补充吧 git真是个好地方 很多类似的问题给了很大的启发 终于搞定了。。。

**Comment by Dtappledoghuati** [comment]
能否加个vx，真的很急13051128832,谢谢

**Comment by jiayuan-running** [comment]
pysot/core/config.py:
#显卡每批次数
__C.TRAIN.BASE_SIZE = 2
#总迭代次数
__C.TRAIN.EPOCH = 2
#预热迭代次数
__C.TRAIN.LR_WARMUP.EPOCH = 1
#每次迭代数量
__C.DATASET.VIDEOS_PER_EPOCH = 10  
#框架迭代次数
__C.BACKBONE.TRAIN_EPOCH = 1


pysot-master/experiments/siamrpn_r50_l234_dwxcorr_8gpu/config.yaml
BATCH_SIZE: 2 #每批训练数量（节约gpu
BACKBONE:
	TRAIN_EPOCH: 2 对应框架迭代次数
TRAIN:
	EPOCH: 2	对应总迭代次数
	LR_WARMUP:
		EPOCH: 1
修改参数如上，但好像还是修改失败了，和我一起做的另外一个老哥调成功了就是这么和我说的，但我的依旧跑要十几天。

**Comment by jiayuan-running** [comment]
Epoch: [1][20/75000] lr: 0.001000
	batch_time: 1.102266 (1.060689)	data_time: 0.763663 (0.722046)
	cls_loss: 0.617595 (0.667299)	loc_loss: 0.417687 (0.474921)
	total_loss: 1.118819 (1.237203)	
[2020-03-20 09:49:04,063-rk0-log_helper.py#105] Progress: 20 / 1500000 [0%], Speed: 1.061 s/iter, ETA 18:09:56 (D:H:M)

**Comment by jiayuan-running** [comment]
c 两个参数文件夹，每次修改都会有变化但长度永远不变，之后发现一个参数文件路径出错了，现在彻底解决了。。。

**Comment by way790110** [comment]
@Dtappledoghuati 你训练siammask 有没有遇到问题?

**Comment by Dtappledoghuati** [comment]
> @Dtappledoghuati 你训练siammask 有没有遇到问题?

问题很多，我觉得根本训练不通，rpn就很容易就通了

**Comment by way790110** [comment]
@jiayuan-running 
pysot/core/config.py:
裡面有一個600000的數字 我改了會變少，但是我不知這是幹嘛的
你看一下看知不知道

**Comment by Dtappledoghuati** [comment]
600000是每次迭代的数量，减少就会缩短训练时间。还有你训练siammask成功了吗，我遇到一个输入输出矩阵不对应的问题，就卡住了

**Comment by way790110** [comment]
你是訓練哪一個 
我剛剛訓練 siamrpn_r50_l234_dwxcorr_8gpu 
用 checkpoint_e1.pth  跑demo.sh
出來只有一個正方形的框
感覺怪怪的

**Comment by Dtappledoghuati** [comment]
我没有训练这个，我训练的是单gpu的，笔记本

**Comment by way790110** [comment]
你有微信嗎 加一下

我也是單GPU 我有稍微改一下

但是我現在要跑siammask 訓練 一直有問題

**Comment by Dtappledoghuati** [comment]
13051128832

**Comment by Singapore-mor** [comment]
> 你有微信嗎 加一下
> 
> 我也是單GPU 我有稍微改一下
> 
> 但是我現在要跑siammask 訓練 一直有問題

想问下单gpu要怎么修改才能把train跑下来，不是很清楚应该怎么修改，方便加下QQ吗 2761520483

**Comment by Singapore-mor** [comment]
> Epoch: [1][20/75000] lr: 0.001000
> batch_time: 1.102266 (1.060689) data_time: 0.763663 (0.722046)
> cls_loss: 0.617595 (0.667299) loc_loss: 0.417687 (0.474921)
> total_loss: 1.118819 (1.237203)
> [2020-03-20 09:49:04,063-rk0-log_helper.py#105] Progress: 20 / 1500000 [0%], Speed: 1.061 s/iter, ETA 18:09:56 (D:H:M)

我也遇到了这个问题，可以加一下联系方式讨论下吗？我QQ2761520483，谢谢啦

**Comment by byq817** [comment]
> 一开始使用的是readme里下载的coco数据集，cfg里相关参数也进行了修改，但进度process一直是20/485000慢慢移，后面想看跑完整个训练的效果就换了自己的数据集改成的coco格式，1900张左右也还是一样，换成30张也是一样，看代码应该是dataset.py的原因，请问如何修改能使process进度正常？

我可以加您好友吗，我自制了来一个coco数据集想问问您

**Comment by byq817** [comment]
> 一开始使用的是readme里下载的coco数据集，cfg里相关参数也进行了修改，但进度process一直是20/485000慢慢移，后面想看跑完整个训练的效果就换了自己的数据集改成的coco格式，1900张左右也还是一样，换成30张也是一样，看代码应该是dataset.py的原因，请问如何修改能使process进度正常？

我可以加您好友吗，我自制了来一个coco数据集想问问您  QQ821099463

**Comment by jiayuan-running** [comment]
keke,zhe ge&nbsp; wen ti wo tong yi&nbsp; hui da yi xia ,我当时是把dataset.py复制到了Python的编译环境的文件里，改参数得到那个你们设置的环境里的dataset里改，我这边跑程序它直接读环境里的，不会读pysot文件夹里的。




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "白颖奇"<notifications@github.com&gt;; 
发送时间: 2020年5月28日(星期四) 晚上8:53
收件人: "STVIR/pysot"<pysot@noreply.github.com&gt;; 
抄送: "吕佳元"<841713241@qq.com&gt;; "Mention"<mention@noreply.github.com&gt;; 
主题: Re: [STVIR/pysot] 我制作了一个只有30张的coco数据集，用于训练但还是以20/485000的进度要跑很久 I made a coco dataset with only 30 sheets for training but still run for a long time at 20/485000 (#326)





  
一开始使用的是readme里下载的coco数据集，cfg里相关参数也进行了修改，但进度process一直是20/485000慢慢移，后面想看跑完整个训练的效果就换了自己的数据集改成的coco格式，1900张左右也还是一样，换成30张也是一样，看代码应该是dataset.py的原因，请问如何修改能使process进度正常？
  
我可以加您好友吗，我自制了来一个coco数据集想问问您
