### ISSUE TITLE
Training issues

### ISSUE THREAD

**Issue by ZZXin** [STVIR/pysot#33]
Thank you for your work, Could I run train.py in single GPU?what should I do? When I run 'train.py' directly, I get the following error:Traceback (most recent call last):
  File "../../tools/train.py", line 314, in <module>
    main()
  File "../../tools/train.py", line 256, in main
    rank, world_size = dist_init()
  File "/home/db/Subject/pysot/pysot/utils/distributed.py", line 104, in dist_init
    rank, world_size = _dist_init()
  File "/home/db/Subject/pysot/pysot/utils/distributed.py", line 83, in _dist_init
    rank = int(os.environ['RANK'])
  File "/home/db/anaconda3/envs/pysot/lib/python3.7/os.py", line 678, in __getitem__
    raise KeyError(key) from None
KeyError: 'RANK'

**Comment by StrangerZhang** [comment]
`
CUDA_VISIBLE_DEVICES=0 # change your cuda visible devices here
python -m torch.distributed.launch \
    --nproc_per_node=1 \ # change nproc_per_node to 1
    --master_port=2333 \
    ../../tools/train.py --cfg config.yaml
`

Note using single GPU takes long time to train.

**Comment by ZZXin** [comment]
I followed what you said, but I have encountered this problem:usage: train.py [-h] [--cfg CFG] [--seed SEED]
train.py: error: unrecognized arguments: --local_rank=0
And this is my GPU configuration information:Fri Jun  7 21:13:59 2019       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 418.43       Driver Version: 418.43       CUDA Version: 10.1     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  GeForce GTX 108...  Off  | 00000000:01:00.0  On |                  N/A |
|  0%   44C    P8    17W / 275W |    153MiB / 11175MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
|    0      1069      G   /usr/lib/xorg/Xorg                           151MiB |
+-----------------------------------------------------------------------------+

**Comment by StrangerZhang** [comment]
Please pull the repo, I update the train.py file.

**Comment by ZZXin** [comment]
OK,I am watching it,thank you very much

**Comment by ZZXin** [comment]
It works,thank you!

**Comment by chenbolinstudent** [comment]
If I want to use one node ,and not use "-m torch.distributed.launch --nproc_per_node=1 --master_port=2333"  ,how should I do ?

**Comment by chenbolinstudent** [comment]
master_port must be 2333 ?

**Comment by chenbolinstudent** [comment]
@StrangerZhang

**Comment by StrangerZhang** [comment]
you can set any free port in your server

**Comment by chenbolinstudent** [comment]
请问如何不通过命令行运行train.py?目前我直接在运行test.py 可以，但是直接运行train.py:
File "/home/public/anaconda3/lib/python3.6/os.py", line 669, in getitem
raise KeyError(key) from None
KeyError: 'RANK'

请问如何在代码中设置：
CUDA_VISIBLE_DEVICES=0,1,2,3,4,5,6,7
python -m torch.distributed.launch 
--nproc_per_node=8 
--master_port=2333 
../../tools/train.py --cfg config.yaml
中的值，使得可以直接在pycharm运行train.py，
谢谢您的回复。

**Comment by chenbolinstudent** [comment]
how to see free port in  server？

**Comment by xi-mao** [comment]
@chenbolinstudent  请问你解决了怎么设置在pycharm运行了吗？

**Comment by chenbolinstudent** [comment]
请问如何不通过命令行运行train.py?目前我直接在运行test.py 可以，但是直接运行train.py:
@StrangerZhang

**Comment by chenbolinstudent** [comment]
when training :
[2019-07-09 11:00:26,420-rk0-train.py#252] Epoch: [4][3324/7692] lr: 0.002627
	batch_time: 2.192731 (2.188426)	data_time: 0.138137 (0.081258)
	total_loss: 0.153974 (0.183364)	cls_loss: 0.012416 (0.018691)
	loc_loss: 0.117965 (0.137227)	

what is the meaning and relation of these 6 loss?

**Comment by colinlin1982** [comment]
@ZZXin how long does it cost while training on single 1080ti GPU?

**Comment by bluoluo** [comment]
> `CUDA_VISIBLE_DEVICES=0 # change your cuda visible devices here`
> `python -m torch.distributed.launch --nproc_per_node=1 --master_port=2333 ../../tools/train.py --cfg config.yaml`
> 
> Note using single GPU takes long time to train.


你好，请问我按你这样的命令在单显卡训练，报这样的错误

Traceback (most recent call last):
  File "../../tools/train.py", line 320, in <module>
    main()
  File "../../tools/train.py", line 258, in main
    rank, world_size = dist_init()    
  File "/home/bluo/git_clone/pysot/pysot/utils/distributed.py", line 113, in dist_init
    raise RuntimeError(*e.args)
RuntimeError: the distributed NCCL backend is not available; try to recompile the THD package with CUDA and NCCL 2+ support at /opt/conda/conda-bld/pytorch_1533739672741/work/torch/lib/THD/process_group/General.cpp:17

请问如何解决？？

**Comment by justDoIt1314** [comment]
> `CUDA_VISIBLE_DEVICES=0 # change your cuda visible devices here`
> `python -m torch.distributed.launch --nproc_per_node=1 --master_port=2333 ../../tools/train.py --cfg config.yaml`
> 
> Note using single GPU takes long time to train.

CUDA_VISIBLE_DEVICES=0  ，Where do you put it？
