### ISSUE TITLE
Is there anyone training siammask_r50_l3 successfully?

### ISSUE THREAD

**Issue by way790110** [STVIR/pysot#331]
This is my error.
Can I fix it?
![siammask_r50_l3](https://user-images.githubusercontent.com/33109449/77220579-89c92900-6b7c-11ea-8386-50ec0b0a2ff7.jpg)

**Comment by zyc-ai** [comment]
What is the value of mask_loss? 
How to reproduce?

**Comment by zyc-ai** [comment]
Since no further question is asked, I'm closing this issue for now. 
Please create a new issue should you have other questions.

**Comment by haishibei** [comment]
> This is my error.
> Can I fix it?
> ![siammask_r50_l3](https://user-images.githubusercontent.com/33109449/77220579-89c92900-6b7c-11ea-8386-50ec0b0a2ff7.jpg)

excuse me, i want to know that have you fixed it and trained successfully?

**Comment by EEEEEREN** [comment]
> > This is my error.
> > Can I fix it?
> > ![siammask_r50_l3](https://user-images.githubusercontent.com/33109449/77220579-89c92900-6b7c-11ea-8386-50ec0b0a2ff7.jpg)
> 
> excuse me, i want to know that have you fixed it and trained successfully?

你训练成功了吗？
这个问题怎么解决的

**Comment by EEEEEREN** [comment]
> This is my error.
> Can I fix it?
> ![siammask_r50_l3](https://user-images.githubusercontent.com/33109449/77220579-89c92900-6b7c-11ea-8386-50ec0b0a2ff7.jpg)

你解决了吗
did u fix this problem?
