### ISSUE TITLE
> 我们假设追踪的是一个刚体，即其尺寸、形状在短时间内不会发生较大的变动。因此，我们对这样的改变进行惩罚。

### ISSUE THREAD

**Issue by buaacarzp** [STVIR/pysot#332]
> 我们假设追踪的是一个刚体，即其尺寸、形状在短时间内不会发生较大的变动。因此，我们对这样的改变进行惩罚。

您好，我想问下，在tracking阶段，得到的bbox的位置不就可以了吗？为什么还要加上模板的中心点坐标位置呢？
```
cx = bbox[0] + self.center_pos[0] #-15+345 ,模板的中心点
cy = bbox[1] + self.center_pos[1]
```

_Originally posted by @buaacarzp in https://github.com/STVIR/pysot/issues/330#issuecomment-601972967_

**Comment by yangkai12** [comment]
bbox应该算的是padding之后的中心点偏移量(相对于上一帧），+ self.center_pos（上一帧在原图中心点位置）就可以得到对应于原图的位置。

**Comment by buaacarzp** [comment]
> bbox应该算的是padding之后的中心点偏移量(相对于上一帧），+ self.center_pos（上一帧在原图中心点位置）就可以得到对应于原图的位置。

可是这个bbox[0]是RPN层输出的偏移量加上anchor的坐标了，已经是一个确定的坐标的了。再说了这跟上一帧有什么关系呢？兄弟，这是 one-shot detection啊

**Comment by yangkai12** [comment]
self.center_pos[0]是上一帧目标的中心坐标，当前测试帧是以上一帧目标中心来裁剪，然后测试的，所以当前帧相对于上一帧会有偏移量，求出中心点偏移量就可以了。

**Comment by buaacarzp** [comment]
> self.center_pos[0]是上一帧目标的中心坐标，当前测试帧是以上一帧目标中心来裁剪，然后测试的，所以当前帧相对于上一帧会有偏移量，求出中心点偏移量就可以了。

您好， 为什么当前帧对于上一帧有偏差呢，当前帧的中心点不是和上一帧的中心点一样吗？

**Comment by yangkai12** [comment]
当前帧按照上一帧的目标中心坐标来裁剪出测试图像，因为当前帧中心未知，但是显然当前帧和上一帧目标中心不一样，会有偏移，而此时裁剪出来的测试图像的中心点（255/2）y与目标的中心点并不重合，所以bbox求出来的自然是偏移量，并不是裁剪时的中心。

**Comment by buaacarzp** [comment]
> 当前帧按照上一帧的目标中心坐标来裁剪出测试图像，因为当前帧中心未知，但是显然当前帧和上一帧目标中心不一样，会有偏移，而此时裁剪出来的测试图像的中心点（255/2）y与目标的中心点并不重合，所以bbox求出来的自然是偏移量，并不是裁剪时的中心。

https://github.com/STVIR/pysot/blob/7835f640aa9dcc2beffb2e13e9318c6c3dbc6af4/pysot/tracker/siamrpn_tracker.py#L112

老哥，您看这里，这个pred_bbox就是将网络输出的偏移量加上anchor的坐标了，已经是实际的坐标了啊。

**Comment by yangkai12** [comment]
这个算的是经过padding之后的，而提问的算的是原图目标位置。整个测试是原图-->padding+croped-->resize成255测试图像。

**Comment by yangkai12** [comment]
这个算的是size为255测试图像的位置，而提问的算的是原图目标位置。整个测试是原图-->padding+croped-->resize成255测试图像。

**Comment by buaacarzp** [comment]
> 这个算的是经过padding之后的，而提问的算的是原图目标位置。整个测试是原图-->padding+croped-->resize成255测试图像。

![image](https://user-images.githubusercontent.com/43240561/77405971-e5025200-6dee-11ea-8220-2472b9cfe062.png)

老哥您好，上图的序号：1,2,3,4是操作顺序，分别是先padding后crop成（225,225），经过预测后得到一个bbox的坐标：
https://github.com/STVIR/pysot/blob/7835f640aa9dcc2beffb2e13e9318c6c3dbc6af4/pysot/tracker/siamrpn_tracker.py#L112
那么接下来要做的是不是将这个坐标转成黑色的框框：原图大小中去？ 为什么通过：
```
cx = bbox[0] + self.center_pos[0] #-15+345 ,模板的中心点
cy = bbox[1] + self.center_pos[1] 
```
加上模板的中心点坐标呢？（假设是第二帧，模板是第一帧），我就这里一直不明白。

**Comment by buaacarzp** [comment]
> 这个算的是size为255测试图像的位置，而提问的算的是原图目标位置。整个测试是原图-->padding+croped-->resize成255测试图像。
我之所认为bbox的坐标是原图中的坐标，是因为:
```
def _convert_bbox(self, delta, anchor):
        delta = delta.permute(1, 2, 3, 0).contiguous().view(4, -1) #将(2205,4)的尺寸转成(4,2205)
        delta = delta.data.cpu().numpy()

        delta[0, :] = delta[0, :] * anchor[:, 2] + anchor[:, 0] #deltax = (X-Xa)/Wa ,anchor中的坐标是真实坐标
        delta[1, :] = delta[1, :] * anchor[:, 3] + anchor[:, 1]
        delta[2, :] = np.exp(delta[2, :]) * anchor[:, 2] #deltaw =log(W/Wa)
        delta[3, :] = np.exp(delta[3, :]) * anchor[:, 3]
        return delta
```
`_convert_bbox`是将偏移量已经转成了实际的坐标了，返回的delta就是在(255,255)原图中的坐标了啊

**Comment by buaacarzp** [comment]
> 这个算的是size为255测试图像的位置，而提问的算的是原图目标位置。整个测试是原图-->padding+croped-->resize成255测试图像。

老哥在吗，可以加个qq吗？ 510695983

**Comment by buaacarzp** [comment]
I find the anchor was generate the coordinates from the center, that is to say the bbox is represented the offset of the center point. And the self.center_pos[0] is the the real coordinates in the picture, so add them to get the new self.center_pos and the new self.size.
