### ISSUE TITLE
siamrpn++和siamrpn训练的loss完全一样吗？

### ISSUE THREAD

**Issue by chenbolinstudent** [STVIR/pysot#335]
siamrpn++和siamrpn训练的loss完全一样吗？
有什么差异？

**Comment by chenbolinstudent** [comment]
@lb1100 @foolwood @103yiran @vladz

**Comment by 103yiran** [comment]
yes @chenbolinstudent

**Comment by chenbolinstudent** [comment]
@103yiran 
but in the official siamrpn paper,it's L1loss is not same as the code in pysot.

**Comment by chenbolinstudent** [comment]
@103yiran
why the code of pysot is L1 ？
