### ISSUE TITLE
some thing about distractor-aware rerank the proposals P ?

### ISSUE THREAD

**Issue by buaacarzp** [STVIR/pysot#336]
I read the paper seriously, but I can't find this stratage in the `pysot/tracker/siamrpnlt_tracker.py`:
![image](https://user-images.githubusercontent.com/43240561/77783857-88c05c00-7094-11ea-8561-d04c1d62476c.png)
I only can find the local-toglobal strategy,but can't find the distractor-aware. Every bro, please help me.

**Comment by iminfine** [comment]
It seems there is not an official implementation of this section. There is an unofficial one at:JachinShen/DaSiamRPNAT.

**Comment by zyc-ai** [comment]
#324
