### ISSUE TITLE
the bbox problem in training.

### ISSUE THREAD

**Issue by buaacarzp** [STVIR/pysot#337]
> ```
>   如题，请问经过par_crop.py 和 gen_json.py文件处理后的COCO2017数据集输出的crop511 和 train2017.json文件中truth box坐标的关系。手动按坐标框貌似在训练图片上框不到东西，逗逼了~
>   另外， 请问`crop_like_SiamFC`函数中，下面两行代码的处理是什么意思啊？
> ```
> 
> > wc_z = target_size[1] + context_amount * sum(target_size)
> > hc_z = target_size[0] + context_amount * sum(target_size)
> 
> ```
>     万分感谢。
> ```
在吗？我也想问这个
```
 wc_z = w + context_amount * (w+h)
 hc_z = h + context_amount * (w+h)
```
既然已经crop成511了，bbox的坐标肯定也跟随resize到511的尺寸下了，为什么这里还要对Bbox的宽和高进行padding？

_Originally posted by @buaacarzp in https://github.com/STVIR/pysot/issues/163#issuecomment-605705300_

**Comment by zyc-ai** [comment]
#334
