### ISSUE TITLE
关于环境配置的问题

### ISSUE THREAD

**Issue by HanlynnKe** [STVIR/pysot#339]
您好，我在配置pysot环境的时候发现pytorch0.4.1的下载速度太慢了，几乎为零，可以使用更高版本的pytorch吗？
这是执行```conda install pytorch=0.4.1 torchvision cuda90 -c pytorch ```这句话的结果:

<img width="718" alt="截屏2020-03-31 下午2 58 01" src="https://user-images.githubusercontent.com/41326993/77996364-0ec3f780-7360-11ea-8250-027826da0ec1.png">

**Comment by HanlynnKe** [comment]
最后靠清华源下了无数次终于下好了...

**Comment by MichaelT800** [comment]
改清华源，“conda install pytorch=0.4.1 torchvision cuda90 -c pytorch”这里要去掉"-c pytorch",否则还是从官方下载。
