### ISSUE TITLE
Hi， is it your convenient to supply a download link about your croped youtube dataset?

### ISSUE THREAD

**Issue by Singingkettle** [STVIR/pysot#34]

**Comment by Singingkettle** [comment]
I have problem to download the full dataset about youtube.  I have spend about six months to download that, which seems unsuccessful. Thank you!

**Comment by Ling-wei** [comment]
got the same question. The download speed is too slow...

**Comment by kshgz** [comment]
I had the same question.

**Comment by Singingkettle** [comment]
Very appreciate for any help! I have big trouble to download the youtube dataset. Thanks!

**Comment by bkkm78** [comment]
Another problem is that many of the videos in youtube-bb are no longer available. For the sake of reproducibility, it would be very helpful if the maintainers could provide the list of videos that were actually used during training.

**Comment by lb1100** [comment]
We are working on this. We will upload our cropped data and jsons for youtube to BaiduYun/Google Drive. But it's still too large (~130G). It will take a long time to upload.

**Comment by madhukiranets** [comment]
Hi,
Was wondering if the link to baidu/google for the cropped dataset is up?
Thanks in advance
Madhu

**Comment by chenbolinstudent** [comment]
@lb1100
when do you can finish upload our cropped data and jsons for youtube to BaiduYun/Google Drive.?
thanks

**Comment by csg1111** [comment]
I had the same question,how soon will you serve the cropped data?,thank you.

**Comment by csg1111** [comment]
> @lb1100
> when do you can finish upload our cropped data and jsons for youtube to BaiduYun/Google Drive.?
> thanks

do you need the cropped youtube data?me to.

**Comment by yangwf1** [comment]
same problem，waiting for the cropped data,  really appreciate it. @lb1100

**Comment by MaxLin86** [comment]
waiting for the cropped data ~ | ~.  Thanks

**Comment by longchaoyang** [comment]
Waiting for the cropped youtube-bb data, really need it.

**Comment by charlesyann** [comment]
really need cropped youtube-bb data, thanks~

**Comment by StrangerZhang** [comment]
You can download our cropped YOUTUBE-BB in [Baidu Drive](https://pan.baidu.com/s/1lTJQ2U1SpgTSRG5c8yE9hA)

**Comment by chenbolinstudent** [comment]
when training only need the data cropped YOUTUBE-BB in Baidu Drive about YOUTUBE-BB?

**Comment by chenbolinstudent** [comment]
when training only need the data cropped YOUTUBE-BB in Baidu Drive about YOUTUBE-BB?
It do not need the original data?

**Comment by chenbolinstudent** [comment]
when training only need the data cropped YOUTUBE-BB in Baidu Drive（100G） about YOUTUBE-BB?
It do not need the original data(400G)?

**Comment by chenbolinstudent** [comment]
when training only need the data cropped YOUTUBE-BB in Baidu Drive（100G） about YOUTUBE-BB?
It do not need the raw image(400G)?

**Comment by chenbolinstudent** [comment]
It do not need the val dataset in the all process ,right?

**Comment by chenbolinstudent** [comment]
@ StrangerZhang
Can you say the catalogue level of cropped YOUTUBE-BB?

**Comment by StrangerZhang** [comment]
--yt_bb
   --crop511
      --train0000
      --train0001
      ...
  --train.json

**Comment by StrangerZhang** [comment]
- yt_bb
   - crop511
      - train0000
      - train0001
...
  - train.config

**Comment by chenbolinstudent** [comment]
can you offer the baidu wangpan of raw image(400G) of youtube_bb?

**Comment by chenbolinstudent** [comment]
[2019-07-08 17:14:57,829-rk0-train.py# 60] build train dataset
[2019-07-08 17:14:57,829-rk0-dataset.py# 39] loading VID
[2019-07-08 17:15:00,390-rk0-dataset.py# 64] VID loaded
[2019-07-08 17:15:00,392-rk0-dataset.py# 93] VID start-index 0 select [100000/3862] path_format {}.{}.{}.jpg
[2019-07-08 17:15:00,392-rk0-dataset.py# 39] loading YOUTUBEBB
[2019-07-08 17:15:12,246-rk0-dataset.py# 64] YOUTUBEBB loaded
[2019-07-08 17:15:12,269-rk0-dataset.py# 93] YOUTUBEBB start-index 3862 select [199267/199267] path_format {}.{}.{}.jpg
[2019-07-08 17:15:12,269-rk0-dataset.py# 39] loading COCO
[2019-07-08 17:15:16,137-rk0-dataset.py# 64] COCO loaded
[2019-07-08 17:15:16,149-rk0-dataset.py# 93] COCO start-index 203129 select [117266/117266] path_format {}.{}.{}.jpg
[2019-07-08 17:15:16,149-rk0-dataset.py# 39] loading DET
[2019-07-08 17:15:21,004-rk0-dataset.py# 64] DET loaded
[2019-07-08 17:15:21,057-rk0-dataset.py# 93] DET start-index 320395 select [333474/333474] path_format {}.{}.{}.jpg
[2019-07-08 17:15:21,185-rk0-dataset.py#204] shuffle done!
[2019-07-08 17:15:21,187-rk0-dataset.py#205] dataset length 120000


about VID 100000/3862
is it normal? is these anyone same?

**Comment by songdejia** [comment]
> * yt_bb
>   
>   * crop511
>     
>     * train0000
>     * train0001
>       ...
>   * train.config

Have u test the label of cropped yt_bb dataset? The visual result show something wrong, because bbox is not tight. @StrangerZhang

**Comment by StrangerZhang** [comment]
The width and height in the train.json file is the original value. You need to calculate the resize factor to resize the width and height. Refer the [dataset.py](https://github.com/STVIR/pysot/blob/5fb3970febcdb3d69cfc0b7d2f6534fe0c547b53/pysot/datasets/dataset.py#L213) to get the correct size.

**Comment by songdejia** [comment]
Thanks, but visualization is done here dataset.py line 414.
![image](https://user-images.githubusercontent.com/36180483/60950568-fc191680-a329-11e9-953f-74ce0dda2d29.png)

Reuslt: 
![image](https://user-images.githubusercontent.com/36180483/60950533-e86db000-a329-11e9-9512-3bf34f92a301.png)
![image](https://user-images.githubusercontent.com/36180483/60950640-1bb03f00-a32a-11e9-8e24-a937d496b25c.png)

**Comment by songdejia** [comment]
> Thanks, but visualization is done here dataset.py line 414.
> ![image](https://user-images.githubusercontent.com/36180483/60950568-fc191680-a329-11e9-953f-74ce0dda2d29.png)
> 
> Reuslt:
> ![image](https://user-images.githubusercontent.com/36180483/60950533-e86db000-a329-11e9-9512-3bf34f92a301.png)
> ![image](https://user-images.githubusercontent.com/36180483/60950640-1bb03f00-a32a-11e9-8e24-a937d496b25c.png)

@StrangerZhang

**Comment by songdejia** [comment]
When test here, some diff also found
![image](https://user-images.githubusercontent.com/36180483/60951119-0c7dc100-a32b-11e9-96c5-8e8d6bd67f60.png)

Result:
![image](https://user-images.githubusercontent.com/36180483/60951166-228b8180-a32b-11e9-887e-257b1dce5a40.png)
![image](https://user-images.githubusercontent.com/36180483/60951195-31723400-a32b-11e9-9b9f-17c0c56af84d.png)
![image](https://user-images.githubusercontent.com/36180483/60951206-3800ab80-a32b-11e9-8eff-8ccb629cb775.png)

**Comment by songdejia** [comment]
> When test here, some diff also found
> ![image](https://user-images.githubusercontent.com/36180483/60951119-0c7dc100-a32b-11e9-96c5-8e8d6bd67f60.png)
> 
> Result:
> ![image](https://user-images.githubusercontent.com/36180483/60951166-228b8180-a32b-11e9-887e-257b1dce5a40.png)
> ![image](https://user-images.githubusercontent.com/36180483/60951195-31723400-a32b-11e9-9b9f-17c0c56af84d.png)
> ![image](https://user-images.githubusercontent.com/36180483/60951206-3800ab80-a32b-11e9-8eff-8ccb629cb775.png)

@StrangerZhang

**Comment by StrangerZhang** [comment]
Cannot see your picture.

**Comment by StrangerZhang** [comment]
We upload the wrong version of cropped images! Waiting for re-upload.

**Comment by songdejia** [comment]
> We upload the wrong version of cropped images! Waiting for re-upload.

OK， thank u for your help @StrangerZhang

**Comment by shallowtoil** [comment]
> We upload the wrong version of cropped images! Waiting for re-upload.

Hi, can I know when will the re-upload be done?

Many thanks for you time.

**Comment by chenbolinstudent** [comment]
yt_bb
crop511
train0000
train0001
...
train.config


where is the train.config file? I cannot find it

**Comment by chenbolinstudent** [comment]
@songdejia
how to visualization the dataset?

**Comment by songdejia** [comment]
> > We upload the wrong version of cropped images! Waiting for re-upload.
> 
> Hi, can I know when will the re-upload be done?
> 
> Many thanks for you time.

@StrangerZhang  Hi, when will we download cropped yt_bb? thx in advance

**Comment by songdejia** [comment]
> @songdejia
> how to visualization the dataset?

@chenbolinstudent  add in TrkDataset
![image](https://user-images.githubusercontent.com/36180483/61165725-a1183700-a556-11e9-8fc0-3c5832a30be5.png)

**Comment by chenbolinstudent** [comment]
when the dataset upload again finished?

@StrangerZhang

thanks

**Comment by chenbolinstudent** [comment]
I have trained with new youtube dataset,but why EAO=0.360 ?

should I change other?

**Comment by wml666** [comment]
> > * yt_bb
> >   
> >   * crop511
> >     
> >     * train0000
> >     * train0001
> >       ...
> >   * train.config
> 
> Have u test the label of cropped yt_bb dataset? The visual result show something wrong, because bbox is not tight. @StrangerZhang

I download the youtubebb dataset from baiduyun ,however i did not find the train.config, but i find train.json file, is that train.json==train.config thanks

**Comment by chenbolinstudent** [comment]
@StrangerZhang
can you offer the code of CAM of channels?
thanks

**Comment by chenbolinstudent** [comment]
@songdejia 
add in TrkDataset , and how and where to use the function?

**Comment by litingsjj** [comment]
@StrangerZhang Have you upload dataset to google driver? Thx!

**Comment by xumengmeng-97** [comment]
请问有youtube-bb的数据集吗？
