### ISSUE TITLE
使用test.py时，出现了问题，请问是数据集问题吗？

### ISSUE THREAD

**Issue by boy-new-2019** [STVIR/pysot#340]
当我在pycharm的终端按教程使用的时候，出现如下问题![image](https://user-images.githubusercontent.com/52913936/78045051-0a233180-73a8-11ea-8cee-9bf8defe3512.png)
然后我直接run test.py，加上这个配置，但是这次跑到一半就报错![image](https://user-images.githubusercontent.com/52913936/78045339-68501480-73a8-11ea-80f2-494a15e92593.png)

**Comment by boy-new-2019** [comment]
是数据集问题，我复制了一遍human4就能跑了。。。

**Comment by ferumchrome** [comment]
@boy-new-2019 Hi, I have the same error. Do you just copy Human4 to Human4-2?
