### ISSUE TITLE
使用eval.py的时候报错，求问是为什么？

### ISSUE THREAD

**Issue by boy-new-2019** [STVIR/pysot#342]
![QQ图片20200404214310](https://user-images.githubusercontent.com/52913936/78452342-5bd7fe80-76bd-11ea-8fbb-41125ce46f68.png)
用的otb100的数据集，直接跑test.py后的结果的评估，用的siamrpn_alex_dwxcorr预训练模型，系统win10，环境和requirement一样

**Comment by SISTMrL** [comment]
你好，我是刚接触计算机视觉的一名学生，这个学期期末的project打算做目标追踪，苦于没人讨论，能否告知联系方式方便讨教，十分感谢

**Comment by byq817** [comment]
您好,请问解决了吗

**Comment by zyc-ai** [comment]
与https://github.com/STVIR/pysot/issues/291重复
