### ISSUE TITLE
eval.

### ISSUE THREAD

**Issue by zt1046656665** [STVIR/pysot#344]
eval.时出现assert len(trackers) > 0 请问一下是什么原因呢

**Comment by zt1046656665** [comment]
test的时候都是正常的 生成了result  然后eval就出错  assert len(trackers) > 0

**Comment by zyc-ai** [comment]
抱歉我有些无法理解你的问题

**Comment by byq817** [comment]
请问解决了吗?我也遇到了这个问题

**Comment by zt1046656665** [comment]
好像是我系统要用ubuntu

**Comment by byq817** [comment]
我用的就是ubuntu系统,
Traceback (most recent call last):
  File "/home/byq/Desktop/pysot-master/tools/eval.py", line 146, in <module>
    main()
  File "/home/byq/Desktop/pysot-master/tools/eval.py", line 39, in main
    assert len(trackers) > 0
AssertionError

**Comment by zt1046656665** [comment]
> 我用的就是ubuntu系统,
> Traceback (most recent call last):
> File "/home/byq/Desktop/pysot-master/tools/eval.py", line 146, in
> main()
> File "/home/byq/Desktop/pysot-master/tools/eval.py", line 39, in main
> assert len(trackers) > 0
> AssertionError

额 我还没装ubuntu，，， 装了再看看，别人跟我说是系统问题

**Comment by byq817** [comment]
--tracker_path
../results
--dataset
OTB100
--num
1
--tracker_prefix
'model'
你的参数设这样的吗

**Comment by byq817** [comment]
我ubunt16.04u,估计不是系统原因吧

**Comment by byq817** [comment]
trackers = glob(os.path.join(args.tracker_path,
                                 args.dataset,
                                 args.tracker_prefix,'/*'))
将上边语局改成如下,就可以啦."+"读不到文件报错

**Comment by byq817** [comment]
../resultsv这个值要用绝对路径,可以试试

**Comment by Cassiel829** [comment]
@byq817 你好，请问你有经过test.py生成的结果的.txt文件吗？有的话可以发一下.txt文件的格式吗？

**Comment by byq817** [comment]
198.5,214.5,34,81
194.25510949152576,215.865625896896,35.7450228878286,79.94423405558845
192.6341428703606,215.76753146855287,36.63817597497708,79.84502989236015
189.97318090583371,216.57730130121627,37.4664146585169,80.22461308508085
这是前几行，和OTB中的ground——rect.txt一样

**Comment by Cassiel829** [comment]
@byq817 感谢你的回复。但我的.txt文件的格式也跟otb的gt.txt格式一样，这是我的格式：
![image](https://user-images.githubusercontent.com/57607989/81464077-59ebe880-91f1-11ea-9f95-e0af6080cf22.png)
但运行eval.py后还是报错，报错如下：
![image](https://user-images.githubusercontent.com/57607989/81464092-71c36c80-91f1-11ea-8c34-900c0e71e3bd.png)
![image](https://user-images.githubusercontent.com/57607989/81464098-7851e400-91f1-11ea-8d95-658076fab2f2.png)
请问有什么解决方法吗？谢谢

**Comment by Cassiel829** [comment]
这是报错：
(pysot) F:\Project\pysot-toolkit\bin>python eval.py --dataset_dir F:\Project\pysot-toolkit\dataset\KITTI --dataset KITTI --tracker_result_dir F:\Project\tracking_r
esults --trackers atom
loading KITTI: 100%|████████████████████████████████████████████| 1/1 [00:00<00:00,  4.00it/s, 0001]
eval success:   0%|                                                           | 0/1 [00:01<?, ?it/s]
multiprocessing.pool.RemoteTraceback:
"""
Traceback (most recent call last):
  File "C:\Users\user\Anaconda3\envs\pysot\lib\multiprocessing\pool.py", line 121, in worker
    result = (True, func(*args, **kwds))
  File "F:\Project\pysot-toolkit\pysot\evaluation\ope_benchmark.py", line 44, in eval_success
    tracker_name, False)
  File "F:\Project\pysot-toolkit\pysot\datasets\kitti.py", line 64, in load_tracker
    pred_traj = [list(map(float, x.strip().split(','))) for x in f.readlines()]
  File "F:\Project\pysot-toolkit\pysot\datasets\kitti.py", line 64, in <listcomp>
    pred_traj = [list(map(float, x.strip().split(','))) for x in f.readlines()]
ValueError: could not convert string to float: '296\t161\t158\t130'
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "eval.py", line 63, in <module>
    trackers), desc='eval success', total=len(trackers), ncols=100):
  File "C:\Users\user\Anaconda3\envs\pysot\lib\site-packages\tqdm\std.py", line 1129, in __iter__
    for obj in iterable:
  File "C:\Users\user\Anaconda3\envs\pysot\lib\multiprocessing\pool.py", line 748, in next
    raise value
ValueError: could not convert string to float: '296\t161\t158\t130'
这是我的.txt文件格式：
296,161,158,130
300,162,156,121
293,152,162,118
289,148,163,118
293,152,152,113
288,153,157,114
292,153,152,112
295,156,146,116
284,156,147,110
284,160,149,113
290,159,144,105
281,160,152,112
287,162,141,110
285,157,142,108
284,156,137,109

**Comment by zyc-ai** [comment]
你中间有一个tab，把tab去掉或者在处理当中去掉tab

**Comment by zyc-ai** [comment]
由于本议题没有得到更进一步的提问，我现在将其关闭。
请创建一个新的议题如果你有其他问题。

**Comment by LiPengSun-code** [comment]
作者的路径写法是在ubuntu下的写法，程序未读取到数据结果，所以len(trackers) =0，由判断条件知程序终止    你可以更改eval.py中的
trackers = glob(os.path.join(args.tracker_path,
                                 args.dataset,
                                 args.tracker_prefix+'*'))
将glob（）中的路径改为windows下的绝对路径：例如：trackers = glob("C:\\Users\\***\\Desktop\\pysot\\experiments\\siamrpn_r50_l234_dwxcorr\\results\\OTB100\\model*")
希望对你有帮助

**Comment by LiPengSun-code** [comment]
作者的路径写法是在ubuntu下的写法，程序未读取到数据结果，所以len(trackers) =0，由判断条件知程序终止    你可以更改eval.py中的
trackers = glob(os.path.join(args.tracker_path,
                                 args.dataset,
                                 args.tracker_prefix+'*'))
将glob（）中的路径改为windows下的绝对路径：例如：trackers = glob("C:\\Users\\***\\Desktop\\pysot\\experiments\\siamrpn_r50_l234_dwxcorr\\results\\OTB100\\model*")

**Comment by zj717754140** [comment]
![image](https://user-images.githubusercontent.com/38878734/97175848-1866ee00-17cf-11eb-8b9e-501d6d2600cf.png)
这个参数是什么意思呀，eval.时出现assert len(trackers) > 0 AssertionError 请问一下是什么原因呢

**Comment by lewisli66** [comment]
您好，请问这个问题解决了没，我也遇到这个问题了，很烦恼。该怎么修改@Cassiel829
