### ISSUE TITLE
Where can I find vid.json used in vid/gen_json.py?

### ISSUE THREAD

**Issue by FrogMegane** [STVIR/pysot#347]
I have ran    "python par_crop.py 511 12" to parse VID dataset, and then I want to run "python gen_json.py" 
However, I can't find vid.json, which is needed to run the code.
Where can I find it, or generate it ? very thanks

**Comment by kumatheworld** [comment]
You can run [parse_vid.py](https://github.com/STVIR/pysot/blob/master/training_dataset/vid/parse_vid.py) as in [readme.md](https://github.com/STVIR/pysot/blob/master/training_dataset/vid/readme.md) to get vid.json.

**Comment by HanlynnKe** [comment]
> You can run [parse_vid.py](https://github.com/STVIR/pysot/blob/master/training_dataset/vid/parse_vid.py) as in [readme.md](https://github.com/STVIR/pysot/blob/master/training_dataset/vid/readme.md) to get vid.json.

Hi, when I run gen_json.py I got this error:
```shell
Traceback (most recent call last):
  File "/***/***/***/***/***/gen_json.py", line 69, in <module>
    snippet[frame['img_path'].split('.')[0]] = o['bbox']
NameError: name 'o' is not defined
```
The variable o is defined in a if-statement but used outside of the if-statement. 
Have you ever met this error?

**Comment by kumatheworld** [comment]
@HanlynnKe No. That's maybe because your vid.json is wrong. Make sure you have followed the instructions in readme.md. My vid.json was as large as 1GB.
For the variable o, you can still use it after the if-statement as long as you passed through it before because if-statements in Python do not define scopes. In other words, the code expects you to meet the if-statement condition at least once before getting out of the for-loop.

**Comment by HanlynnKe** [comment]
> @HanlynnKe No. That's maybe because your vid.json is wrong. Make sure you have followed the instructions in readme.md. My vid.json was as large as 1GB.
> For the variable o, you can still use it after the if-statement as long as you passed through it before because if-statements in Python do not define scopes. In other words, the code expects you to meet the if-statement condition at least once before getting out of the for-loop.

Got it. Thanks a lot!

**Comment by FrogMegane** [comment]
Thank you  all, I follow the steps and get train.json finally. However I'm not sure whether the format is correct, since I run the code on Windows10.

The format I originally got looks like this:
{
    "a\\ILSVRC2015_train_00000000": {
        "00": {
            "a\\ILSVRC2015_train_00000000\\000000": [
                323,
                216,
                1050,
                428
            ],.......
}

I modify it to the format as follow ( which is the same as train2017.json in coco dataset)

{
    "a\\ILSVRC2015_train_00000000": {
        "00": {
            "000000": [
                323,
                216,
                1050,
                428
            ],.......
}

**Comment by kumatheworld** [comment]
@FrogMegane Yea your modification is correct. You can also get it by replacing the `'/'` [here](https://github.com/STVIR/pysot/blob/master/training_dataset/vid/parse_vid.py#L44) by `'\'` and running parse_vid.py and gen_json.py again.
The thing is that parse_vid.py assumes the directory separator is `'/'`, which is not the case in Windows.

**Comment by FrogMegane** [comment]
@kumatheworld  Awesome!! Thx for your help, I have training siamrpn_r50_1234_dxcorr on Windows 10 without problem for 2 days.
