### ISSUE TITLE
为什么alexnet只训练四层和五层，不训练前面几层

### ISSUE THREAD

**Issue by aboy2018** [STVIR/pysot#354]
您好，我想问一下，在加载预训练模型时，alexnet只对4，5层训练，为什么不对前面几层训练，是有什么考虑吗；
这是不是意味着开源的最好模型和原始alexnet前面几层参数一样，如果我加载的预训练模型是开源的最好模型，是不是也只需要对4，5层训练，还望大神指教，谢谢。

**Comment by zyc-ai** [comment]
可以，但没必要。

**Comment by zyc-ai** [comment]
由于本议题没有得到更进一步的提问，我现在将其关闭。
请创建一个新的议题如果你有其他问题。
