### ISSUE TITLE
你好，我在运行eval.py遇到如下问题

### ISSUE THREAD

**Issue by Cassiel829** [STVIR/pysot#358]
我使用atom模型测试了KITTI数据集并得到了.txt文件的results，但在运行eval.py的时候遇到了如下报错：
![image](https://user-images.githubusercontent.com/57607989/81413240-ae528200-9177-11ea-853b-bfbfbc5866a1.png)
![image](https://user-images.githubusercontent.com/57607989/81413301-c6c29c80-9177-11ea-9845-a04ef326396f.png)
我测试生成的.txt文件格式如下：
![image](https://user-images.githubusercontent.com/57607989/81413410-f671a480-9177-11ea-870f-d240071e9f34.png)
请问有什么解决方法或者有人可以提供经test.py生成的.txt文件的格式吗？谢谢

**Comment by aboy2018** [comment]
test.py

**Comment by Cassiel829** [comment]
@aboy2018 你好，请问你是怎么解决的，可以详细一点吗？谢谢

**Comment by zyc-ai** [comment]
duplicate with https://github.com/STVIR/pysot/issues/344
