### ISSUE TITLE
How to convert pth model to caffemodel

### ISSUE THREAD

**Issue by aboy2018** [STVIR/pysot#359]
When I try to convert pth model to caffemodel or to pt model，there be have an error.I guess that rpn can't convert.Can you help me.Thank you.
![a](https://user-images.githubusercontent.com/50036961/81466804-f2d92e80-9206-11ea-98df-e7f7eb776514.png)

**Comment by aboy2018** [comment]
result = self.forward(*input, **kwargs)
  File "E:\project\Tracker\pysot-master\tools\pysot\models\model_builder.py", line 82, in forward
    template = data['template'].cuda()
IndexError: too many indices for tensor of dimension 4

**Comment by zyc-ai** [comment]
Duplicate with https://github.com/STVIR/pysot/issues/307
