### ISSUE TITLE
开始训练backbone之后的显存变化

### ISSUE THREAD

**Issue by kongbia** [STVIR/pysot#367]
当训练到某个epoch之后开始训练backbone此时显存占用率会提高很多，但是如果从这个epoch开始断点训练时显存占用用低下来了，请问这是什么原因？
 我碰到的现象是一开始训练GPU只使用了大概4个G左右的显存，然后到了训练backbone时就cuda out of memory，但是我从那个epoch开始断点训练，直到训练结束显存占用又回到了一直是4个G

**Comment by kongbia** [comment]
我发现问题好像在于如果断点刚好在cfg.BACKBONE.TRAIN_EPOCH时，是不会重新运行build_opt_lr将backbone参数加载到优化器中

**Comment by zyc-ai** [comment]
你指的是warmup阶段结束之后显存暴增么？
将warmup设置为0呢？

**Comment by kongbia** [comment]
> 你指的是warmup阶段结束之后显存暴增么？
> 将warmup设置为0呢？

现在已经解决了，我之前的问题是到达TRAIN_EPOCH时，我设计的结构显存超标训练终止，然后我从这个断掉的TRAIN_EPOCH开始resume发现显存又占得很小不会超标。后来发现问题是断点resume时我的config文件没有修改cfg.TRAIN.START_EPOCH，导致backbone的训练参数没有被加载到optimizer中

**Comment by zyc-ai** [comment]
那就好~

**Comment by Jee-King** [comment]
@kongbia  您好， 我也遇到了同样的问题，按照您说的从断掉的epoch开始resume就不会 out of memory. 所以想问一下解决方法就是这样吗，还是更改代码可以解决这个问题？

**Comment by kongbia** [comment]
> @kongbia 您好， 我也遇到了同样的问题，按照您说的从断掉的epoch开始resume就不会 out of memory. 所以想问一下解决方法就是这样吗，还是更改代码可以解决这个问题？

断点训练不但要修改resume还要修改start_epoch，如果正常训练显存超标那断点训练一样也会超标，把batch改小一点就行

**Comment by Jee-King** [comment]
谢谢您的回复。但是我这里显存超标是不正常的情况，因为我试了8块GPU, epoch到第11次就会超出显存。然后我就按照您说的断点从第10个epoch 开始训练，但是start_epoch还是设置的0，没有改过，这样是可以成功训练的。如果改start_epoch，是要将其设成断点的epoch值吗（在我这里就是10）？

**Comment by kongbia** [comment]
> 谢谢您的回复。但是我这里显存超标是不正常的情况，因为我试了8块GPU, epoch到第11次就会超出显存。然后我就按照您说的断点从第10个epoch 开始训练，但是start_epoch还是设置的0，没有改过，这样是可以成功训练的。如果改start_epoch，是要将其设成断点的epoch值吗（在我这里就是10）？

是的，start_epoch设置成你重新训练开始的epoch数，才会加载backbone的参数进行训练。然后要想正常训练，还是要改小单张卡的batch数

**Comment by Jee-King** [comment]
_TRAIN:
    EPOCH: 50
    START_EPOCH: 10
    BATCH_SIZE: 28
    BASE_LR: 0.005
    CLS_WEIGHT: 1.0
    LOC_WEIGHT: 1.2
    RESUME: 'snapshot/checkpoint_e10.pth'_

这样改之后会出现下面的错误

`Traceback (most recent call last):
  File "../../tools/train.py", line 326, in <module>
    main()
  File "../../tools/train.py", line 311, in main
    restore_from(model, optimizer, cfg.TRAIN.RESUME)
  File "/mnt/pysot/pysot/utils/model_load.py", line 88, in restore_from
    optimizer.load_state_dict(ckpt['optimizer'])
  File "/opt/conda/lib/python3.6/site-packages/torch/optim/optimizer.py", line 115, in load_state_dict
    raise ValueError("loaded state dict contains a parameter group "
ValueError: loaded state dict contains a parameter group that doesn't match the size of optimizer's group
`
应该是训练backbone前后优化器不一致导致的。哪里出错了呢？

**Comment by zyc-ai** [comment]
咦我咋把这个给关了

错误：保存checkpoint时没有保存当前epoch，导致每回从零开始训练。
解决方案：将当前epoch保存到checkpoint当中，并在加载的时候读取。

**Comment by mr-xiao-zuo** [comment]
> _火车： EPOCH：50 START_EPOCH：10 BATCH_SIZE：28 BASE_LR：0.005 CLS_WEIGHT：1.0 LOC_WEIGHT：1.2 RESUME：“快照/checkpoint_e10.pth ”_
> 
> 这样改之后会出现以下的错误
> 
> _追溯（最近一次通话最近）： main（）中的 文件“ ../../tools/train.py”，行 326，main中的文件“ ../../tools/train.py”，行311 restore_from（模型，优化器，cfg.TRAIN.RESUME） 文件“ /mnt/pysot/pysot/utils/model_load.py”，线88，在restore_fromoptimizer.load_state_dict （CKPT ['优化']） 文件” /选择中/康达/lib/python3.6/site-packages/torch/optim/optimizer.py”，行115，在load_state_dict中引发 ValueError（“”加载状态dict包含参数组” ValueError：加载状态dict包含不包含的参数组匹配优化程序组的大小_
> 
> 
> start_epoch依然设置为0就不会报错。应该是训练backbone前后优化器交替导致的。哪里出错了呢？

您好，请问您这个问题解决了吗？方便的话，能加您个wechat吗？我的是ZC_Dec26

**Comment by vic01512** [comment]
> _TRAIN: EPOCH: 50 START_EPOCH: 10 BATCH_SIZE: 28 BASE_LR: 0.005 CLS_WEIGHT: 1.0 LOC_WEIGHT: 1.2 RESUME: 'snapshot/checkpoint_e10.pth'_
> 
> 这样改之后会出现下面的错误
> 
> _Traceback (most recent call last): File "../../tools/train.py", line 326, in main() File "../../tools/train.py", line 311, in main restore_from(model, optimizer, cfg.TRAIN.RESUME) File "/mnt/pysot/pysot/utils/model_load.py", line 88, in restore_from optimizer.load_state_dict(ckpt['optimizer']) File "/opt/conda/lib/python3.6/site-packages/torch/optim/optimizer.py", line 115, in load_state_dict raise ValueError("loaded state dict contains a parameter group " ValueError: loaded state dict contains a parameter group that doesn't match the size of optimizer's group_
> 
> 应该是训练backbone前后优化器不一致导致的。哪里出错了呢？ start_epoch 依然设置为0 就不会报错。

您好，解决了吗，我也遇到了这个问题
