### ISSUE TITLE
关于pysot/datasets/dataset.py的代码问题

### ISSUE THREAD

**Issue by Singapore-mor** [STVIR/pysot#369]
你好，我看pysot/datasets/dataset.py这块代码的时候发现
line 103 处的 `get_image_anno`  函数返回的imagepath都是
`.format(frame, track, 'x')` 好像之前crop得到的z的图片并没有用到？
对此比较疑惑，希望得到解答，谢谢

**Comment by Singapore-mor** [comment]
还有个问题是训练的时候是不是数据集用的都是train.json中的数据？那val.json里面的数据是什么时候用的？

**Comment by zyc-ai** [comment]
Duplicate with #365 and #366
