### ISSUE TITLE
Train on pretrained baseline models

### ISSUE THREAD

**Issue by johko** [STVIR/pysot#37]
Hi,
Is there a way to use the pretrained baseline models as base for the training, rather than just the pretrained backbones?
I want to train a model on a new dataset and don't want to retrain it with the provided four.

**Comment by lb1100** [comment]
We will add a pertained parameter to solve this. Please wait. Or you can add it by yourself currently.

**Comment by chenbolinstudent** [comment]
have you add a pertained parameter ? @lb1100

**Comment by serycjon** [comment]
Have you tried to add it yourself @chenbolinstudent ?

**Comment by lb1100** [comment]
Sorry about the late reply. Now added. In `config.yaml`, at the same level of RESUME, add a PRETRAINED: "path/to/pretain/model" will use a pretained model.
