### ISSUE TITLE
GOT-10k数据集解析错误

### ISSUE THREAD

**Issue by AngXinzh** [STVIR/pysot#370]
GOT-10k.json文件读取后产生乱码，好像不是utf-8编码，似乎是Windows-1252？其他.json文件都没有出现此问题。

**Comment by zyc-ai** [comment]
这看上去不是一个编码问题，而是由于json文件当中混入了其他字符串导致的。
作为一个临时解决办法，请先使用这个json：
https://zyc.cowtransfer.com/s/c37424216bea4f

@StrangerZhang 麻烦老哥有空更新一下

**Comment by AngXinzh** [comment]
okok太感谢老哥了！🙏🙏🙏



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: Zhiyuan Chen <notifications@github.com&gt;
发送时间: 2020年6月4日 12:04
收件人: STVIR/pysot <pysot@noreply.github.com&gt;
抄送: AngXinzh <547311247@qq.com&gt;, Author <author@noreply.github.com&gt;
主题: 回复：[STVIR/pysot] GOT-10k数据集解析错误 (#370)





 
这看上去不是一个编码问题，而是由于json文件当中混入了其他字符串导致的。
 作为一个临时解决办法，请先使用这个json：
 https://zyc.cowtransfer.com/s/c37424216bea4f
 
@StrangerZhang 麻烦老哥有空更新一下

**Comment by StrangerZhang** [comment]
Got it
