### ISSUE TITLE
YOUTUBEBB提供的百度网盘链接被封了

### ISSUE THREAD

**Issue by ApolloBian** [STVIR/pysot#373]
Hi, the link in TRAIN.md for the processed data of youtube-bb is not available now. Can you update the link? Thanks.
![image](https://user-images.githubusercontent.com/13659369/85097901-93216a80-b22b-11ea-995a-515cd2908ee7.png)

**Comment by zyc-ai** [comment]
Duplicate with https://github.com/STVIR/pysot/issues/302
