### ISSUE TITLE
bug with __pyx_v_i

### ISSUE THREAD

**Issue by ArturHarutunyan** [STVIR/pysot#376]
toolkit/utils/region.c: In function ‘__pyx_pw_7toolkit_5utils_6region_7Polygon_5__str__’:
toolkit/utils/region.c:4331:70: warning: ‘__pyx_v_i’ may be used uninitialized in this function [-Wmaybe-uninitialized]
 4331 | x_t_10 = PyFloat_FromDouble((__pyx_v_self->_c_region_polygon->x[__pyx_v_i])); if (unlikely(!__pyx_t_10)) __PYX_ERR(0, 141, __pyx_L1_error)

**Comment by zyc-ai** [comment]
It looks like a PyTorch issue.
Could you please provide detailed steps to reproduce this error?

**Comment by zyc-ai** [comment]
Close due to unable to reproduce. 
Please create a new issue should you have other questions.
