### ISSUE TITLE
请问pytorch==1.5.0中损失函数有哪里需要修改？

### ISSUE THREAD

**Issue by dun-123-tudou** [STVIR/pysot#377]
请问pytorch==1.5.0中损失函数有哪里需要修改

**Comment by zyc-ai** [comment]
我映像中就是一个bool的问题，大的没什么变动。

**Comment by zyc-ai** [comment]
由于本议题没有得到更进一步的回复，我现在将其关闭。
请创建一个新的议题如果你有其他问题。
