### ISSUE TITLE
rank

### ISSUE THREAD

**Issue by chenbolinstudent** [STVIR/pysot#39]
when use one node  
File "/home/public/anaconda3/lib/python3.6/os.py", line 669, in __getitem__
    raise KeyError(key) from None
KeyError: 'RANK'

**Comment by chenbolinstudent** [comment]
I want to direct run the train.py file,
how do I set the  -m torch.distributed.launch  -nproc_per_node=8 master_port=2333 --cfg config.yaml in 
the code?

CUDA_VISIBLE_DEVICES=0,1,2,3,4,5,6,7
python -m torch.distributed.launch \
    --nproc_per_node=8 \
    --master_port=2333 \
    ../../tools/train.py --cfg config.yaml

**Comment by chenbolinstudent** [comment]
when :
    #rank, world_size = dist_init()
    logger.info("init done")
    rank = 0

get:
raise(Exception('dist not inited'))
Exception: dist not inited

**Comment by StrangerZhang** [comment]
duplicate #33

**Comment by chenbolinstudent** [comment]
but I want to know how do I set the  -nproc_per_node=8 master_port=2333  in
the code?

**Comment by chenbolinstudent** [comment]
like this format: 

args.dataset = "VOT2018"

**Comment by chenbolinstudent** [comment]
If I want to use one node ,and not use "-m torch.distributed.launch --nproc_per_node=1 --master_port=2333"  ,how should I do ?
