### ISSUE TITLE
UAV123.json中的NaN怎么处理呀

### ISSUE THREAD

**Issue by XiaoMingDe** [STVIR/pysot#396]
在使用tools/test  测试UAV123时候，跑到第二个视频bike2出现错误       
                                                                       # gt_box = [NaN, NaN, NaN, NaN]
  pred_bbox = list(map(int, pred_bbox))      #  ValueError: cannot convert float NaN to integer

**Comment by zyc-ai** [comment]
抱歉我无法理解你的问题，到底是gt_bbox是NaN还是pred_bbox是NaN？

**Comment by zyc-ai** [comment]
由于本议题没有得到更进一步的回复，我现在将其关闭。
请创建一个新的议题如果你有其他问题。
