### ISSUE TITLE
关于backbone训练的问题

### ISSUE THREAD

**Issue by xiaolin13** [STVIR/pysot#398]
backbone只是在ImageNet进行预热，仅仅是提供一个初始模型而不需要在ImageNet上达到某个精度吗？

**Comment by zyc-ai** [comment]
不管是跟踪还是检测，backbone都不需要刷精度.

**Comment by xiaolin13** [comment]
> 不管是跟踪还是检测，backbone都不需要刷精度.

好的谢谢你
