### ISSUE TITLE
关于画面切换的目标追踪目前支持吗

### ISSUE THREAD

**Issue by Anonym91** [STVIR/pysot#40]
提个外行的问题😁尝试了一下，剪了一段视频最初ROI选定人脸，由于画面有切换，不是一直追踪拍摄，切换后目标就乱了，使用SiamMask算法，SiamRPN稍好一点。有时会再捕捉到原目标，有时就走远了~~

![test1](https://user-images.githubusercontent.com/38170974/59265884-dc35fa80-8c78-11e9-8fa5-d184ee33807d.gif)

**Comment by StrangerZhang** [comment]
Try our [siamrpn++ long-term](https://github.com/STVIR/pysot/tree/master/experiments/siamrpn_r50_l234_dwxcorr_lt) version, could be better under this situation.

**Comment by NWPUWRY** [comment]
你好，请问你是如何运行Siammask的demo的？

**Comment by Anonym91** [comment]
> 你好，请问你是如何运行Siammask的demo的？

就是按照markdown里边的demo运行说明操作的

**Comment by NWPUWRY** [comment]
demo 里面只是要求将SiamRPN++训练模型/视频/config文件的路径设置好，并没有看到如何运行SiamMask丫

**Comment by NWPUWRY** [comment]
我尝试在config中将Mask值改为True,之后的报错我就看不太明白了，请问还需要设置什么吗？

**Comment by Anonym91** [comment]
> 我尝试在config中将Mask值改为True,之后的报错我就看不太明白了，请问还需要设置什么吗？

不好意思哈，距离当时试玩这个时间有点久。刚才试着去运行发现原来的运行环境被我搞丢了o(╥﹏╥)o，运行的话我记得是需要下载其他几个文件的，测试数据集和toolkit（这个忘了是否必要）
![image](https://user-images.githubusercontent.com/38170974/64482589-2c483d00-d227-11e9-82db-746f14051c65.png)
运行的python tools/demo.py --config 后的 config.yaml 和 model.path路径应该是testdata里边数据集的路径。
![无标题](https://user-images.githubusercontent.com/38170974/64482635-30c12580-d228-11e9-8ab7-85fd006bf565.png)
其他的好像没有特殊的要求了吧，实在是时间太久忘了，不好意思啊

**Comment by NWPUWRY** [comment]
我一直在rpn的config文件中改mask....mask文件中直接设置好了，sorry

**Comment by sxs11** [comment]
@StrangerZhang @NWPUWRY @Anonym91 
hello，I am a little new to SOT. I run the demo and test. They all occured the error as following:
Traceback (most recent call last):
File "../../tools/test.py", line 15, in
from pysot.core.config import cfg
File "/data1/pysot/pysot/core/config.py", line 86, in
__C.TRAIN.LR.KWARGS = CN(new_allowed=True)
TypeError: __init__() got an unexpected keyword argument 'new_allowed'

so, what's the meaning of new_allowed？ and how should i do? thanks
