### ISSUE TITLE
Could you provide cropped youtube-bb dataset?

### ISSUE THREAD

**Issue by deneb2016** [STVIR/pysot#403]
The original youtube-bb dataset is too large. (approximately 20TB?)
Could you provide cropped youtube-bb dataset?

Thanks in advance.

**Comment by laisimiao** [comment]
> The original youtube-bb dataset is too large. (approximately 20TB?)
> Could you provide cropped youtube-bb dataset?
> 
> Thanks in advance.

In [TRAIN.md](https://github.com/STVIR/pysot/blob/master/TRAIN.md),it has provided cropped youtube-bb dataset download link.

**Comment by zyc-ai** [comment]
Since no further question is asked, I'm closing this issue for now. 
Please create a new issue should you have other questions.
