### ISSUE TITLE
par_crop of coco dataset

### ISSUE THREAD

**Issue by laisimiao** [STVIR/pysot#406]
I have two questions:
- 1、in [line51 of par_crop.py of coco](https://github.com/STVIR/pysot/blob/master/training_dataset/coco/par_crop.py#L51), it shoule be `target_size[0]` and same with **line52** 
- 2、Because in [line106 of datasets.py](https://github.com/STVIR/pysot/blob/master/pysot/datasets/dataset.py#L106), it just uses `x` crop, so why we need to write `z` patch of cropped coco to disk?

**Comment by zyc-ai** [comment]
Duplicate with https://github.com/STVIR/pysot/issues/284
