### ISSUE TITLE
你好，关于siameseFC模型

### ISSUE THREAD

**Issue by byq817** [STVIR/pysot#407]
您好，我是目标跟踪新手，但关注该项目很长时间了，在model Zoo中始终没有SiameseFC的模型，请问后期会更新SiameseFC嘛，还是已经存在此模型，我没有看到？谢谢

**Comment by zyc-ai** [comment]
你只要使用AlexNet bakbone然后去掉新工作添加的内容（比如depthwise互相关）就是SiamFC了呀

**Comment by zyc-ai** [comment]
由于本议题没有得到更进一步的提问，我现在将其关闭。
请创建一个新的议题如果你还有其他问题。
