### ISSUE TITLE
class UPChannelRPN error

### ISSUE THREAD

**Issue by wwdguu** [STVIR/pysot#41]
self.search_cls_conv = nn.Conv2d(feature_in, 
                feature_in * cls_output, kernel_size=3)
self.search_loc_conv = nn.Conv2d(feature_in, 
                feature_in * loc_output, kernel_size=3)
should be :
self.search_cls_conv = nn.Conv2d(feature_in, 
                feature_in, kernel_size=3)
        self.search_loc_conv = nn.Conv2d(feature_in, 
                feature_in, kernel_size=3)

**Comment by StrangerZhang** [comment]
could you give a pull request. Thanks!
