### ISSUE TITLE
Training on custom dataset

### ISSUE THREAD

**Issue by hgaiser** [STVIR/pysot#410]
First of all, thank you for this implementation. I was hoping to train on a custom dataset, but couldn't find a suggested approach for this in the README. What is the best practice for training on my own data? Is there an advised format to convert my data to? Can I find this definition somewhere?

I'm comfortable writing some custom code for parsing my dataset, I was just hoping to get some insight on what the best practices are for custom training processes.

**Comment by zyc-ai** [comment]
> First of all, thank you for this implementation. I was hoping to train on a custom dataset, but couldn't find a suggested approach for this in the README. What is the best practice for training on my own data? Is there an advised format to convert my data to? Can I find this definition somewhere?
Have you checkouted the [TRAIN](https://github.com/STVIR/pysot/blob/master/TRAIN.md)?

**Comment by hgaiser** [comment]
@zyc-ai I have, but it only mentions training on existing datasets:

- VID
- YOUTUBEBB
- DET
- COCO

I would like to train on my own dataset. I looked into using one of the existing formats, like VID, but it doesn't feel like this is the intended way. There are some assumptions about directory structure and file naming conventions (every filename should be an integer for example).

**Comment by zyc-ai** [comment]
Ahhh yes, it would be nice if there are instructions for custom dataset. 
For now, the easiest way could be write your own subdataset class and add it to dataset. Another easy way is to just reorg dataset like ybb or vid and than use provided directly.
