### ISSUE TITLE
pysot训练

### ISSUE THREAD

**Issue by StrugglingForBetter** [STVIR/pysot#420]
我是参照这个链接训练的：
https://github.com/STVIR/pysot/blob/master/TRAIN.md

用4块GPU的服务器训练，

CUDA_VISIBLE_DEVICES=0,1,2,3
python -m torch.distributed.launch \
    --nproc_per_node=4 \
    --master_port=2333 \
    ../../tools/train.py --cfg config.yaml

只有单个node的这个命令可以正常训练，但是很慢

如果用下面这个就会一直卡住，然后不动了
CUDA_VISIBLE_DEVICES=0,1,2,3
python -m torch.distributed.launch \
    --nnodes=2 \
    --node_rank=0 \
    --nproc_per_node=4 \
    --master_addr=192.168.1.1 \  # adjust your ip here
    --master_port=2333 \
    ../../tools/train.py

请问是什么原因？我还是不太明白nnodes这个参数到底是什么意思？是不是因我的服务器本来就只有一个Node？

请问如何查询有多少个Node？

**Comment by wWHWw** [comment]
感觉这个node应该是对应服务器数量的
顺便问一句，您训练过程中会出现Nonetype has no attribute .shape这种由于不能正确找到图片引发的问题吗？
您的数据集处理步骤尤其是ytbb是怎样的

**Comment by StrugglingForBetter** [comment]
> 感觉这个node应该是对应服务器数量的
> 顺便问一句，您训练过程中会出现Nonetype has no attribute .shape这种由于不能正确找到图片引发的问题吗？
> 您的数据集处理步骤尤其是ytbb是怎样的

应该是，我当时可能用的老的数据，所以出问题了，后来下载了新的ytbb数据就没事了
就是按照train.md里面的来就行了

**Comment by wWHWw** [comment]
> > 感觉这个node应该是对应服务器数量的
> > 顺便问一句，您训练过程中会出现Nonetype has no attribute .shape这种由于不能正确找到图片引发的问题吗？
> > 您的数据集处理步骤尤其是ytbb是怎样的
> 
> 应该是，我当时可能用的老的数据，所以出问题了，后来下载了新的ytbb数据就没事了
> 就是按照train.md里面的来就行了

我也是按照train.md 里面处理的coco 和 VID，yt_bb是直接用的百度云下载的数据和里面提供的train.json 文件，但是我还是会报这个问题，我前天还重新下了一遍。我现在就很困惑。
而且我这跑起来每次logger.info展现训练速度和实时损失的时候，那个ETA越来越长，而且能明显感受到他输出训练信息的间隔也变长了，我现在都在怀疑是不是我的设备跑不了了

**Comment by StrugglingForBetter** [comment]
是设备的问题，我也是，所以似乎不能同时训练4个数据集，我都是分开训练的，好麻烦

**Comment by wWHWw** [comment]
> 是设备的问题，我也是，所以似乎不能同时训练4个数据集，我都是分开训练的，好麻烦

请教一下四个数据集怎么分开训练？读取前一个数据集训练完的pth吗？那学习率怎么办？
我比较菜=-=
