### ISSUE TITLE
TRAIN.md

### ISSUE THREAD

**Issue by XiaoCode-er** [STVIR/pysot#43]
TRAIN.md
Testing
python -u ../tools/test.py \
        --snapshot {} \
	--config config.py \

should be:
python -u ../../tools/test.py \
        --snapshot {} \
	--config config.yaml \

**Comment by StrangerZhang** [comment]
Thanks!

**Comment by XiaoCode-er** [comment]
python -u ../tools/test.py 
should be:
python -u ../../tools/test.py
