### ISSUE TITLE
Cannot reproduce the results of config "https://github.com/STVIR/pysot/blob/master/experiments/siamrpn_r50_l234_dwxcorr_8gpu/config.yaml"

### ISSUE THREAD

**Issue by Singingkettle** [STVIR/pysot#441]
After training model by the config file "siamrpn_r50_l234_dwxcorr_8gpu/config.yaml", the model saved in the 20 epoch has an EAO "0.349", which is not the same as the official "0.415". What's the reason?
![image](https://user-images.githubusercontent.com/14244102/94983825-e28c6c00-0578-11eb-9e47-e754d5cf80be.png)

**Comment by zyc-ai** [comment]
Duplicates with https://github.com/STVIR/pysot/discussions/94
