### ISSUE TITLE
.json file for GOT-10k is missing

### ISSUE THREAD

**Issue by MARMOTatZJU** [STVIR/pysot#45]
The following error is encountered during (file _pysot/testing_dataset/GOT-10k/GOT-10k_new.json_, line 60)
```with open(os.path.join(dataset_root, name+'_new.json'), 'r') as f:```
This is due to the missing file _GOT-10k_new.json_ which can neither be found on BaiduYun disk nor Google Drive. Would you mind upload this missing file? Thanks in advance.

**Comment by StrangerZhang** [comment]
Upload to BaiduYun, you can download it now. Also pull the repo, there are some bugs fixed
