### ISSUE TITLE
When I set__ C. TRAIN.EXEMPLAR_ SIZE=512.. my loc loss is always 0

### ISSUE THREAD

**Issue by XuShoweR** [STVIR/pysot#450]
When I set__ C. TRAIN.EXEMPLAR_ SIZE=512，__ C. TRAIN.SEARCH_ SIZE=800，__ C. TRAIN.OUTPUT_ When size = 37, my loc loss is always 0. What other parameters do I need to change

**Comment by ZhiyuanChen** [comment]
Could you provide more details, e.g. the config file used for training.

**Comment by XuShoweR** [comment]
I solved this problem by using pretrained model
