### ISSUE TITLE
tb_writer.add_graph(model,dummy_input)  TypeError: 'GraphDef' object does not support indexing

### ISSUE THREAD

**Issue by FMsunyh** [STVIR/pysot#46]
Hi;
I want to save the model graph, but it occur errors when I save it via tb_writer.add_graph.
it seems like this issue： https://github.com/lanpa/tensorboardX/issues/220

![image](https://user-images.githubusercontent.com/9877644/59400472-1cf15900-8dca-11e9-854a-b791ddd1acd9.png)

who can help me to visual network structure?

**Comment by yc-zc** [comment]
https://github.com/lanpa/tensorboardX/issues/220#issuecomment-508325874

**Comment by yc-zc** [comment]
Since no further question is asked, I'm closing it for now.
Please reopen it or create a new issue if you have further question.
