### ISSUE TITLE
about train

### ISSUE THREAD

**Issue by longqiwf** [STVIR/pysot#47]
Hi, I want to train the alexnet with your training code on VID dataset, is there any backbone use the same structure as SiamRPN++? Means random shift and depth-wise cross correlation used even in alexnet.

**Comment by StrangerZhang** [comment]
We already provided, the (alexnet experiment)[https://github.com/STVIR/pysot/tree/master/experiments/siamrpn_alex_dwxcorr_16gpu] use random shift and depth-wise cross correlation

**Comment by longqiwf** [comment]
yes, but the model is trained on four dataset, I just want to train on VID. Thanks for your reply.

**Comment by StrangerZhang** [comment]
Delete [line 68,69,70](https://github.com/STVIR/pysot/blob/b1cd90ccf166a2aa083f2eb3ce05db144ee57742/experiments/siamrpn_alex_dwxcorr_16gpu/config.yaml#L68), can training on vid, you should also change the VIDEOS_PER_EPOCH parameter

**Comment by longqiwf** [comment]
Thanks, have you ever tried train the siamfc on VID and YoutubeBB? How is the performance on OTB2015? I know siamfc  gets 0.58 success on that, and it just used VID.

**Comment by longqiwf** [comment]
Hi, I didn't find the VIDEOS_PER_EPOCH parameter, where is it?

**Comment by StrangerZhang** [comment]
[config.py](https://github.com/STVIR/pysot/blob/b1cd90ccf166a2aa083f2eb3ce05db144ee57742/pysot/core/config.py#L162)

**Comment by chenbolinstudent** [comment]
when only train on coco,change the VIDEOS_PER_EPOCH parameter to which?
what is the meaning of __C.DATASET.VIDEOS_PER_EPOCH = 600000 ?
and when train on other?

**Comment by GengMingjin2** [comment]
@longqiwf  Hello, have you figured out the parameter VIDEOS_PER_EPOCH when you train the network only on VID dataset? I just tried the default setting(600000) and the training time tends to be 13 days...Thank you!

**Comment by chenbolinstudent** [comment]
@StrangerZhang 
when only train coco or other dataset,what is the setting if VIDEOS_PER_EPOCH ? and how to change other super parameters?
