### ISSUE TITLE
 KeyError(key) from None KeyError: 'RANK'

### ISSUE THREAD

**Issue by chenbolinstudent** [STVIR/pysot#48]
请问如何不通过命令行运行train.py?目前我直接在运行test.py 可以，但是直接运行train.py:
File "/home/public/anaconda3/lib/python3.6/os.py", line 669, in getitem
raise KeyError(key) from None
KeyError: 'RANK'

请问如何在代码中设置：
CUDA_VISIBLE_DEVICES=0,1,2,3,4,5,6,7
python -m torch.distributed.launch 
--nproc_per_node=8 
--master_port=2333 
../../tools/train.py --cfg config.yaml
中的值，使得可以直接在pycharm运行train.py，
谢谢您的回复。

**Comment by Hevans123** [comment]
same question

**Comment by lb1100** [comment]
Duplicate of #42. Please don't post same issues.
