### ISSUE TITLE
能否提供百度云链接下载

### ISSUE THREAD

**Issue by zgq91** [STVIR/pysot#5]
您好!
       非常感谢你们开源工作,不知道能否提供百度云链接下载;国内谷歌云下载很不稳定,经常下载失败。

**Comment by foolwood** [comment]
链接: https://pan.baidu.com/s/1GB9-aTtjG57SebraVoBfuQ 提取码: j9yb 

All models available for download through this document are licensed under [the Creative Commons Attribution-ShareAlike 3.0 license](https://github.com/STVIR/pysot/blob/master/MODEL_ZOO.md).

**Comment by lzy19974** [comment]
> 链接：[https](https://pan.baidu.com/s/1GB9-aTtjG57SebraVoBfuQ)：//pan.baidu.com/s/1GB9-aTtjG57SebraVoBfuQ提取码：j9yb
> 
> 可通过本文档下载的所有型号均以[Creative Commons Attribution-ShareAlike 3.0许可证授权](https://github.com/STVIR/pysot/blob/master/MODEL_ZOO.md)。

3q.
