### ISSUE TITLE
How can i fix the Error: AssertionError……/testing_dataset/VOT2018/ants1/color/00000001.jpg

### ISSUE THREAD

**Issue by EEEEEREN** [STVIR/pysot#500]
I want testing tracker : Siammask ,  i followed the step and i can run demo
but when i try to test tracker, this step
![QQ截图20210223134053](https://user-images.githubusercontent.com/67900018/108806481-c4351480-75dc-11eb-86c1-8505382ca910.png)

and there is an error 
AssertionError……/testing_dataset/VOT2018/ants1/color/00000001.jpg
![阿里旺旺图片20210223133921](https://user-images.githubusercontent.com/67900018/108806435-a071ce80-75dc-11eb-84dc-e3b50c4a25ef.jpg)

**Comment by ZhiyuanChen** [comment]
Could you confirm if the presented image is all right?

**Comment by EEEEEREN** [comment]
> Could you confirm if the presented image is all right?

我知道了，我有个文件夹命名错了
