### ISSUE TITLE
what about stop at 'build dataset done'...

### ISSUE THREAD

**Issue by EEEEEREN** [STVIR/pysot#501]
I try to train SiamMask_r50_l3, but when i followed the step in 'train.md' and put the dataset in their folder respectively 
when i try to start,  it shows the picture as followed
![1](https://user-images.githubusercontent.com/67900018/109166431-a8399a80-77b7-11eb-9ad8-be0bace7781a.png)
![2](https://user-images.githubusercontent.com/67900018/109166438-a96ac780-77b7-11eb-95a8-366d90db3784.png)
![3](https://user-images.githubusercontent.com/67900018/109166442-aa9bf480-77b7-11eb-99b2-d258b1d5a5d3.png)
and it is 'stucked' at 'build dataset done' from 18:00 pm  to now... =.=
what i want to know is that is there an Error or something else ..

我想训练SiamMask，我按照指示把数据集都放在了相应的文件夹之后，就按照"Single node, multiple GPUs" 那一段去开始训练，结果现在一直停在了'build dataset done'， 有没有好心的大佬告诉我这是咋回事....

PS：我只有一块GPU，这一条命令：CUDA_VISIBLE_DEVICES=0,1,2,3,4,5,6,7 这里我应该是填0吗
PPS：有谁知道训练时候的终端界面是什么样子吗...搞了好几个礼拜了，demo测试都搞稳妥了，就是训练各种报错QAQ

**Comment by ZhiyuanChen** [comment]
If you have only one GPU, you should follow Single node, single GPU.

**Comment by EEEEEREN** [comment]
> If you have only one GPU, you should follow Single node, single GPU.

CUDA_VISIBLE_DEVICES=0,1,2,3,4,5,6,7
python -m torch.distributed.launch \
    --nproc_per_node=8 \
    --master_port=2333 \
    ../../tools/train.py --cfg config.yaml

Would u mind teaching me how to set the code with 1node, 1GPU, thx a lot 🙏

**Comment by ZhiyuanChen** [comment]
> Would u mind teaching me how to set the code with 1node, 1GPU, thx a lot 🙏

Can I suggest you read the documents of PyTorch distributed training first before using it?
