### ISSUE TITLE
where is pretrained backbone 'mobilenetv2' , i only find the 'resnet50.model' in google Drive

### ISSUE THREAD

**Issue by EEEEEREN** [STVIR/pysot#509]
I want to train (not test) SiamRPN++ based on Mobilenet, but i cant find the pretrain model like 'resnet50.model'  in google drive.
so, how should i get mobilenetV2.model ,   in paper of MobilenetV2? or other place ?

**Comment by ZhiyuanChen** [comment]
I don't think it is provided.

**Comment by EEEEEREN** [comment]
how should i do to train SiamRPN++ with MobilenetV2 😂

**Comment by ZhiyuanChen** [comment]
I believe enough details have been given in the paper
