### ISSUE TITLE
when only train the coco 

### ISSUE THREAD

**Issue by chenbolinstudent** [STVIR/pysot#52]
how the set config.yaml?
and other operation

**Comment by shenfanML** [comment]
the det, vid, and yt_bb dataset is so large and the network speed is so slow, I want to know how to train the only dataset coco

**Comment by bigbigrabbit** [comment]
find out config.yaml and you will know how to do it

**Comment by bigbigrabbit** [comment]
you can delete the other datesets' name on config.yaml

**Comment by chenbolinstudent** [comment]
can you offer the result of only train coco?
thanks

**Comment by shenfanML** [comment]
I trained only the coco dataset and it succeed. The result .pth file is too large(more than 2GB).

**Comment by chenbolinstudent** [comment]
@shenfanML 
the result is poor

**Comment by ny222333** [comment]
> I trained only the coco dataset and it succeed. The result .pth file is too large(more than 2GB).

How long did it take you  when trained only the coco dataset
