### ISSUE TITLE
单卡训练问题

### ISSUE THREAD

**Issue by hongtaofly** [STVIR/pysot#559]
由于整个实验室共用两个卡，而其他同门的任务默认卡0，导致出现卡0显存已满，卡1还有很多显存的情况。而算法在第11个epoch开始解冻backbone时，显存溢出，所以请问单卡训练时训练命令是怎样的？

**Comment by DDuranin** [comment]
同问

**Comment by desperate1998** [comment]
在config.py里面设置__C.TRAIN.RESUME = 'snapshot/checkpoint_e10.pth'

**Comment by WhXl** [comment]
为什么没有训练的例子呢

**Comment by ZhiyuanChen** [comment]
建议使用CUDA_VISIBLE_DEVICES指定卡1训练

**Comment by WhXl** [comment]
好的，谢谢



---原始邮件---
发件人: "Zhiyuan ***@***.***&gt;
发送时间: 2022年1月26日(周三) 中午1:17
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [STVIR/pysot] 单卡训练问题 (Issue #559)




 
建议使用CUDA_VISIBLE_DEVICES指定卡1训练
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by DDuranin** [comment]
谢谢啦 确实是按照您的方法，已经实现了

2022-01-26 13:17:49"Zhiyuan Chen" ***@***.***>写道：

建议使用CUDA_VISIBLE_DEVICES指定卡1训练

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
