### ISSUE TITLE
ModuleNotFoundError: No module named 'Cython'

### ISSUE THREAD

**Issue by ssshcj** [STVIR/pysot#57]
run python setup.py build_ext --inplace
and get an error:
Traceback (most recent call last):
File "setup.py", line 3, in <module>
from Cython.Build import cythonize
ModuleNotFoundError: No module named 'Cython'

I have installed cython, but there are still errors ,my cython is cython-0.29.10

**Comment by lb1100** [comment]
There must be something wrong with your environment. Please check which python you are using. Is that the same Python which has installed python?
