### ISSUE TITLE
sorry, i ues the wrong model

### ISSUE THREAD

**Issue by zhanght021** [STVIR/pysot#58]

**Comment by StrangerZhang** [comment]
Which model did you use? The model for vot should be siamrpn_r50_l234_dwxcorr.

**Comment by zhanght021** [comment]
> Which model did you use? The model for vot should be siamrpn_r50_l234_dwxcorr.
@StrangerZhang 
 this model :siamrpn_alex_dwxcorr,

**Comment by StrangerZhang** [comment]
Which config.yaml did you use?

**Comment by zhanght021** [comment]
@StrangerZhang 

in folder pysot/experiments/siamrpn_alex_dwxcorr

I use python3.6 and pytorch1.1.0,

in VOT2018 the gap between the result i got and published in model zoo is so big

**Comment by lb1100** [comment]
Maybe. We haven't tested 1.1 right now. But I think it's more likely you are using the wrong model. (eg. are you using otb model?). 
And may I ask what GPU devices you are using? Different generation of GPU may affect the tracking results since the error is cummulated after long frames. And we are testing on 10th generation of GPU (eg. 1080TI, TITAN XP).

**Comment by zhanght021** [comment]
@lb1100 1080TI
@StrangerZhang 
very very sorry to you , i used the wrong model (OTB model)    very sorry

**Comment by chenbolinstudent** [comment]
@lb1100
 the number of GPU and the batchsize will influence the result?
what is the result of  TITAN 12 G with 3 GPU  of VOT2018?

**Comment by chenbolinstudent** [comment]
@lb1100
the number of GPU and the batchsize will influence the result?
what is the result of TITAN 12 G with 3 GPU of VOT2018 of resnet?

**Comment by chenbolinstudent** [comment]
@lb1100
the number of GPU and the batchsize will influence the result?
what is the result of TITAN 12 G with 3 GPU of VOT2018?(old is 0.414)

**Comment by lb1100** [comment]
You need to test on your own. We can't provide configs for every combinations. Our experiments will be conducted mainly on 8/16 1080TIs.
