### ISSUE TITLE
How to write a json file for a new dataset

### ISSUE THREAD

**Issue by lawpdas** [STVIR/pysot#6]
I want to test trackers on VOT2019 dataset. Can you tell me how to write a json file for the new dataset?

**Comment by StrangerZhang** [comment]
You can download th VOT2019.json in [baidupan](https://pan.baidu.com/s/1js0Qhykqqur7_lNRtle1tA)

**Comment by lawpdas** [comment]
Thanks! But there is not json file for long-term challenge.

**Comment by cappuccino19** [comment]
感觉OTB100的json 跟数据库对不上呢
