### ISSUE TITLE
torch.distributed.init_process_group  

### ISSUE THREAD

**Issue by chenbolinstudent** [STVIR/pysot#60]
I set rank=0 ,and run train.py in pycharm ,

get :
RuntimeError: rank is not set but it is required for env:// init method at /opt/conda/conda-bld/pytorch_1524590031827/work/torch/lib/THD/process_group/General.cpp:17

can you offer the method without distributed?
怎样不通过分布式运行代码？

**Comment by lb1100** [comment]
Currently this code only support distributed version.
