### ISSUE TITLE
about pretraied model: why mobilenetv2's model is slower than alexnet's?

### ISSUE THREAD

**Issue by dypromise** [STVIR/pysot#61]
Hi, 
In pretrained Model-Zoo, I see that the mobilenetv2 based model is 87fps while alexnet based model is 180 fps, Why alex is faster than mobilenetV2? and I observed that no mobilenetV2 train config file exists?

**Comment by lb1100** [comment]
Is there any reason that mobilenet should be faster than alexnet? And as for train config for mobilenet, we will update recently.
