### ISSUE TITLE
some questions on test and training

### ISSUE THREAD

**Issue by xi-mao** [STVIR/pysot#62]
1. I use demo.py  to test  siamrpn_alex_dwxcorr  model。After setting config and model with [https://drive.google.com/drive/folders/1t62x56Jl7baUzPTo0QrC4jJnwvPZm-2m](url) 。 the code has error like this:
*********************************************
Traceback (most recent call last):
  File "tools/demo.py", line 111, in <module>
    main()
  File "tools/demo.py", line 62, in main
    cfg.merge_from_file(args.config)
  File "/home/ximao/.local/lib/python3.5/site-packages/yacs/config.py", line 213, in merge_from_file
    self.merge_from_other_cfg(cfg)
  File "/home/ximao/.local/lib/python3.5/site-packages/yacs/config.py", line 217, in merge_from_other_cfg
    _merge_a_into_b(cfg_other, self, self, [])
  File "/home/ximao/.local/lib/python3.5/site-packages/yacs/config.py", line 460, in _merge_a_into_b
    _merge_a_into_b(v, b[k], root, key_list + [k])
  File "/home/ximao/.local/lib/python3.5/site-packages/yacs/config.py", line 473, in _merge_a_into_b
    raise KeyError("Non-existent config key: {}".format(full_key))
KeyError: 'Non-existent config key: RPN.WEIGHTED'
***********************************************

the error said that the file pysot/cror/config.py dosen't has key 'RPN.WEIGHTED', but in pysot/cror/config.py  has been set  like this :

__C.RPN = CN()
__C.RPN.TYPE = 'MultiRPN'

__C.RPN.KWARGS = CN(new_allowed=True)
`
I think  the last sentence allows to accept new parameter， but it is useless。I don't understand why。I gusse that it is because my python version  3.5。but i don't test on 3.6 or 3.7

2.I was training  siamrpn_alex_dwxcorr_16gpu model。 I use two GTX1080 GPU training on vid and ytbb，beacuse SiamRPN training on the two datasets。but  It's vary slow， So can i ask how long it token you to training  siamrpn_alex_dwxcorr_16gpu model if using 16GPUS。

3.besides I don't understand the difference between siamrpn_alex_dwxcorr and   siamrpn_alex_dwxcorr_16gpu 。 I think it just differ in using gpu numbers。but when i training siamrpn_alex_dwxcorr with pertrained model  alexnet-bn.pth 。it appear error 
"Error(s) in loading state_dict for ModelBuilder  Missing key(s) in state_dict: "backbone.features.0.weight", "backbone.features.0.bias", "backbone.features.1.weight","
when load model alexnet-bn.pth。 it seems that siamrpn_alex_dwxcorr and   siamrpn_alex_dwxcorr_16gpu has different network structures。 

I don’t know why。can anyone explain to me ，thanks。

**Comment by StrangerZhang** [comment]
1. You should use the config.yaml in our repo, not the file in google driver. There are some changes after the recent updates. Sorry for the inconvenience.
2. 16 GPUs takes about 12hrs.
3.  The siamrpn_alex_dwxcorr is used for inference. siamrpn_alex_dwxcorr_16gpu is used for training

**Comment by xi-mao** [comment]
> 1. You should use the config.yaml in our repo, not the file in google driver. There are some changes after the recent updates. Sorry for the inconvenience.
> 2. 16 GPUs takes about 12hrs.
> 3. The siamrpn_alex_dwxcorr is used for inference. siamrpn_alex_dwxcorr_16gpu is used for training

thank you vary much,it meets my suppose。
