### ISSUE TITLE
RunTimeError：Connection reset by peer

### ISSUE THREAD

**Issue by zhanght021** [STVIR/pysot#63]
I meet a question again， when i use 8 GPU（GTX1080Ti） to train, it will appear this error

and i change the code using DataParallel to train， it will not appear this error, but the speed is very slow

I do not know where is the problem 
![943895768](https://user-images.githubusercontent.com/19857363/59730143-d7bea280-9273-11e9-9ebd-0135a3294043.jpg)

**Comment by lb1100** [comment]
If you are using DataParallel, it shouldn't call any functions from `distributed.py`. You should check your code.

**Comment by zhanght021** [comment]
@lb1100 yes ,i delete some code to use DataParallel, and i train in coco2017, GOT-10K and VID dataset, and the eao in VOT2016 can reach 0.38, but the training speed is very slow, 
and i use the origin code you published, it will get the above error，

**Comment by zhanght021** [comment]
i do not know where is the problem

**Comment by lb1100** [comment]
Maybe train PyTorch 1.0 will work. There seems to be some problem about DataLoader in PyTorch 0.4.1 [Always get error "ConnectionResetError: [Errno 104] Connection reset by peer" #9127](https://github.com/pytorch/pytorch/issues/9127)

**Comment by pobingwanghai** [comment]
@lb1100 so you guys really use the 0.4.1 or use the pytorch 1.0 for training?

**Comment by pobingwanghai** [comment]
@lb1100 update to 1.0.1 won't solve this problem

**Comment by zhanght021** [comment]
i change the torch to 1.0version， and  all is okay ，the problem is solved

**Comment by ZhaoZeng101** [comment]
RuntimeError: Input type (torch.cuda.FloatTensor) and weight type (torch.FloatTensor) should be the same

**Comment by ZhaoZeng101** [comment]
How can i set parameter to running tools/demo.py without GPU
