### ISSUE TITLE
QObject::moveToThread: Current thread (0x55afd0e09f40) is not the object's thread (0x55afd2d621e0). Cannot move to target thread (0x55afd0e09f40)  QPixmap: Must construct a QApplication before a QPaintDevice

### ISSUE THREAD

**Issue by lazyfan** [STVIR/pysot#68]
when  i run demo.py 
```
python tools/demo.py \
    --config experiments/siamrpn_alex_dwxcorr/config.yaml \
    --snapshot experiments/siamrpn_alex_dwxcorr/model.pth \
    --video demo/bag.avi
```

QObject::moveToThread: Current thread (0x55afd0e09f40) is not the object's thread (0x55afd2d621e0).
Cannot move to target thread (0x55afd0e09f40)

QPixmap: Must construct a QApplication before a QPaintDevice

**Comment by MichaelXin** [comment]
same problem...
any solution?

**Comment by MichaelXin** [comment]
Select a ROI and then press SPACE or ENTER button!
Cancel the selection process by pressing c button!

**Comment by czy-orange** [comment]
I had almost the same problem and error message and I installed PyQt and it worked.

**Comment by yc-zc** [comment]
Since no further question is asked, I'm closing it for now.
Please reopen it or create a new issue if you have further question.
