### ISSUE TITLE
评价多个算法性能

### ISSUE THREAD

**Issue by kongbia** [STVIR/pysot#7]
eval.py载入多个算法时
    trackers = glob(os.path.join(args.tracker_path, args.dataset, args.tracker_prefix+'*'))
    trackers = [x.split('/')[-1] for x in trackers]
这样语法会存在错误吧，是不是应该改成
    trackers = args.tracker_prefix.split(" ")

**Comment by StrangerZhang** [comment]
Currently only support multiple trackers with the same prefix.
