### ISSUE TITLE
DET

### ISSUE THREAD

**Issue by chenbolinstudent** [STVIR/pysot#74]
ty@N606-TITAN32:/mnt/cbl/det$ ln -sfb $PWD/ILSVRC/Annotations/DET/train/ILSVRC2013_train /mnt/cbl/det/ILSVRC/Annotations/DET/train/a
ln: failed to create symbolic link '/mnt/cbl/det/ILSVRC/Annotations/DET/train/a': No such file or directory

should I change the ILSVRC2015 to ILSVRC ?is it suitable?

**Comment by lb1100** [comment]
`a, b, c, d, e` represent `train/ILSVRC2015_VID_train_0000` ~ `train/ILSVRC2015_VID_train_0003` and `val` respectively. I think it's the same as SiamFC.
