### ISSUE TITLE
INSTALL.md的最后一步，找不到vcvarsall.bat

### ISSUE THREAD

**Issue by zhujinchao123** [STVIR/pysot#75]
python setup.py build_ext --inplace运行部不了
报错如下：
running build_ext
building 'toolkit.utils.region' extension
error: Unable to find vcvarsall.bat

**Comment by lb1100** [comment]
Maybe this will help. [error: Unable to find vcvarsall.bat
](https://stackoverflow.com/questions/2817869/error-unable-to-find-vcvarsall-bat/38477649)
