### ISSUE TITLE
ImageNet  COCO , ImageNet DET , ImageNet VID, and YouTube-BoundingBoxes Dataset

### ISSUE THREAD

**Issue by chenbolinstudent** [STVIR/pysot#76]
resnet50.model is trained from only ImageNet ?
siamrpn_r50_l234_dwxcorr/model.pth is trained from ImageNet  COCO , ImageNet DET , ImageNet VID, and YouTube-BoundingBoxes Dataset ?

**Comment by lb1100** [comment]
yes.

**Comment by chenbolinstudent** [comment]
when do you offer the baidu pan of YouTube-BoundingBoxes Dataset?
thanks
@ lb1100

**Comment by chenbolinstudent** [comment]
when do you offer the baidu pan of YouTube-BoundingBoxes Dataset?
thanks
@lb1100
