### ISSUE TITLE
ModuleNotFoundError: No module named 'pysot'

### ISSUE THREAD

**Issue by TeslaHua** [STVIR/pysot#8]
你好，我进入pysot的虚拟环境之后，运行你的tools/test.py的时候，出现了：

Traceback (most recent call last):
  File "../../tools/test.py", line 13, in <module>
    from pysot.core.config import cfg
ModuleNotFoundError: No module named 'pysot'

我按照你的教程INSTALL.md进行了相关依赖包的安装。我设置了：　
export PYTHONPATH=/home/username/anaconda3/lib/python3.7/site-packages:$PYTHONPATH

README中说的：export PYTHONPATH=/path/to/PySOT:$PYTHONPATH　是什么意思呢，/path/to/PySOT具体指的哪个路径？是anaconda里面的pysot虚拟环境路径还是git clone下来的工程里面的pysot路径？

**Comment by linkinpark213** [comment]
你好，/path/to/PySOT指的是你clone的PySOT代码路径。例如我在`/home/linkinpark213/Source`使用`git clone`命令下载代码，则`/home/linkinpark213/Source/pysot`即为我的`/path/to/PySOT`路径。执行
```
export PYTHONPATH=/home/linkinpark213/Source/pysot:$PYTHONPATH
```
即可。

PS：这个目录下会有一个叫做pysot的文件夹，这也就是`ModuleNotFoundError: No module named 'pysot'`中的`pysot`模块。

**Comment by TeslaHua** [comment]
@linkinpark213 不好意思，我按照你说的执行了，还是报同样的错误。我发现只有把你说的pysot模块放到/usr/local/lib/python3.7/lib/python3.7/site-packages  执行才不会报缺少pysot模块的错误。
但是又报了缺少 torch 模块的错误。

而且我在conda的base环境下，python之后import torch没错，但是进入conda activate pysot虚拟环境之后就报No module named 'torch'的错误。

**Comment by linkinpark213** [comment]
`conda activate pysot`的作用是切换到一个叫做pysot的环境下。看起来你在这个环境下并没有安装PyTorch框架之类的依赖。

如果你是按照[INSTALL.md](https://github.com/STVIR/pysot/blob/master/INSTALL.md)执行的，那么可能是在`conda create --name pysot python=3.7`步骤后忘了先`conda activate pysot`再执行后续的安装步骤？

**Comment by TeslaHua** [comment]
@linkinpark213 是不是不需要安装python3.7，只需要安装python3.7版本的anaconda就可以了

**Comment by linkinpark213** [comment]
@TeslaHua 是的，Python3.7版本的Anaconda在base环境下默认使用自带的Python3.7，但是它同样可以用来创建使用其他版本Python的环境。因此，在创建环境（`conda create`）的时候是需要指定新环境所使用的Python版本号的（也就是后边那个`python=3.7`参数），若不指定则会按Anaconda自带的默认版本。

**Comment by TeslaHua** [comment]
@linkinpark213 好的，谢谢你。可能是版本冲突了，我重新弄一下。

**Comment by TeslaHua** [comment]
@linkinpark213 不好意思，我重新打开了这个问题。昨天我重新在pysot的虚拟环境下安装了其他依赖库，下面是我在pysot环境下的conda list，改装的依赖应该都装了：
```
# Name                    Version                   Build  Channel
blas                      1.0                         mkl    defaults
ca-certificates           2019.1.23                     0    defaults
certifi                   2019.3.9                 py37_0    defaults
cffi                      1.12.3           py37h2e261b9_0    defaults
colorama                  0.4.1                    pypi_0    pypi
cuda90                    1.0                  h6433d27_0    pytorch
cycler                    0.10.0                   pypi_0    pypi
cython                    0.29.7           py37he6710b0_0    defaults
freetype                  2.9.1                h8a8886c_1    defaults
intel-openmp              2019.3                      199    defaults
jpeg                      9b                   h024ee3a_2    defaults
kiwisolver                1.1.0                    pypi_0    pypi
libedit                   3.1.20181209         hc058e9b_0    defaults
libffi                    3.2.1                hd88cf55_4    defaults
libgcc                    7.2.0                h69d50b8_2    defaults
libgcc-ng                 8.2.0                hdf63c60_1    defaults
libgfortran-ng            7.3.0                hdf63c60_0    defaults
libpng                    1.6.37               hbc83047_0    defaults
libstdcxx-ng              8.2.0                hdf63c60_1    defaults
libtiff                   4.0.10               h2733197_2    defaults
matplotlib                3.0.3                    pypi_0    pypi
mkl                       2019.3                      199    defaults
mkl_fft                   1.0.12           py37ha843d7b_0    defaults
mkl_random                1.0.2            py37hd81dba3_0    defaults
ncurses                   6.1                  he6710b0_1    defaults
ninja                     1.9.0            py37hfd86e86_0    defaults
numpy                     1.16.3           py37h7e9f1db_0    defaults
numpy-base                1.16.3           py37hde5b4d6_0    defaults
olefile                   0.46                     py37_0    defaults
opencv-python             4.1.0.25                 pypi_0    pypi
openssl                   1.1.1b               h7b6447c_1    defaults
pillow                    6.0.0                    pypi_0    pypi
pip                       19.1.1                   py37_0    defaults
protobuf                  3.7.1                    pypi_0    pypi
pycparser                 2.19                     py37_0    defaults
pyparsing                 2.4.0                    pypi_0    pypi
python                    3.7.3                h0371630_0    defaults
python-dateutil           2.8.0                    pypi_0    pypi
pytorch                   0.4.1           py37_py36_py35_py27__9.0.176_7.1.2_2    <unknown>
pyyaml                    5.1                      pypi_0    pypi
readline                  7.0                  h7b6447c_5    defaults
setuptools                41.0.1                   py37_0    defaults
six                       1.12.0                   pypi_0    pypi
sqlite                    3.28.0               h7b6447c_0    defaults
tensorboardx              1.6                      pypi_0    pypi
tk                        8.6.8                hbc83047_0    defaults
torchvision               0.2.2.post3              pypi_0    pypi
tqdm                      4.32.1                   pypi_0    pypi
wheel                     0.33.2                   py37_0    defaults
xz                        5.2.4                h14c3975_4    defaults
yacs                      0.1.6                    pypi_0    pypi
zlib                      1.2.11               h7b6447c_3    defaults
zstd                      1.3.7                h0b5b093_0    defaults
```

echo $PYTHONPATH 输出：Traceback (most recent call last):
  File "../../tools/test.py", line 13, in <module>
    from pysot.core.config import cfg
ModuleNotFoundError: No module named 'pysot'
`/home/myusername/pysot: `   应该也没问题

我执行tools下的test.py时(没有加sudo)，报错：　
`RuntimeError: CUDA error: unknown error`，查了下是没加sudo.

之后我加了sudo 之后也把后面的python命令变成了anaconda3/envs/pysot/bin/python3.7。

发现还是报错：　
```
Traceback (most recent call last):
  File "../../tools/test.py", line 13, in <module>
    from pysot.core.config import cfg
ModuleNotFoundError: No module named 'pysot'
```

**Comment by TeslaHua** [comment]
我自己解决了，我看到test.py和eval.py只需要toolkit和pysot两个依赖包，我直接把它俩放到了~/anaconda3/envs/pysot/lib/python3.7/site-packages/里面可以直接运行了。

**Comment by chenbolinstudent** [comment]
python torch.distributed.launch --nproc_per_node=1 --master_port=2333 ../../tools/train.py --cfg config.yaml

No module named 'pysot'

**Comment by WuZheBao0914** [comment]
> 我自己解决了，我看到test.py和eval.py只需要toolkit和pysot两个依赖包，我直接把它俩放到了~/anaconda3/envs/pysot/lib/python3.7/site-packages/里面可以直接运行了。

解决了！！！非常感激你！

**Comment by StoneWST** [comment]
If you use windows, you can replace "export PYTHONPATH=/path/to/PySOT:$PYTHONPATH" with the following code adding into your files.

import sys
sys.path.append('/path/to/PySOT')


It can also solve the issue: No module named 'pysot'
