### ISSUE TITLE
model size different

### ISSUE THREAD

**Issue by MaxLin86** [STVIR/pysot#81]
I want to train pysot based on mobilenetV2.
The siamrpn_mobilev2_l234_dwxcorr model that downloaded in ModelZoo was 44.9MB in Ubuntu16 system.
But when I train a new model using config in "experiments/siamrpn_mobilev2_l234_dwxcorr/config.yaml", the model size was 75.6MB.

So is this normal？

**Comment by lb1100** [comment]
there is not optimizer state dict in our provided models. It's normal.
