### ISSUE TITLE
run demo failed on mobilev2

### ISSUE THREAD

**Issue by MaxLin86** [STVIR/pysot#82]
terminal:
python tools/demo.py --config experiments/siamrpn_mobilev2_l234_dwxcorr/config.yaml --snapshot experiments/siamrpn_mobilev2_l234_dwxcorr/model.pth --video demo/bag.avi 

error:
RuntimeError: Error(s) in loading state_dict for ModelBuilder:
	Missing key(s) in state_dict: "rpn_head.cls_weight", "rpn_head.loc_weight".

alexnet and r50 are ok.

**Comment by StrangerZhang** [comment]
Fix it! Pull the repo, you will get the correct mobilev2 config.yaml

**Comment by MaxLin86** [comment]
> Fix it! Pull the repo, you will get the correct mobilev2 config.yaml

Thanks, really appreciate it.
