### ISSUE TITLE
train siamrpn_alex failed

### ISSUE THREAD

**Issue by MaxLin86** [STVIR/pysot#85]
When I train siamrpn_alex in experiments using "python -m torch.distributed.launch --nproc_per_node=4 --master_port=2341 ../../tools/train.py --cfg config.yaml
", it give me this error.

It seems like network structure error?

```
result = self.forward(*input, **kwargs)
  File "/root/ly18/pysot/pysot/utils/distributed.py", line 43, in forward
    return self.module(*args, **kwargs)
  File "/opt/conda/envs/pysot/lib/python3.7/site-packages/torch/nn/modules/module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "/root/ly18/pysot/pysot/models/model_builder.py", line 105, in forward
    loc_loss = weight_l1_loss(loc, label_loc, label_loc_weight)
  File "/root/ly18/pysot/pysot/models/loss.py", line 45, in weight_l1_loss
    diff = (pred_loc - label_loc).abs()
RuntimeError: The size of tensor a (17) must match the size of tensor b (25) at non-singleton dimension 4
```

I have trained siamrpn_mobilev2 already.

**Comment by lb1100** [comment]
Use this config [siamrpn_alex_dwxcorr_16gpu](https://github.com/STVIR/pysot/blob/master/experiments/siamrpn_alex_dwxcorr_16gpu/config.yaml).
AlexNet's config is different from resent.

**Comment by MaxLin86** [comment]
> Use this config [siamrpn_alex_dwxcorr_16gpu](https://github.com/STVIR/pysot/blob/master/experiments/siamrpn_alex_dwxcorr_16gpu/config.yaml).
> AlexNet's config is different from resent.

This config have not pretrained model in ModelZoo.

And the first error occur when I using config [experiments/siamrpn_alex_dwxcorr/config.yaml](url)

**Comment by lb1100** [comment]
In [TRAIN.md](https://github.com/STVIR/pysot/blob/master/TRAIN.md#download-pretrained-backbones), we provided ImageNet pretrained feature model of AlexNet and ResNet-50.

**Comment by lb1100** [comment]
`siamrpn_alex_dwxcorr` is only for inference, there is no training parameters in the config. If you want to fine-tune alexnet, you can use `siamrpn_alex_dwxcorr_16gpu` as config, and load the pretrained network.

**Comment by MaxLin86** [comment]
Where is the pretrained model?

The link [https://drive.google.com/drive/folders/1t62x56Jl7baUzPTo0QrC4jJnwvPZm-2m](url)  in ModelZoo?

**Comment by lb1100** [comment]
If you want a ImageNet pretrained model to reimplement our SiamRPN's performance, use [TRAIN.md](https://github.com/STVIR/pysot/blob/master/TRAIN.md#download-pretrained-backbones). If you want to finetune from our pretrained models (our tracking pretrained model) on other dataset, use the link provided in ModelZoo.

**Comment by MaxLin86** [comment]
Thanks.
I realize that pretrained backbones in "TRAIN.md" are different from pretrained models in ModelZoo.

By the way, siamrpn_alex_dwxcorr_16gpu seems using 16 gpu to train. 
If only 4 gpu to train, should I change learning rate corresponding？

**Comment by StrangerZhang** [comment]
You don't need to change the learning rate, the default reduce is *sum*.

**Comment by MaxLin86** [comment]
ok, thanks again.

**Comment by yustaub** [comment]
@MaxLin86 @StrangerZhang @lb1100    if I want to fine-tune from the pretrained models on my dataset, change the BACKBONE:PRETRAINED:'pretrained_models/alexnet-bn.pth' with the provides model in the model zoo?thanks for your reply!
