### ISSUE TITLE
update template during tracking

### ISSUE THREAD

**Issue by kodonnell** [STVIR/pysot#86]
Is there are reason why we don't update the template as we're tracking? Put another way, why `tracker.init(...)` is only called in the first frame in `demo.py`? I feel it'd get better results for tracking over long periods of time, or for slowly changing objects (e.g. people moving etc.).

**Comment by StrangerZhang** [comment]
Good question! However we find either use moving average to update template frame or reinitialize the template frame could not improve the tracking result.

**Comment by kodonnell** [comment]
Interesting. Is that on datasets with deformable objects over long periods (e.g. people walking)? Moving average is also a clever idea. I'd be interested to see the code added if you already have it and it's easy.
