### ISSUE TITLE
How to launch webcam demo with trained model ?

### ISSUE THREAD

**Issue by shenfanML** [STVIR/pysot#87]
> python tools/demo.py \
    --config experiments/siamrpn_r50_l234_dwxcorr/config.yaml \
    --snapshot experiments/siamrpn_r50_l234_dwxcorr/model.pth

How to modify the argument --snapshot when I use trained model to launch the webcam demo?
As when I trained the net with COCO dataset, there were ten checkpoint_e*.pth files in the snapshot folder.

**Comment by lb1100** [comment]
All checkpoints can be used to launch webcam demo. However, you may need to select the best model, which can be done by testing them on VOT or other dataset.

**Comment by shenfanML** [comment]
> python tools/demo.py \
    --config experiments/siamrpn_r50_l234_dwxcorr_8gpu/config.yaml \
    --snapshot experiments/siamrpn_r50_l234_dwxcorr_8gpu/snapshot/checkpoint_e2.pth

I use the script above and encounter problems below:

> Traceback (most recent call last):
  File "tools/demo.py", line 109, in <module>
    main()
  File "tools/demo.py", line 69, in main
    map_location=lambda storage, loc: storage.cpu()))
  File "/home/wangdong/anaconda3/envs/pysot/lib/python3.7/site-packages/torch/nn/modules/module.py", line 719, in load_state_dict
    self.__class__.__name__, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for ModelBuilder:
	Missing key(s) in state_dict: "backbone.conv1.weight", "backbone.bn1.weight", "backbone.bn1.bias", "backbone.bn1.running_mean", "backbone.bn1.running_var", "backbone.layer1.0.conv1.weight", "backbone.layer1.0.bn1.weight", "backbone.layer1.0.bn1.bias",
 ......
Unexpected key(s) in state_dict: "epoch", "state_dict", "optimizer".

**Comment by zhysee** [comment]
I got the same error, have you sovle this problem?

**Comment by Emanuel-c** [comment]
me too, have you solved this problem

**Comment by IrectionD** [comment]
I met this error too, I wish someone can solve it.

**Comment by yc-zc** [comment]
> > python tools/demo.py 
> >     --config experiments/siamrpn_r50_l234_dwxcorr_8gpu/config.yaml 
> >     --snapshot experiments/siamrpn_r50_l234_dwxcorr_8gpu/snapshot/checkpoint_e2.pth
> 
> I use the script above and encounter problems below:
> 
> > Traceback (most recent call last):
> > File "tools/demo.py", line 109, in 
> > main()
> > File "tools/demo.py", line 69, in main
> > map_location=lambda storage, loc: storage.cpu()))
> > File "/home/wangdong/anaconda3/envs/pysot/lib/python3.7/site-packages/torch/nn/modules/module.py", line 719, in load_state_dict
> > self.**class**.**name**, "\n\t".join(error_msgs)))
> > RuntimeError: Error(s) in loading state_dict for ModelBuilder:
> > Missing key(s) in state_dict: "backbone.conv1.weight", "backbone.bn1.weight", "backbone.bn1.bias", "backbone.bn1.running_mean", "backbone.bn1.running_var", "backbone.layer1.0.conv1.weight", "backbone.layer1.0.bn1.weight", "backbone.layer1.0.bn1.bias",
> > ......
> > Unexpected key(s) in state_dict: "epoch", "state_dict", "optimizer".

It seems your weights was not properly loaded.

**Comment by yc-zc** [comment]
Since no further question is asked, I'm closing it for now.
Please reopen it or create a new issue if you have further question.
