### ISSUE TITLE
two node training problem

### ISSUE THREAD

**Issue by chenbolinstudent** [STVIR/pysot#88]
Node 1: (IP: 192.168.1.1, and has a free port: 2333) master node

CUDA_VISIBLE_DEVICES=0,1,2,3,4,5,6,7
python -m torch.distributed.launch \
    --nnodes=2 \
    --node_rank=0 \
    --nproc_per_node=8 \
    --master_addr=192.168.1.1 \  # adjust your ip here
    --master_port=2333 \
    ../../tools/train.py
Node 2:

CUDA_VISIBLE_DEVICES=0,1,2,3,4,5,6,7
python -m torch.distributed.launch \
    --nnodes=2 \
    --node_rank=1 \
    --nproc_per_node=8 \
    --master_addr=192.168.1.1 \
    --master_port=2333 \
    ../../tools/train.py

why it do not need the --cfg config.yaml ?
and how to  run the Node 1 and Node 2 at the same time? 
run Node 1 first and run the Node 2 later? please give the detail。

**Comment by lb1100** [comment]
You can parse `--cfg config.yaml`. This code has default value for cfg, which is config.yaml.

**Comment by chenbolinstudent** [comment]
whether I run Node 1 first and run the Node 2 later?  or just run Node 1?
and the result save in Node 1 or Node 2?
can you say the distributed?

**Comment by lb1100** [comment]
run code on master node first.  Details please refer to [launch-utility](https://pytorch.org/docs/stable/distributed.html#launch-utility).

Results are saved by process whose rank==0, which is on Node 1.

**Comment by chenbolinstudent** [comment]
RuntimeError: Address already in use at /pytorch/torch/lib/THD/process_group/General.cpp:17
I have set the right IP address

**Comment by xiaotian3** [comment]
How to locate the ip and  port for free?

**Comment by xiaotian3** [comment]
have your solver the problem ?could you explan the detals ?

**Comment by yc-zc** [comment]
> RuntimeError: Address already in use at /pytorch/torch/lib/THD/process_group/General.cpp:17
> I have set the right IP address

Maybe consider tp change to another address or port.

**Comment by yc-zc** [comment]
Since no further question is asked, I'm closing it for now.
Please reopen it or create a new issue if you have further question.
