### ISSUE TITLE
problem in YOUTUBEBB datasets

### ISSUE THREAD

**Issue by zhanght021** [STVIR/pysot#89]
I download the YOUTUBEBB dataset you uploaded, but in the folder train0056/0/Z6BVtmEMfkI,there is no any images, but in the train.json, Z6BVtmEMfkI has two targets, and each targets has about 10 images, it will cause 'NoneType' object has no attribute 'shape'

**Comment by StrangerZhang** [comment]
It's a little wired. I re-upload the  *train0056.tar*. If you find similar problems, fell free to let us know.

**Comment by zhanght021** [comment]
in train0046/10/T9MJbMv2_-c Su0nbwH... SiYBHA... SKGRud_x... T62iQhik... 
some folder is no image, some folder is lack of part of image
in train0035/14/LSQ3EV.., lack of 000043.00.x.jpg
@StrangerZhang

**Comment by lb1100** [comment]
Try this new link in [TRAIN.md](https://github.com/STVIR/pysot/blob/master/TRAIN.md#prepare-training-dataset)

**Comment by zhanght021** [comment]
@lb1100  thanks
