### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'shape'

### ISSUE THREAD

**Issue by chenbolinstudent** [STVIR/pysot#90]
after set

yt_bb
    crop511
         train0000
         train0001
...
    train.json

File "/home/ty/PycharmProjects/pysot-master/pysot/datasets/dataset.py", line 218, in _get_bbox
    imh, imw = image.shape[:2]
AttributeError: 'NoneType' object has no attribute 'shape'

**Comment by StrangerZhang** [comment]
Re-download *train0056.tar*. Maybe could solve your problem.

**Comment by chenbolinstudent** [comment]
thanks

**Comment by chenbolinstudent** [comment]
when use the new youtube_bb
AttributeError: 'NoneType' object has no attribute 'shape'

@StrangerZhang

**Comment by chenbolinstudent** [comment]
when only use the coco
AttributeError: 'NoneType' object has no attribute 'shape'

@StrangerZhang
why?
