### ISSUE TITLE
out of memory

### ISSUE THREAD

**Issue by chenbolinstudent** [STVIR/pysot#91]
when train after e10 ,it out of memory
how much it need?

**Comment by lb1100** [comment]
We conduct our experiments on 1080TI, so 11G is enough.  If your GPU memory is not enough, try  to use smaller batch size.

**Comment by chenbolinstudent** [comment]
why train without yourube is ok, but with it 1080TI  is out of  memory

**Comment by chenbolinstudent** [comment]
smaller batch size will make the result poorer?

**Comment by lb1100** [comment]
Not sure, it need to be test on your own. We just simply use as many as we can to fully use the GPU memory.
