### ISSUE TITLE
Resume bug： ValueError: loaded state dict contains a parameter group that doesn't match the size of optimizer's group

### ISSUE THREAD

**Issue by qingchunlizhi** [STVIR/pysot#92]
when I resume from checkpoint_e10.pth(current_epoch >= cfg.BACKBONE.TRAIN_EPOCH) ,I get a error : ValueError: loaded state dict contains a parameter group that doesn't match the size of optimizer's group. But resume from checkpoint_e9.pth will work well . could anyone tell me how to slove this problem? Thanks!

**Comment by shizhenjun** [comment]
https://github.com/STVIR/pysot/issues/77

**Comment by qingchunlizhi** [comment]
> #77

I have tried,but it not works.

**Comment by lb1100** [comment]
Since Epoch 10's optimizer state dict changes (feature part included), it will fail. Try to use checkpoint_e9.pth or use PRETRAINED instead of RESUME. We don't use old optimizer state dict after optimizer changed. So using PRETRAINED will yield same results.

**Comment by qingchunlizhi** [comment]
I modified this code in model_load.py,then it can resume checkpoint_e10.pth:
https://github.com/STVIR/pysot/blob/5fb3970febcdb3d69cfc0b7d2f6534fe0c547b53/pysot/utils/model_load.py#L79
    if "state_dict" in ckpt.keys():
        ckpt_model_dict = remove_prefix(ckpt['state_dict'],'module.')
    else:
        ckpt_model_dict = remove_prefix(ckpt, 'module.')

**Comment by shizhenjun** [comment]
@qingchunlizhi 我感觉你这样的改法是存在问题的，当resume的epoch大于10时，并不是backbone的所有层都可训练；所以改build_opt_lr()这个函数才是正确的。举例来说，以res50为例，当epoch小于10时，所有层都不训练，当epoch大于10时，只有layer2、layer3、layer4参与训练；如果不改动build_opt_lr()这个函数，当在epoch大于10进行resume，那么res50的所有层都是可训练的；因为构建网络时全部参数默认是可训练，这时候手动把layer2、layer3、layer4设置为可训练，其实并没什么变化。

**Comment by xi-mao** [comment]
> @qingchunlizhi 我感觉你这样的改法是存在问题的，当resume的epoch大于10时，并不是backbone的所有层都可训练；所以改build_opt_lr()这个函数才是正确的。举例来说，以res50为例，当epoch小于10时，所有层都不训练，当epoch大于10时，只有layer2、layer3、layer4参与训练；如果不改动build_opt_lr()这个函数，当在epoch大于10进行resume，那么res50的所有层都是可训练的；因为构建网络时全部参数默认是可训练，这时候手动把layer2、layer3、layer4设置为可训练，其实并没什么变化。

大于10的时候并不会出现所有层都会训练啊，有cfg.BACKBONE.TRAIN_LAYERS在约束，他这个问题是从10到11resum的时候报的错，因为在1~10 backbone没有训练，当resum的时候backone有三层被加入到训练参数中，所以会报错 doesn't match the size of optimizer's 。

**Comment by xi-mao** [comment]
其实可以直接注释掉 optimizer.load_state_dict(ckpt['optimizer'])  因为
            if cfg.BACKBONE.TRAIN_EPOCH == epoch:
                logger.info('start training backbone.')
                optimizer, lr_scheduler = build_opt_lr(model.module, epoch)
                logger.info("model\n{}".format(describe(model.module)))
当epoch=10  的时候，optimizer会重新生成。

**Comment by xi-mao** [comment]
我有一个问题，问什么SiameseRPN++ 训练到第10个epoch会自动停掉

**Comment by yc-zc** [comment]
由于本issue没有得到更进一步的提问，我现在将其关闭。
如有新的问题，请重新打开它或者创建一个新的issue。

**Comment by PhenomenalOnee** [comment]
Well #77 didn't work for me while resuming from checkpoint_18.pth. The problem is when we resume, the model and optimizer passed in the restore_from function are suitable for epoch less than 10 (till backbone is not training) because the cfg.TRAIN.START_EPOCH is 0 (passed in build_opt_lr function just before restore_from) initially so this mismatches the optimizer after backbone start training. So to resume my training , I pass the cfg.TRAIN.START_EPOCH as 19 and when build_opt_lr function receives epoch greater than 10 (i.e Backbone training starts) it produces the model and optimizer suitable for resuming. And i can resume my training.
