### ISSUE TITLE
AUC on OTB100  0.54， training on VID and ytbb

### ISSUE THREAD

**Issue by xi-mao** [STVIR/pysot#96]
I trained siamrpn_alex_dwxcorr_16gpu on VID and ytbb. but it's only got AUC 0.54 on OTB100. I train twice，and the results is same。I didn't change the hyperparameters。 I think the reason is that the hyperparameters is set for traning four datasets。Maye it’s not suitable for two datasets。
 Anyone can explain to me？

**Comment by longqiwf** [comment]
You can change some hyperparameters like epoch in config.yaml and the VIDEOS_PER_EPOCH in pysot.core.config.py, matching with your datasets.

**Comment by csg1111** [comment]
I trained   siamrpn_alex_dwxcorr_16gpu on GOT-10k train dataset, it's performance better than yours, but 
it can't catch up with author's ,can we  communicate with each other?

**Comment by liuyun19951104** [comment]
can you present how the VID dataset is? i cannot download it, and i want to train in my own video dataset. i don't know how to do?
