### ISSUE TITLE
KeyError: 'epoch'

### ISSUE THREAD

**Issue by chenbolinstudent** [STVIR/pysot#97]
[2019-07-08 13:15:21,166-rk0-train.py#370] resume from /home/cbl/PycharmProjects/pysot-master/experiments/siamrpn_r50_l234_dwxcorr/model.pth
Traceback (most recent call last):
  File "../../tools/train.py", line 386, in <module>
    main()
  File "../../tools/train.py", line 374, in main
    restore_from(model, optimizer, cfg.TRAIN.RESUME)
  File "/home/cbl/PycharmProjects/pysot-master-train/pysot/utils/model_load.py", line 77, in restore_from
Traceback (most recent call last):
  File "../../tools/train.py", line 386, in <module>
    epoch = ckpt['epoch']
KeyError: 'epoch'

**Comment by zhanght021** [comment]
the chinese meaning of resume is "中断后恢复", if you want to train upon the model.pth ,you should use cfg.TRAIN.PRETRAINED; model.pth only has model parameters,do not have (epoch, optimizer) , you should read the code a little carefully

**Comment by chenbolinstudent** [comment]
thanks,
then  the  resnet50.model have what?

**Comment by zhanght021** [comment]
resnet50.model is the pretrained model of backbone ,it only has the parameters of backbone network resnet50,
and model.pth is the full model of SiamRPN the author trained,

**Comment by chenbolinstudent** [comment]
resnet50.model is the result of train imagenet ,

siamrpn_r50_l234_dwxcorr/model.pth  is load the resnet50.model  and the train coco det vid youtube_bb?

**Comment by zhanght021** [comment]
好吧，我用中文吧，英文确实不太好，model.pth是作者已经训练好的完整模型，你可以直接进行测试，可以直接在VOT2018上得到0.415这个结果；
如果你单纯想自己训练出作者的结果出来的话，你就只需加载进去resnet50.model就行了，然后再数据集上进行训练；和model.pth没有任何关系

**Comment by chenbolinstudent** [comment]
那我想接着训练时，一定要导入resnet50.model，而不能导入siamrpn_r50_l234_dwxcorr/model.pth？
这样就不能在0.415基础上继续训练了？

**Comment by zhanght021** [comment]
你可以接着训练，可以在model.pth上面接着训练，那估计得换你自己的数据集，或者别的数据集了吧，作者训练的4的数据集估计已经训练到收敛的不能再收敛了，
如果想在0.415上接着训练的话，也可以啊，train.py中是先加载resnet.model,然后后面才是cfg.TRAIN.PRETRAINED，其实把model.pth已经把resnet.model覆盖掉了，其实相当于resnet.model没有加载进去哈

**Comment by zhanght021** [comment]
你想在在0.415上训练的话，可以把两个都导入，其实相当于model.pth吧resnet50.model覆盖了

你也可以将cfg.BACKBONE.PRETRAINED=False或者置为空，那么这句话也就不执行了哈，只需要导入model.pth就行了，其实代码里面还是挺清楚的

**Comment by chenbolinstudent** [comment]
__C.TRAIN.EPOCH = 20

__C.DATASET.VIDEOS_PER_EPOCH = 600000

__C.BACKBONE.TRAIN_EPOCH = 10

可以说一下他们的关系吗？

**Comment by zhanght021** [comment]
第一个，总共训练次数
第二个，训练用到的样本数量
第三个，第11个epoch开始训练backbone

**Comment by chenbolinstudent** [comment]
那用那四个数据集训练时，一定要__C.DATASET.VIDEOS_PER_EPOCH = 600000？
如果想减少迭代次数应该设置哪？
当我想接着训练时设置
__C.BACKBONE.TRAIN_EPOCH = 1
__C.TRAIN.EPOCH = 2
会报错

**Comment by zhanght021** [comment]
不一定要60万，你可以少设置一点，那估计效果也会变差一点吧，
后面那个我没试过 ，不过你可以稍微看一下代码，然后应该比较快就能调试通了吧，

**Comment by chenbolinstudent** [comment]
当__C.DATASET.VIDEOS_PER_EPOCH = 600000
想减少迭代次数应该设置哪？

**Comment by chenbolinstudent** [comment]
当__C.DATASET.VIDEOS_PER_EPOCH = 600000
想减少迭代次数应该设置哪？就是想迭代很少的次数，然后达到和0.415差不多的结果，谢谢。

**Comment by zhanght021** [comment]
迭代次数是什么意思，是每个epoch减少iter吗，那只能通过增加batchsize的方式了，或者只能通过减小600000了，在config.yaml中的TRAIN下面有一个batch_size你可以增加那个值，然后就可以减少iter了，但是那样子就会更容易出现out of memory了

**Comment by chenbolinstudent** [comment]
以前代码一般迭代次数都是很大的数，
__C.TRAIN.EPOCH = 20
现在怎么会这么少，这个20好像又是保存的模型的个数吧。

另外batch_size和GPU的个数会影响 结果吗？

**Comment by chenbolinstudent** [comment]
以前代码一般迭代次数都是很大的数，
__C.TRAIN.EPOCH = 20
现在怎么会这么少，这个20好像又是保存的模型的个数吧。

另外batch_size和GPU的个数会影响 结果吗？
VIDEOS_PER_EPOCH 在哪里使用了？

**Comment by zhanght021** [comment]
VIDEOS_PER_EPOCH代表的是你每一个epoch用的样本数，也就是说每个epoch用60万对样本

至于你说的为什么是20这么小的数字呢，谁知道呢，这个代码训练backbone为AlexNet的时候是50 ，他是没一个epoch结束，就把结果保存下来了，，，，你可以看一下代码的，其实代码还是比较好理解的

**Comment by chenbolinstudent** [comment]
好的，谢谢，那么batch_size和GPU的个数会影响 结果吗？

**Comment by zhanght021** [comment]
应该也会有影响的，作者用16GPU和8GPU训练的时候用了不同大小的batchsize

不过应该是有影响，但是不会有特别大的影响

**Comment by qingchunlizhi** [comment]
> 那用那四个数据集训练时，一定要__C.DATASET.VIDEOS_PER_EPOCH = 600000？
> 如果想减少迭代次数应该设置哪？
> 当我想接着训练时设置
> __C.BACKBONE.TRAIN_EPOCH = 1
> __C.TRAIN.EPOCH

> 那用那四个数据集训练时，一定要__C.DATASET.VIDEOS_PER_EPOCH = 600000？
> 如果想减少迭代次数应该设置哪？
> 当我想接着训练时设置
> __C.BACKBONE.TRAIN_EPOCH = 1
> __C.TRAIN.EPOCH = 2
> 会报错

改这个地方吧：
把configure.yaml里面BACKBONE:  TRAIN_EPOCH: 10 改为2.就能从第3个epoch开始训练backbone

**Comment by chenbolinstudent** [comment]
现在用3块GPU , 跑它的siamrpn_r50_l234_dwxcorr_8gpu/config.yaml
达不到0.415。batch_size 和 penalty_k 和  window influence 应该怎么设置呢？

**Comment by xi-mao** [comment]
> 现在用3块GPU , 跑它的siamrpn_r50_l234_dwxcorr_8gpu/config.yaml
> 达不到0.415。batch_size 和 penalty_k 和 window influence 应该怎么设置呢？

我跑到第11个epoch的时候会自动断掉，你是怎么设置的啊。

**Comment by yc-zc** [comment]
> 第一个，总共训练次数
> 第二个，训练用到的样本数量
> 第三个，第11个epoch开始训练backbone



> [2019-07-08 13:15:21,166-rk0-train.py#370] resume from /home/cbl/PycharmProjects/pysot-master/experiments/siamrpn_r50_l234_dwxcorr/model.pth
> Traceback (most recent call last):
> File "../../tools/train.py", line 386, in
> main()
> File "../../tools/train.py", line 374, in main
> restore_from(model, optimizer, cfg.TRAIN.RESUME)
> File "/home/cbl/PycharmProjects/pysot-master-train/pysot/utils/model_load.py", line 77, in restore_from
> Traceback (most recent call last):
> File "../../tools/train.py", line 386, in
> epoch = ckpt['epoch']
> KeyError: 'epoch'

由于本issue没有得到更进一步的提问，我现在将其关闭。
如有新的问题，请重新打开它或者创建一个新的issue。

**Comment by Jee-King** [comment]
@chenbolinstudent  __C.DATASET.VIDEOS_PER_EPOCH的大小等于训练序列的个数吗?
