### ISSUE TITLE
Missing config value causes AttributeError

### ISSUE THREAD

**Issue by jhultman** [STVIR/pysot#99]
In `config.yaml` for the siammask_r50_l3 model, `cfg.REFINE.REFINE` is `True` but `cfg.TRAIN.LR.BASE_LR` is unspecified (not even in the default `config.py`). The missing attribute causes the YACS config node to throw AttributeError on [line 107](https://github.com/STVIR/pysot/blob/5fb3970febcdb3d69cfc0b7d2f6534fe0c547b53/tools/train.py#L107) in `train.py`.
```
if cfg.REFINE.REFINE:
    trainable_params += [{'params': model.refine_head.parameters(),
                          'lr': cfg.TRAIN.LR.BASE_LR}]
```
Kindly let me know if I am misunderstanding something.

**Comment by StrangerZhang** [comment]
Currently, training siammask is not supported.
